// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Access Key ID for API operations.
func GetAccessKeyId(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:accessKeyId")
}

// The path to your configuration file in which you have defined your credentials.
func GetConfigFile(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:configFile")
}
func GetEndpoints(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:endpoints")
}

// tls insecure connection
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "outscale:insecure")
}

// The name of your profile in which you define your credencial
func GetProfile(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:profile")
}

// The Region for API operations.
func GetRegion(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:region")
}

// The Secret Key ID for API operations.
func GetSecretKeyId(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:secretKeyId")
}

// The path to your x509 cert
func GetX509CertPath(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:x509CertPath")
}

// The path to your x509 key
func GetX509KeyPath(ctx *pulumi.Context) string {
	return config.Get(ctx, "outscale:x509KeyPath")
}
