apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: observability
spec:
  ports:
    - port: 8428
      name: http
  selector:
    app: victoriametrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: observability
  labels:
    app: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
      - name: victoriametrics
        image: victoriametrics/victoria-metrics:v1.93.0
        args:
          - "-promscrape.config=/config/scrape.yml"
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1w"
          - "-memory.allowedPercent=60"
        ports:
          - containerPort: 8428
            name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
        volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          configMap:
            name: victoriametrics-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: observability
data:
  scrape.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'victoriametrics'
        static_configs:
          - targets: ['localhost:8428']
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        ports:
          - containerPort: 3000
        env:
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true" # For ease of demo
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: "Admin"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: observability
spec:
  parentRefs:
  - name: openaether-gateway
  hostnames:
  - "grafana.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: grafana
      port: 3000
