apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: keycloak
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: keycloak-db-app
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak/db
      property: username
  - secretKey: password
    remoteRef:
      key: keycloak/db
      property: password
