version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Install dependencies
    cmds:
      - echo "Ensure tofu, talosctl, and kubectl are installed."

  deploy:
    desc: Deploy the cluster using OpenTofu
    dir: infrastructure/opentofu
    cmds:
      - tofu apply -var-file="tofu.tfvars"

  preview:
    desc: Preview changes
    dir: infrastructure/opentofu
    cmds:
      - tofu plan -var-file="tofu.tfvars"

  destroy:
    desc: Destroy the cluster
    dir: infrastructure/opentofu
    cmds:
      - tofu destroy -var-file="tofu.tfvars"

  kubeconfig:
    desc: Retrieve kubeconfig
    dir: infrastructure/opentofu
    cmds:
      - tofu output -raw talosconfig > talosconfig
      - echo "Use talosctl to retrieve kubeconfig using the talosconfig"
