version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  setup:
    desc: Install dependencies (OpenTofu, Talosctl, Kubectl, Task, pre-commit)
    # Note: For initial setup (when task is not installed yet), run ./scripts/setup.sh directly
    cmds:
      - ./scripts/setup.sh

  lint:
    desc: Lint and format code (OpenTofu, YAML)
    cmds:
      - tofu fmt -check -recursive infrastructure/opentofu
      - yamllint -c infrastructure/.yamllint apps/ infrastructure/
      - tflint --recursive infrastructure/opentofu

  fmt:
    desc: Format OpenTofu code
    cmds:
      - tofu fmt -recursive infrastructure/opentofu

  validate:
    desc: Validate OpenTofu code
    dir: infrastructure/opentofu
    cmds:
      - tofu init -backend=false
      - tofu validate

  security:
    desc: Run security scans (Trivy, Checkov, Gitleaks)
    cmds:
      - trivy config infrastructure/
      - checkov -d infrastructure/opentofu
      - gitleaks detect --source . --no-git

  test:
    desc: Run OpenTofu tests
    dir: infrastructure/opentofu
    cmds:
      - tofu test -var-file="tofu.tfvars"

  deploy:
    desc: Deploy the cluster using OpenTofu
    dir: infrastructure/opentofu
    cmds:
      - tofu apply -var-file="tofu.tfvars"

  destroy:
    desc: Destroy the cluster
    dir: infrastructure/opentofu
    cmds:
      - tofu destroy -var-file="tofu.tfvars"

  bootstrap:
    desc: Apply bootstrap manifests (ArgoCD)
    cmds:
      - kubectl apply -k apps/bootstrap/overlays/local

  secrets:
    desc: Initialize OpenBao secrets
    cmds:
      - ./scripts/init_secrets.sh

  kubeconfig:
    desc: Retrieve kubeconfig
    dir: infrastructure/opentofu
    cmds:
      - tofu output -raw talosconfig > talosconfig
      - echo "Use talosctl to retrieve kubeconfig using the talosconfig"
