version: "3"

vars:
  ENV: '{{.ENV | default "local"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  lint:
    desc: Run golangci-lint and yamllint
    cmds:
      - cd infrastructure && golangci-lint run ./...
      - yamllint .

  # ============================================
  # DEPLOYMENT TASKS (Multi-Environment)
  # ============================================

  deploy:
    desc: "Deploy cluster to environment. Usage: task deploy ENV=test"
    dir: infrastructure
    dotenv:
      - '.env'
      - 'environments/.env.{{.ENV}}'
    cmds:
      - pulumi login --local
      - pulumi stack select {{.ENV}} --create
      - pulumi up --stack {{.ENV}} --yes
      - pulumi stack output kubeconfig --stack {{.ENV}} --show-secrets > ../kubeconfig-{{.ENV}}.yaml
      - echo "âœ… Deployed to {{.ENV}}"
      - echo "Kubeconfig saved to kubeconfig-{{.ENV}}.yaml"

  destroy:
    desc: "Destroy cluster. Usage: task destroy ENV=test"
    dir: infrastructure
    dotenv:
      - '.env'
      - 'environments/.env.{{.ENV}}'
    cmds:
      - pulumi destroy --stack {{.ENV}} --yes
      - echo "ðŸ—‘ï¸ Destroyed {{.ENV}}"

  preview:
    desc: "Preview changes without applying. Usage: task preview ENV=test"
    dir: infrastructure
    dotenv:
      - '.env'
      - 'environments/.env.{{.ENV}}'
    cmds:
      - pulumi login --local
      - pulumi stack select {{.ENV}} --create
      - pulumi preview --stack {{.ENV}}

  status:
    desc: "Show cluster status. Usage: task status ENV=test"
    cmds:
      - kubectl --kubeconfig kubeconfig-{{.ENV}}.yaml get nodes
      - kubectl --kubeconfig kubeconfig-{{.ENV}}.yaml get pods -A

  # ============================================
  # SHORTCUT TASKS
  # ============================================

  local:up:
    desc: Deploy local Docker cluster (shortcut for deploy ENV=local)
    cmds:
      - task: deploy
        vars:
          ENV: local

  local:down:
    desc: Destroy local Docker cluster
    cmds:
      - task: destroy
        vars:
          ENV: local

  test:up:
    desc: Deploy test environment
    cmds:
      - task: deploy
        vars:
          ENV: test

  test:down:
    desc: Destroy test environment
    cmds:
      - task: destroy
        vars:
          ENV: test

  prod:up:
    desc: Deploy production environment
    cmds:
      - task: deploy
        vars:
          ENV: prod

  prod:down:
    desc: Destroy production environment
    cmds:
      - task: destroy
        vars:
          ENV: prod

  # ============================================
  # UTILITY TASKS
  # ============================================

  kubeconfig:
    desc: "Export kubeconfig. Usage: task kubeconfig ENV=test"
    dir: infrastructure
    dotenv:
      - '.env'
      - 'environments/.env.{{.ENV}}'
    cmds:
      - pulumi stack output kubeconfig --stack {{.ENV}} --show-secrets > ../kubeconfig-{{.ENV}}.yaml
      - echo "Kubeconfig saved to kubeconfig-{{.ENV}}.yaml"

  # generate:manifests:
  #   desc: Generate/Download required manifests (Gateway API) locally if missing
  #   cmds:
  #     - mkdir -p apps/infrastructure/gateway-api
  #     - curl -sL https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.0.0/standard-install.yaml -o apps/infrastructure/gateway-api/standard-install.yaml

  deploy:platform:
    desc: Deploy platform components via Kustomize
    cmds:
      - kubectl --kubeconfig kubeconfig-{{.ENV}}.yaml apply -k apps/platform/

  # ============================================
  # SETUP TASKS
  # ============================================

  setup:
    desc: Copy .env.example to .env
    dir: scripts
    cmds:
      - bash setup.sh
