// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AccessKey struct {
	pulumi.CustomResourceState

	AccessKeyId          pulumi.StringOutput        `pulumi:"accessKeyId"`
	CreationDate         pulumi.StringOutput        `pulumi:"creationDate"`
	ExpirationDate       pulumi.StringOutput        `pulumi:"expirationDate"`
	LastModificationDate pulumi.StringOutput        `pulumi:"lastModificationDate"`
	RequestId            pulumi.StringOutput        `pulumi:"requestId"`
	SecretKey            pulumi.StringOutput        `pulumi:"secretKey"`
	State                pulumi.StringOutput        `pulumi:"state"`
	Timeouts             AccessKeyTimeoutsPtrOutput `pulumi:"timeouts"`
	UserName             pulumi.StringPtrOutput     `pulumi:"userName"`
}

// NewAccessKey registers a new resource with the given unique name, arguments, and options.
func NewAccessKey(ctx *pulumi.Context,
	name string, args *AccessKeyArgs, opts ...pulumi.ResourceOption) (*AccessKey, error) {
	if args == nil {
		args = &AccessKeyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource AccessKey
	err = ctx.RegisterPackageResource("outscale:index/accessKey:AccessKey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAccessKey gets an existing AccessKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAccessKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AccessKeyState, opts ...pulumi.ResourceOption) (*AccessKey, error) {
	var resource AccessKey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/accessKey:AccessKey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AccessKey resources.
type accessKeyState struct {
	AccessKeyId          *string            `pulumi:"accessKeyId"`
	CreationDate         *string            `pulumi:"creationDate"`
	ExpirationDate       *string            `pulumi:"expirationDate"`
	LastModificationDate *string            `pulumi:"lastModificationDate"`
	RequestId            *string            `pulumi:"requestId"`
	SecretKey            *string            `pulumi:"secretKey"`
	State                *string            `pulumi:"state"`
	Timeouts             *AccessKeyTimeouts `pulumi:"timeouts"`
	UserName             *string            `pulumi:"userName"`
}

type AccessKeyState struct {
	AccessKeyId          pulumi.StringPtrInput
	CreationDate         pulumi.StringPtrInput
	ExpirationDate       pulumi.StringPtrInput
	LastModificationDate pulumi.StringPtrInput
	RequestId            pulumi.StringPtrInput
	SecretKey            pulumi.StringPtrInput
	State                pulumi.StringPtrInput
	Timeouts             AccessKeyTimeoutsPtrInput
	UserName             pulumi.StringPtrInput
}

func (AccessKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*accessKeyState)(nil)).Elem()
}

type accessKeyArgs struct {
	ExpirationDate *string            `pulumi:"expirationDate"`
	State          *string            `pulumi:"state"`
	Timeouts       *AccessKeyTimeouts `pulumi:"timeouts"`
	UserName       *string            `pulumi:"userName"`
}

// The set of arguments for constructing a AccessKey resource.
type AccessKeyArgs struct {
	ExpirationDate pulumi.StringPtrInput
	State          pulumi.StringPtrInput
	Timeouts       AccessKeyTimeoutsPtrInput
	UserName       pulumi.StringPtrInput
}

func (AccessKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*accessKeyArgs)(nil)).Elem()
}

type AccessKeyInput interface {
	pulumi.Input

	ToAccessKeyOutput() AccessKeyOutput
	ToAccessKeyOutputWithContext(ctx context.Context) AccessKeyOutput
}

func (*AccessKey) ElementType() reflect.Type {
	return reflect.TypeOf((**AccessKey)(nil)).Elem()
}

func (i *AccessKey) ToAccessKeyOutput() AccessKeyOutput {
	return i.ToAccessKeyOutputWithContext(context.Background())
}

func (i *AccessKey) ToAccessKeyOutputWithContext(ctx context.Context) AccessKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AccessKeyOutput)
}

type AccessKeyOutput struct{ *pulumi.OutputState }

func (AccessKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AccessKey)(nil)).Elem()
}

func (o AccessKeyOutput) ToAccessKeyOutput() AccessKeyOutput {
	return o
}

func (o AccessKeyOutput) ToAccessKeyOutputWithContext(ctx context.Context) AccessKeyOutput {
	return o
}

func (o AccessKeyOutput) AccessKeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.AccessKeyId }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) LastModificationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.LastModificationDate }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o AccessKeyOutput) Timeouts() AccessKeyTimeoutsPtrOutput {
	return o.ApplyT(func(v *AccessKey) AccessKeyTimeoutsPtrOutput { return v.Timeouts }).(AccessKeyTimeoutsPtrOutput)
}

func (o AccessKeyOutput) UserName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AccessKey) pulumi.StringPtrOutput { return v.UserName }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AccessKeyInput)(nil)).Elem(), &AccessKey{})
	pulumi.RegisterOutputType(AccessKeyOutput{})
}
