// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ApiAccessRule struct {
	pulumi.CustomResourceState

	ApiAccessRuleId         pulumi.StringOutput      `pulumi:"apiAccessRuleId"`
	CaIds                   pulumi.StringArrayOutput `pulumi:"caIds"`
	Cns                     pulumi.StringArrayOutput `pulumi:"cns"`
	Description             pulumi.StringPtrOutput   `pulumi:"description"`
	IpRanges                pulumi.StringArrayOutput `pulumi:"ipRanges"`
	OutscaleApiAccessRuleId pulumi.StringOutput      `pulumi:"outscaleApiAccessRuleId"`
	RequestId               pulumi.StringOutput      `pulumi:"requestId"`
}

// NewApiAccessRule registers a new resource with the given unique name, arguments, and options.
func NewApiAccessRule(ctx *pulumi.Context,
	name string, args *ApiAccessRuleArgs, opts ...pulumi.ResourceOption) (*ApiAccessRule, error) {
	if args == nil {
		args = &ApiAccessRuleArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ApiAccessRule
	err = ctx.RegisterPackageResource("outscale:index/apiAccessRule:ApiAccessRule", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApiAccessRule gets an existing ApiAccessRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApiAccessRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApiAccessRuleState, opts ...pulumi.ResourceOption) (*ApiAccessRule, error) {
	var resource ApiAccessRule
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/apiAccessRule:ApiAccessRule", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApiAccessRule resources.
type apiAccessRuleState struct {
	ApiAccessRuleId         *string  `pulumi:"apiAccessRuleId"`
	CaIds                   []string `pulumi:"caIds"`
	Cns                     []string `pulumi:"cns"`
	Description             *string  `pulumi:"description"`
	IpRanges                []string `pulumi:"ipRanges"`
	OutscaleApiAccessRuleId *string  `pulumi:"outscaleApiAccessRuleId"`
	RequestId               *string  `pulumi:"requestId"`
}

type ApiAccessRuleState struct {
	ApiAccessRuleId         pulumi.StringPtrInput
	CaIds                   pulumi.StringArrayInput
	Cns                     pulumi.StringArrayInput
	Description             pulumi.StringPtrInput
	IpRanges                pulumi.StringArrayInput
	OutscaleApiAccessRuleId pulumi.StringPtrInput
	RequestId               pulumi.StringPtrInput
}

func (ApiAccessRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*apiAccessRuleState)(nil)).Elem()
}

type apiAccessRuleArgs struct {
	CaIds                   []string `pulumi:"caIds"`
	Cns                     []string `pulumi:"cns"`
	Description             *string  `pulumi:"description"`
	IpRanges                []string `pulumi:"ipRanges"`
	OutscaleApiAccessRuleId *string  `pulumi:"outscaleApiAccessRuleId"`
}

// The set of arguments for constructing a ApiAccessRule resource.
type ApiAccessRuleArgs struct {
	CaIds                   pulumi.StringArrayInput
	Cns                     pulumi.StringArrayInput
	Description             pulumi.StringPtrInput
	IpRanges                pulumi.StringArrayInput
	OutscaleApiAccessRuleId pulumi.StringPtrInput
}

func (ApiAccessRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apiAccessRuleArgs)(nil)).Elem()
}

type ApiAccessRuleInput interface {
	pulumi.Input

	ToApiAccessRuleOutput() ApiAccessRuleOutput
	ToApiAccessRuleOutputWithContext(ctx context.Context) ApiAccessRuleOutput
}

func (*ApiAccessRule) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiAccessRule)(nil)).Elem()
}

func (i *ApiAccessRule) ToApiAccessRuleOutput() ApiAccessRuleOutput {
	return i.ToApiAccessRuleOutputWithContext(context.Background())
}

func (i *ApiAccessRule) ToApiAccessRuleOutputWithContext(ctx context.Context) ApiAccessRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiAccessRuleOutput)
}

type ApiAccessRuleOutput struct{ *pulumi.OutputState }

func (ApiAccessRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiAccessRule)(nil)).Elem()
}

func (o ApiAccessRuleOutput) ToApiAccessRuleOutput() ApiAccessRuleOutput {
	return o
}

func (o ApiAccessRuleOutput) ToApiAccessRuleOutputWithContext(ctx context.Context) ApiAccessRuleOutput {
	return o
}

func (o ApiAccessRuleOutput) ApiAccessRuleId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringOutput { return v.ApiAccessRuleId }).(pulumi.StringOutput)
}

func (o ApiAccessRuleOutput) CaIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringArrayOutput { return v.CaIds }).(pulumi.StringArrayOutput)
}

func (o ApiAccessRuleOutput) Cns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringArrayOutput { return v.Cns }).(pulumi.StringArrayOutput)
}

func (o ApiAccessRuleOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

func (o ApiAccessRuleOutput) IpRanges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringArrayOutput { return v.IpRanges }).(pulumi.StringArrayOutput)
}

func (o ApiAccessRuleOutput) OutscaleApiAccessRuleId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringOutput { return v.OutscaleApiAccessRuleId }).(pulumi.StringOutput)
}

func (o ApiAccessRuleOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiAccessRule) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApiAccessRuleInput)(nil)).Elem(), &ApiAccessRule{})
	pulumi.RegisterOutputType(ApiAccessRuleOutput{})
}
