// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FlexibleGpuLink struct {
	pulumi.CustomResourceState

	FlexibleGpuIds    pulumi.StringArrayOutput         `pulumi:"flexibleGpuIds"`
	FlexibleGpuLinkId pulumi.StringOutput              `pulumi:"flexibleGpuLinkId"`
	RequestId         pulumi.StringOutput              `pulumi:"requestId"`
	Timeouts          FlexibleGpuLinkTimeoutsPtrOutput `pulumi:"timeouts"`
	VmId              pulumi.StringOutput              `pulumi:"vmId"`
}

// NewFlexibleGpuLink registers a new resource with the given unique name, arguments, and options.
func NewFlexibleGpuLink(ctx *pulumi.Context,
	name string, args *FlexibleGpuLinkArgs, opts ...pulumi.ResourceOption) (*FlexibleGpuLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FlexibleGpuIds == nil {
		return nil, errors.New("invalid value for required argument 'FlexibleGpuIds'")
	}
	if args.VmId == nil {
		return nil, errors.New("invalid value for required argument 'VmId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource FlexibleGpuLink
	err = ctx.RegisterPackageResource("outscale:index/flexibleGpuLink:FlexibleGpuLink", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFlexibleGpuLink gets an existing FlexibleGpuLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFlexibleGpuLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FlexibleGpuLinkState, opts ...pulumi.ResourceOption) (*FlexibleGpuLink, error) {
	var resource FlexibleGpuLink
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/flexibleGpuLink:FlexibleGpuLink", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FlexibleGpuLink resources.
type flexibleGpuLinkState struct {
	FlexibleGpuIds    []string                 `pulumi:"flexibleGpuIds"`
	FlexibleGpuLinkId *string                  `pulumi:"flexibleGpuLinkId"`
	RequestId         *string                  `pulumi:"requestId"`
	Timeouts          *FlexibleGpuLinkTimeouts `pulumi:"timeouts"`
	VmId              *string                  `pulumi:"vmId"`
}

type FlexibleGpuLinkState struct {
	FlexibleGpuIds    pulumi.StringArrayInput
	FlexibleGpuLinkId pulumi.StringPtrInput
	RequestId         pulumi.StringPtrInput
	Timeouts          FlexibleGpuLinkTimeoutsPtrInput
	VmId              pulumi.StringPtrInput
}

func (FlexibleGpuLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*flexibleGpuLinkState)(nil)).Elem()
}

type flexibleGpuLinkArgs struct {
	FlexibleGpuIds    []string                 `pulumi:"flexibleGpuIds"`
	FlexibleGpuLinkId *string                  `pulumi:"flexibleGpuLinkId"`
	Timeouts          *FlexibleGpuLinkTimeouts `pulumi:"timeouts"`
	VmId              string                   `pulumi:"vmId"`
}

// The set of arguments for constructing a FlexibleGpuLink resource.
type FlexibleGpuLinkArgs struct {
	FlexibleGpuIds    pulumi.StringArrayInput
	FlexibleGpuLinkId pulumi.StringPtrInput
	Timeouts          FlexibleGpuLinkTimeoutsPtrInput
	VmId              pulumi.StringInput
}

func (FlexibleGpuLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*flexibleGpuLinkArgs)(nil)).Elem()
}

type FlexibleGpuLinkInput interface {
	pulumi.Input

	ToFlexibleGpuLinkOutput() FlexibleGpuLinkOutput
	ToFlexibleGpuLinkOutputWithContext(ctx context.Context) FlexibleGpuLinkOutput
}

func (*FlexibleGpuLink) ElementType() reflect.Type {
	return reflect.TypeOf((**FlexibleGpuLink)(nil)).Elem()
}

func (i *FlexibleGpuLink) ToFlexibleGpuLinkOutput() FlexibleGpuLinkOutput {
	return i.ToFlexibleGpuLinkOutputWithContext(context.Background())
}

func (i *FlexibleGpuLink) ToFlexibleGpuLinkOutputWithContext(ctx context.Context) FlexibleGpuLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlexibleGpuLinkOutput)
}

type FlexibleGpuLinkOutput struct{ *pulumi.OutputState }

func (FlexibleGpuLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlexibleGpuLink)(nil)).Elem()
}

func (o FlexibleGpuLinkOutput) ToFlexibleGpuLinkOutput() FlexibleGpuLinkOutput {
	return o
}

func (o FlexibleGpuLinkOutput) ToFlexibleGpuLinkOutputWithContext(ctx context.Context) FlexibleGpuLinkOutput {
	return o
}

func (o FlexibleGpuLinkOutput) FlexibleGpuIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *FlexibleGpuLink) pulumi.StringArrayOutput { return v.FlexibleGpuIds }).(pulumi.StringArrayOutput)
}

func (o FlexibleGpuLinkOutput) FlexibleGpuLinkId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpuLink) pulumi.StringOutput { return v.FlexibleGpuLinkId }).(pulumi.StringOutput)
}

func (o FlexibleGpuLinkOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpuLink) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o FlexibleGpuLinkOutput) Timeouts() FlexibleGpuLinkTimeoutsPtrOutput {
	return o.ApplyT(func(v *FlexibleGpuLink) FlexibleGpuLinkTimeoutsPtrOutput { return v.Timeouts }).(FlexibleGpuLinkTimeoutsPtrOutput)
}

func (o FlexibleGpuLinkOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpuLink) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlexibleGpuLinkInput)(nil)).Elem(), &FlexibleGpuLink{})
	pulumi.RegisterOutputType(FlexibleGpuLinkOutput{})
}
