// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type FlexibleGpu struct {
	pulumi.CustomResourceState

	DeleteOnVmDeletion pulumi.BoolOutput            `pulumi:"deleteOnVmDeletion"`
	FlexibleGpuId      pulumi.StringOutput          `pulumi:"flexibleGpuId"`
	Generation         pulumi.StringOutput          `pulumi:"generation"`
	ModelName          pulumi.StringOutput          `pulumi:"modelName"`
	State              pulumi.StringOutput          `pulumi:"state"`
	SubregionName      pulumi.StringOutput          `pulumi:"subregionName"`
	Timeouts           FlexibleGpuTimeoutsPtrOutput `pulumi:"timeouts"`
	VmId               pulumi.StringOutput          `pulumi:"vmId"`
}

// NewFlexibleGpu registers a new resource with the given unique name, arguments, and options.
func NewFlexibleGpu(ctx *pulumi.Context,
	name string, args *FlexibleGpuArgs, opts ...pulumi.ResourceOption) (*FlexibleGpu, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ModelName == nil {
		return nil, errors.New("invalid value for required argument 'ModelName'")
	}
	if args.SubregionName == nil {
		return nil, errors.New("invalid value for required argument 'SubregionName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource FlexibleGpu
	err = ctx.RegisterPackageResource("outscale:index/flexibleGpu:FlexibleGpu", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetFlexibleGpu gets an existing FlexibleGpu resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetFlexibleGpu(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *FlexibleGpuState, opts ...pulumi.ResourceOption) (*FlexibleGpu, error) {
	var resource FlexibleGpu
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/flexibleGpu:FlexibleGpu", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering FlexibleGpu resources.
type flexibleGpuState struct {
	DeleteOnVmDeletion *bool                `pulumi:"deleteOnVmDeletion"`
	FlexibleGpuId      *string              `pulumi:"flexibleGpuId"`
	Generation         *string              `pulumi:"generation"`
	ModelName          *string              `pulumi:"modelName"`
	State              *string              `pulumi:"state"`
	SubregionName      *string              `pulumi:"subregionName"`
	Timeouts           *FlexibleGpuTimeouts `pulumi:"timeouts"`
	VmId               *string              `pulumi:"vmId"`
}

type FlexibleGpuState struct {
	DeleteOnVmDeletion pulumi.BoolPtrInput
	FlexibleGpuId      pulumi.StringPtrInput
	Generation         pulumi.StringPtrInput
	ModelName          pulumi.StringPtrInput
	State              pulumi.StringPtrInput
	SubregionName      pulumi.StringPtrInput
	Timeouts           FlexibleGpuTimeoutsPtrInput
	VmId               pulumi.StringPtrInput
}

func (FlexibleGpuState) ElementType() reflect.Type {
	return reflect.TypeOf((*flexibleGpuState)(nil)).Elem()
}

type flexibleGpuArgs struct {
	DeleteOnVmDeletion *bool                `pulumi:"deleteOnVmDeletion"`
	Generation         *string              `pulumi:"generation"`
	ModelName          string               `pulumi:"modelName"`
	SubregionName      string               `pulumi:"subregionName"`
	Timeouts           *FlexibleGpuTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a FlexibleGpu resource.
type FlexibleGpuArgs struct {
	DeleteOnVmDeletion pulumi.BoolPtrInput
	Generation         pulumi.StringPtrInput
	ModelName          pulumi.StringInput
	SubregionName      pulumi.StringInput
	Timeouts           FlexibleGpuTimeoutsPtrInput
}

func (FlexibleGpuArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*flexibleGpuArgs)(nil)).Elem()
}

type FlexibleGpuInput interface {
	pulumi.Input

	ToFlexibleGpuOutput() FlexibleGpuOutput
	ToFlexibleGpuOutputWithContext(ctx context.Context) FlexibleGpuOutput
}

func (*FlexibleGpu) ElementType() reflect.Type {
	return reflect.TypeOf((**FlexibleGpu)(nil)).Elem()
}

func (i *FlexibleGpu) ToFlexibleGpuOutput() FlexibleGpuOutput {
	return i.ToFlexibleGpuOutputWithContext(context.Background())
}

func (i *FlexibleGpu) ToFlexibleGpuOutputWithContext(ctx context.Context) FlexibleGpuOutput {
	return pulumi.ToOutputWithContext(ctx, i).(FlexibleGpuOutput)
}

type FlexibleGpuOutput struct{ *pulumi.OutputState }

func (FlexibleGpuOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlexibleGpu)(nil)).Elem()
}

func (o FlexibleGpuOutput) ToFlexibleGpuOutput() FlexibleGpuOutput {
	return o
}

func (o FlexibleGpuOutput) ToFlexibleGpuOutputWithContext(ctx context.Context) FlexibleGpuOutput {
	return o
}

func (o FlexibleGpuOutput) DeleteOnVmDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.BoolOutput { return v.DeleteOnVmDeletion }).(pulumi.BoolOutput)
}

func (o FlexibleGpuOutput) FlexibleGpuId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.FlexibleGpuId }).(pulumi.StringOutput)
}

func (o FlexibleGpuOutput) Generation() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.Generation }).(pulumi.StringOutput)
}

func (o FlexibleGpuOutput) ModelName() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.ModelName }).(pulumi.StringOutput)
}

func (o FlexibleGpuOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o FlexibleGpuOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.SubregionName }).(pulumi.StringOutput)
}

func (o FlexibleGpuOutput) Timeouts() FlexibleGpuTimeoutsPtrOutput {
	return o.ApplyT(func(v *FlexibleGpu) FlexibleGpuTimeoutsPtrOutput { return v.Timeouts }).(FlexibleGpuTimeoutsPtrOutput)
}

func (o FlexibleGpuOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *FlexibleGpu) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlexibleGpuInput)(nil)).Elem(), &FlexibleGpu{})
	pulumi.RegisterOutputType(FlexibleGpuOutput{})
}
