// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupApiAccessRule(ctx *pulumi.Context, args *LookupApiAccessRuleArgs, opts ...pulumi.InvokeOption) (*LookupApiAccessRuleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupApiAccessRuleResult
	err = ctx.InvokePackage("outscale:index/getApiAccessRule:getApiAccessRule", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApiAccessRule.
type LookupApiAccessRuleArgs struct {
	Filters []GetApiAccessRuleFilter `pulumi:"filters"`
	Id      *string                  `pulumi:"id"`
}

// A collection of values returned by getApiAccessRule.
type LookupApiAccessRuleResult struct {
	ApiAccessRuleId string                   `pulumi:"apiAccessRuleId"`
	CaIds           []string                 `pulumi:"caIds"`
	Cns             []string                 `pulumi:"cns"`
	Description     string                   `pulumi:"description"`
	Filters         []GetApiAccessRuleFilter `pulumi:"filters"`
	Id              string                   `pulumi:"id"`
	IpRanges        []string                 `pulumi:"ipRanges"`
	RequestId       string                   `pulumi:"requestId"`
}

func LookupApiAccessRuleOutput(ctx *pulumi.Context, args LookupApiAccessRuleOutputArgs, opts ...pulumi.InvokeOption) LookupApiAccessRuleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupApiAccessRuleResultOutput, error) {
			args := v.(LookupApiAccessRuleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupApiAccessRuleResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getApiAccessRule:getApiAccessRule", args, LookupApiAccessRuleResultOutput{}, options).(LookupApiAccessRuleResultOutput), nil
		}).(LookupApiAccessRuleResultOutput)
}

// A collection of arguments for invoking getApiAccessRule.
type LookupApiAccessRuleOutputArgs struct {
	Filters GetApiAccessRuleFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput            `pulumi:"id"`
}

func (LookupApiAccessRuleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiAccessRuleArgs)(nil)).Elem()
}

// A collection of values returned by getApiAccessRule.
type LookupApiAccessRuleResultOutput struct{ *pulumi.OutputState }

func (LookupApiAccessRuleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupApiAccessRuleResult)(nil)).Elem()
}

func (o LookupApiAccessRuleResultOutput) ToLookupApiAccessRuleResultOutput() LookupApiAccessRuleResultOutput {
	return o
}

func (o LookupApiAccessRuleResultOutput) ToLookupApiAccessRuleResultOutputWithContext(ctx context.Context) LookupApiAccessRuleResultOutput {
	return o
}

func (o LookupApiAccessRuleResultOutput) ApiAccessRuleId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) string { return v.ApiAccessRuleId }).(pulumi.StringOutput)
}

func (o LookupApiAccessRuleResultOutput) CaIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) []string { return v.CaIds }).(pulumi.StringArrayOutput)
}

func (o LookupApiAccessRuleResultOutput) Cns() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) []string { return v.Cns }).(pulumi.StringArrayOutput)
}

func (o LookupApiAccessRuleResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupApiAccessRuleResultOutput) Filters() GetApiAccessRuleFilterArrayOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) []GetApiAccessRuleFilter { return v.Filters }).(GetApiAccessRuleFilterArrayOutput)
}

func (o LookupApiAccessRuleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupApiAccessRuleResultOutput) IpRanges() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) []string { return v.IpRanges }).(pulumi.StringArrayOutput)
}

func (o LookupApiAccessRuleResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupApiAccessRuleResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupApiAccessRuleResultOutput{})
}
