// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupClientGateway(ctx *pulumi.Context, args *LookupClientGatewayArgs, opts ...pulumi.InvokeOption) (*LookupClientGatewayResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupClientGatewayResult
	err = ctx.InvokePackage("outscale:index/getClientGateway:getClientGateway", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getClientGateway.
type LookupClientGatewayArgs struct {
	ClientGatewayId *string                  `pulumi:"clientGatewayId"`
	Filters         []GetClientGatewayFilter `pulumi:"filters"`
	Id              *string                  `pulumi:"id"`
}

// A collection of values returned by getClientGateway.
type LookupClientGatewayResult struct {
	BgpAsn          float64                  `pulumi:"bgpAsn"`
	ClientGatewayId *string                  `pulumi:"clientGatewayId"`
	ConnectionType  string                   `pulumi:"connectionType"`
	Filters         []GetClientGatewayFilter `pulumi:"filters"`
	Id              string                   `pulumi:"id"`
	PublicIp        string                   `pulumi:"publicIp"`
	RequestId       string                   `pulumi:"requestId"`
	State           string                   `pulumi:"state"`
	Tags            []GetClientGatewayTag    `pulumi:"tags"`
}

func LookupClientGatewayOutput(ctx *pulumi.Context, args LookupClientGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupClientGatewayResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupClientGatewayResultOutput, error) {
			args := v.(LookupClientGatewayArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupClientGatewayResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getClientGateway:getClientGateway", args, LookupClientGatewayResultOutput{}, options).(LookupClientGatewayResultOutput), nil
		}).(LookupClientGatewayResultOutput)
}

// A collection of arguments for invoking getClientGateway.
type LookupClientGatewayOutputArgs struct {
	ClientGatewayId pulumi.StringPtrInput            `pulumi:"clientGatewayId"`
	Filters         GetClientGatewayFilterArrayInput `pulumi:"filters"`
	Id              pulumi.StringPtrInput            `pulumi:"id"`
}

func (LookupClientGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getClientGateway.
type LookupClientGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupClientGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientGatewayResult)(nil)).Elem()
}

func (o LookupClientGatewayResultOutput) ToLookupClientGatewayResultOutput() LookupClientGatewayResultOutput {
	return o
}

func (o LookupClientGatewayResultOutput) ToLookupClientGatewayResultOutputWithContext(ctx context.Context) LookupClientGatewayResultOutput {
	return o
}

func (o LookupClientGatewayResultOutput) BgpAsn() pulumi.Float64Output {
	return o.ApplyT(func(v LookupClientGatewayResult) float64 { return v.BgpAsn }).(pulumi.Float64Output)
}

func (o LookupClientGatewayResultOutput) ClientGatewayId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) *string { return v.ClientGatewayId }).(pulumi.StringPtrOutput)
}

func (o LookupClientGatewayResultOutput) ConnectionType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.ConnectionType }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) Filters() GetClientGatewayFilterArrayOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) []GetClientGatewayFilter { return v.Filters }).(GetClientGatewayFilterArrayOutput)
}

func (o LookupClientGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) Tags() GetClientGatewayTagArrayOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) []GetClientGatewayTag { return v.Tags }).(GetClientGatewayTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupClientGatewayResultOutput{})
}
