// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetClientGateways(ctx *pulumi.Context, args *GetClientGatewaysArgs, opts ...pulumi.InvokeOption) (*GetClientGatewaysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetClientGatewaysResult
	err = ctx.InvokePackage("outscale:index/getClientGateways:getClientGateways", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getClientGateways.
type GetClientGatewaysArgs struct {
	ClientGatewayIds []string                  `pulumi:"clientGatewayIds"`
	Filters          []GetClientGatewaysFilter `pulumi:"filters"`
	Id               *string                   `pulumi:"id"`
}

// A collection of values returned by getClientGateways.
type GetClientGatewaysResult struct {
	ClientGatewayIds []string                         `pulumi:"clientGatewayIds"`
	ClientGateways   []GetClientGatewaysClientGateway `pulumi:"clientGateways"`
	Filters          []GetClientGatewaysFilter        `pulumi:"filters"`
	Id               string                           `pulumi:"id"`
	RequestId        string                           `pulumi:"requestId"`
}

func GetClientGatewaysOutput(ctx *pulumi.Context, args GetClientGatewaysOutputArgs, opts ...pulumi.InvokeOption) GetClientGatewaysResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetClientGatewaysResultOutput, error) {
			args := v.(GetClientGatewaysArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetClientGatewaysResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getClientGateways:getClientGateways", args, GetClientGatewaysResultOutput{}, options).(GetClientGatewaysResultOutput), nil
		}).(GetClientGatewaysResultOutput)
}

// A collection of arguments for invoking getClientGateways.
type GetClientGatewaysOutputArgs struct {
	ClientGatewayIds pulumi.StringArrayInput           `pulumi:"clientGatewayIds"`
	Filters          GetClientGatewaysFilterArrayInput `pulumi:"filters"`
	Id               pulumi.StringPtrInput             `pulumi:"id"`
}

func (GetClientGatewaysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientGatewaysArgs)(nil)).Elem()
}

// A collection of values returned by getClientGateways.
type GetClientGatewaysResultOutput struct{ *pulumi.OutputState }

func (GetClientGatewaysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClientGatewaysResult)(nil)).Elem()
}

func (o GetClientGatewaysResultOutput) ToGetClientGatewaysResultOutput() GetClientGatewaysResultOutput {
	return o
}

func (o GetClientGatewaysResultOutput) ToGetClientGatewaysResultOutputWithContext(ctx context.Context) GetClientGatewaysResultOutput {
	return o
}

func (o GetClientGatewaysResultOutput) ClientGatewayIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetClientGatewaysResult) []string { return v.ClientGatewayIds }).(pulumi.StringArrayOutput)
}

func (o GetClientGatewaysResultOutput) ClientGateways() GetClientGatewaysClientGatewayArrayOutput {
	return o.ApplyT(func(v GetClientGatewaysResult) []GetClientGatewaysClientGateway { return v.ClientGateways }).(GetClientGatewaysClientGatewayArrayOutput)
}

func (o GetClientGatewaysResultOutput) Filters() GetClientGatewaysFilterArrayOutput {
	return o.ApplyT(func(v GetClientGatewaysResult) []GetClientGatewaysFilter { return v.Filters }).(GetClientGatewaysFilterArrayOutput)
}

func (o GetClientGatewaysResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientGatewaysResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetClientGatewaysResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetClientGatewaysResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetClientGatewaysResultOutput{})
}
