// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCas(ctx *pulumi.Context, args *GetCasArgs, opts ...pulumi.InvokeOption) (*GetCasResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetCasResult
	err = ctx.InvokePackage("outscale:index/getCas:getCas", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCas.
type GetCasArgs struct {
	Filters []GetCasFilter `pulumi:"filters"`
	Id      *string        `pulumi:"id"`
}

// A collection of values returned by getCas.
type GetCasResult struct {
	Cas       []GetCasCa     `pulumi:"cas"`
	Filters   []GetCasFilter `pulumi:"filters"`
	Id        string         `pulumi:"id"`
	RequestId string         `pulumi:"requestId"`
}

func GetCasOutput(ctx *pulumi.Context, args GetCasOutputArgs, opts ...pulumi.InvokeOption) GetCasResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetCasResultOutput, error) {
			args := v.(GetCasArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetCasResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getCas:getCas", args, GetCasResultOutput{}, options).(GetCasResultOutput), nil
		}).(GetCasResultOutput)
}

// A collection of arguments for invoking getCas.
type GetCasOutputArgs struct {
	Filters GetCasFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput  `pulumi:"id"`
}

func (GetCasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCasArgs)(nil)).Elem()
}

// A collection of values returned by getCas.
type GetCasResultOutput struct{ *pulumi.OutputState }

func (GetCasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCasResult)(nil)).Elem()
}

func (o GetCasResultOutput) ToGetCasResultOutput() GetCasResultOutput {
	return o
}

func (o GetCasResultOutput) ToGetCasResultOutputWithContext(ctx context.Context) GetCasResultOutput {
	return o
}

func (o GetCasResultOutput) Cas() GetCasCaArrayOutput {
	return o.ApplyT(func(v GetCasResult) []GetCasCa { return v.Cas }).(GetCasCaArrayOutput)
}

func (o GetCasResultOutput) Filters() GetCasFilterArrayOutput {
	return o.ApplyT(func(v GetCasResult) []GetCasFilter { return v.Filters }).(GetCasFilterArrayOutput)
}

func (o GetCasResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCasResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCasResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCasResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCasResultOutput{})
}
