// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDhcpOptions(ctx *pulumi.Context, args *GetDhcpOptionsArgs, opts ...pulumi.InvokeOption) (*GetDhcpOptionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetDhcpOptionsResult
	err = ctx.InvokePackage("outscale:index/getDhcpOptions:getDhcpOptions", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDhcpOptions.
type GetDhcpOptionsArgs struct {
	Filters []GetDhcpOptionsFilter `pulumi:"filters"`
	Id      *string                `pulumi:"id"`
}

// A collection of values returned by getDhcpOptions.
type GetDhcpOptionsResult struct {
	DhcpOptions       []GetDhcpOptionsDhcpOption `pulumi:"dhcpOptions"`
	DhcpOptionsSetIds []string                   `pulumi:"dhcpOptionsSetIds"`
	Filters           []GetDhcpOptionsFilter     `pulumi:"filters"`
	Id                string                     `pulumi:"id"`
	RequestId         string                     `pulumi:"requestId"`
}

func GetDhcpOptionsOutput(ctx *pulumi.Context, args GetDhcpOptionsOutputArgs, opts ...pulumi.InvokeOption) GetDhcpOptionsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDhcpOptionsResultOutput, error) {
			args := v.(GetDhcpOptionsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetDhcpOptionsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getDhcpOptions:getDhcpOptions", args, GetDhcpOptionsResultOutput{}, options).(GetDhcpOptionsResultOutput), nil
		}).(GetDhcpOptionsResultOutput)
}

// A collection of arguments for invoking getDhcpOptions.
type GetDhcpOptionsOutputArgs struct {
	Filters GetDhcpOptionsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput          `pulumi:"id"`
}

func (GetDhcpOptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDhcpOptionsArgs)(nil)).Elem()
}

// A collection of values returned by getDhcpOptions.
type GetDhcpOptionsResultOutput struct{ *pulumi.OutputState }

func (GetDhcpOptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDhcpOptionsResult)(nil)).Elem()
}

func (o GetDhcpOptionsResultOutput) ToGetDhcpOptionsResultOutput() GetDhcpOptionsResultOutput {
	return o
}

func (o GetDhcpOptionsResultOutput) ToGetDhcpOptionsResultOutputWithContext(ctx context.Context) GetDhcpOptionsResultOutput {
	return o
}

func (o GetDhcpOptionsResultOutput) DhcpOptions() GetDhcpOptionsDhcpOptionArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []GetDhcpOptionsDhcpOption { return v.DhcpOptions }).(GetDhcpOptionsDhcpOptionArrayOutput)
}

func (o GetDhcpOptionsResultOutput) DhcpOptionsSetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []string { return v.DhcpOptionsSetIds }).(pulumi.StringArrayOutput)
}

func (o GetDhcpOptionsResultOutput) Filters() GetDhcpOptionsFilterArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []GetDhcpOptionsFilter { return v.Filters }).(GetDhcpOptionsFilterArrayOutput)
}

func (o GetDhcpOptionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDhcpOptionsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDhcpOptionsResultOutput{})
}
