// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetEntitiesLinkedToPolicy(ctx *pulumi.Context, args *GetEntitiesLinkedToPolicyArgs, opts ...pulumi.InvokeOption) (*GetEntitiesLinkedToPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetEntitiesLinkedToPolicyResult
	err = ctx.InvokePackage("outscale:index/getEntitiesLinkedToPolicy:getEntitiesLinkedToPolicy", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEntitiesLinkedToPolicy.
type GetEntitiesLinkedToPolicyArgs struct {
	EntitiesTypes []string `pulumi:"entitiesTypes"`
	Id            *string  `pulumi:"id"`
	PolicyOrn     string   `pulumi:"policyOrn"`
}

// A collection of values returned by getEntitiesLinkedToPolicy.
type GetEntitiesLinkedToPolicyResult struct {
	EntitiesTypes  []string                                `pulumi:"entitiesTypes"`
	Id             string                                  `pulumi:"id"`
	PolicyEntities []GetEntitiesLinkedToPolicyPolicyEntity `pulumi:"policyEntities"`
	PolicyOrn      string                                  `pulumi:"policyOrn"`
}

func GetEntitiesLinkedToPolicyOutput(ctx *pulumi.Context, args GetEntitiesLinkedToPolicyOutputArgs, opts ...pulumi.InvokeOption) GetEntitiesLinkedToPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEntitiesLinkedToPolicyResultOutput, error) {
			args := v.(GetEntitiesLinkedToPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetEntitiesLinkedToPolicyResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getEntitiesLinkedToPolicy:getEntitiesLinkedToPolicy", args, GetEntitiesLinkedToPolicyResultOutput{}, options).(GetEntitiesLinkedToPolicyResultOutput), nil
		}).(GetEntitiesLinkedToPolicyResultOutput)
}

// A collection of arguments for invoking getEntitiesLinkedToPolicy.
type GetEntitiesLinkedToPolicyOutputArgs struct {
	EntitiesTypes pulumi.StringArrayInput `pulumi:"entitiesTypes"`
	Id            pulumi.StringPtrInput   `pulumi:"id"`
	PolicyOrn     pulumi.StringInput      `pulumi:"policyOrn"`
}

func (GetEntitiesLinkedToPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesLinkedToPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getEntitiesLinkedToPolicy.
type GetEntitiesLinkedToPolicyResultOutput struct{ *pulumi.OutputState }

func (GetEntitiesLinkedToPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEntitiesLinkedToPolicyResult)(nil)).Elem()
}

func (o GetEntitiesLinkedToPolicyResultOutput) ToGetEntitiesLinkedToPolicyResultOutput() GetEntitiesLinkedToPolicyResultOutput {
	return o
}

func (o GetEntitiesLinkedToPolicyResultOutput) ToGetEntitiesLinkedToPolicyResultOutputWithContext(ctx context.Context) GetEntitiesLinkedToPolicyResultOutput {
	return o
}

func (o GetEntitiesLinkedToPolicyResultOutput) EntitiesTypes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEntitiesLinkedToPolicyResult) []string { return v.EntitiesTypes }).(pulumi.StringArrayOutput)
}

func (o GetEntitiesLinkedToPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesLinkedToPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEntitiesLinkedToPolicyResultOutput) PolicyEntities() GetEntitiesLinkedToPolicyPolicyEntityArrayOutput {
	return o.ApplyT(func(v GetEntitiesLinkedToPolicyResult) []GetEntitiesLinkedToPolicyPolicyEntity {
		return v.PolicyEntities
	}).(GetEntitiesLinkedToPolicyPolicyEntityArrayOutput)
}

func (o GetEntitiesLinkedToPolicyResultOutput) PolicyOrn() pulumi.StringOutput {
	return o.ApplyT(func(v GetEntitiesLinkedToPolicyResult) string { return v.PolicyOrn }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEntitiesLinkedToPolicyResultOutput{})
}
