// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetImageExportTasks(ctx *pulumi.Context, args *GetImageExportTasksArgs, opts ...pulumi.InvokeOption) (*GetImageExportTasksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetImageExportTasksResult
	err = ctx.InvokePackage("outscale:index/getImageExportTasks:getImageExportTasks", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImageExportTasks.
type GetImageExportTasksArgs struct {
	DryRun   *bool                        `pulumi:"dryRun"`
	Filters  []GetImageExportTasksFilter  `pulumi:"filters"`
	Id       *string                      `pulumi:"id"`
	Timeouts *GetImageExportTasksTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getImageExportTasks.
type GetImageExportTasksResult struct {
	DryRun           bool                                 `pulumi:"dryRun"`
	Filters          []GetImageExportTasksFilter          `pulumi:"filters"`
	Id               string                               `pulumi:"id"`
	ImageExportTasks []GetImageExportTasksImageExportTask `pulumi:"imageExportTasks"`
	RequestId        string                               `pulumi:"requestId"`
	Timeouts         *GetImageExportTasksTimeouts         `pulumi:"timeouts"`
}

func GetImageExportTasksOutput(ctx *pulumi.Context, args GetImageExportTasksOutputArgs, opts ...pulumi.InvokeOption) GetImageExportTasksResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetImageExportTasksResultOutput, error) {
			args := v.(GetImageExportTasksArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetImageExportTasksResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getImageExportTasks:getImageExportTasks", args, GetImageExportTasksResultOutput{}, options).(GetImageExportTasksResultOutput), nil
		}).(GetImageExportTasksResultOutput)
}

// A collection of arguments for invoking getImageExportTasks.
type GetImageExportTasksOutputArgs struct {
	DryRun   pulumi.BoolPtrInput                 `pulumi:"dryRun"`
	Filters  GetImageExportTasksFilterArrayInput `pulumi:"filters"`
	Id       pulumi.StringPtrInput               `pulumi:"id"`
	Timeouts GetImageExportTasksTimeoutsPtrInput `pulumi:"timeouts"`
}

func (GetImageExportTasksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImageExportTasksArgs)(nil)).Elem()
}

// A collection of values returned by getImageExportTasks.
type GetImageExportTasksResultOutput struct{ *pulumi.OutputState }

func (GetImageExportTasksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImageExportTasksResult)(nil)).Elem()
}

func (o GetImageExportTasksResultOutput) ToGetImageExportTasksResultOutput() GetImageExportTasksResultOutput {
	return o
}

func (o GetImageExportTasksResultOutput) ToGetImageExportTasksResultOutputWithContext(ctx context.Context) GetImageExportTasksResultOutput {
	return o
}

func (o GetImageExportTasksResultOutput) DryRun() pulumi.BoolOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) bool { return v.DryRun }).(pulumi.BoolOutput)
}

func (o GetImageExportTasksResultOutput) Filters() GetImageExportTasksFilterArrayOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) []GetImageExportTasksFilter { return v.Filters }).(GetImageExportTasksFilterArrayOutput)
}

func (o GetImageExportTasksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetImageExportTasksResultOutput) ImageExportTasks() GetImageExportTasksImageExportTaskArrayOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) []GetImageExportTasksImageExportTask { return v.ImageExportTasks }).(GetImageExportTasksImageExportTaskArrayOutput)
}

func (o GetImageExportTasksResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetImageExportTasksResultOutput) Timeouts() GetImageExportTasksTimeoutsPtrOutput {
	return o.ApplyT(func(v GetImageExportTasksResult) *GetImageExportTasksTimeouts { return v.Timeouts }).(GetImageExportTasksTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetImageExportTasksResultOutput{})
}
