// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetImages(ctx *pulumi.Context, args *GetImagesArgs, opts ...pulumi.InvokeOption) (*GetImagesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetImagesResult
	err = ctx.InvokePackage("outscale:index/getImages:getImages", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImages.
type GetImagesArgs struct {
	AccountIds  []string          `pulumi:"accountIds"`
	Filters     []GetImagesFilter `pulumi:"filters"`
	Id          *string           `pulumi:"id"`
	ImageIds    []string          `pulumi:"imageIds"`
	Permissions []string          `pulumi:"permissions"`
}

// A collection of values returned by getImages.
type GetImagesResult struct {
	AccountIds  []string          `pulumi:"accountIds"`
	Filters     []GetImagesFilter `pulumi:"filters"`
	Id          string            `pulumi:"id"`
	ImageIds    []string          `pulumi:"imageIds"`
	Images      []GetImagesImage  `pulumi:"images"`
	Permissions []string          `pulumi:"permissions"`
	RequestId   string            `pulumi:"requestId"`
}

func GetImagesOutput(ctx *pulumi.Context, args GetImagesOutputArgs, opts ...pulumi.InvokeOption) GetImagesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetImagesResultOutput, error) {
			args := v.(GetImagesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetImagesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getImages:getImages", args, GetImagesResultOutput{}, options).(GetImagesResultOutput), nil
		}).(GetImagesResultOutput)
}

// A collection of arguments for invoking getImages.
type GetImagesOutputArgs struct {
	AccountIds  pulumi.StringArrayInput   `pulumi:"accountIds"`
	Filters     GetImagesFilterArrayInput `pulumi:"filters"`
	Id          pulumi.StringPtrInput     `pulumi:"id"`
	ImageIds    pulumi.StringArrayInput   `pulumi:"imageIds"`
	Permissions pulumi.StringArrayInput   `pulumi:"permissions"`
}

func (GetImagesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImagesArgs)(nil)).Elem()
}

// A collection of values returned by getImages.
type GetImagesResultOutput struct{ *pulumi.OutputState }

func (GetImagesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetImagesResult)(nil)).Elem()
}

func (o GetImagesResultOutput) ToGetImagesResultOutput() GetImagesResultOutput {
	return o
}

func (o GetImagesResultOutput) ToGetImagesResultOutputWithContext(ctx context.Context) GetImagesResultOutput {
	return o
}

func (o GetImagesResultOutput) AccountIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []string { return v.AccountIds }).(pulumi.StringArrayOutput)
}

func (o GetImagesResultOutput) Filters() GetImagesFilterArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []GetImagesFilter { return v.Filters }).(GetImagesFilterArrayOutput)
}

func (o GetImagesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetImagesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetImagesResultOutput) ImageIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []string { return v.ImageIds }).(pulumi.StringArrayOutput)
}

func (o GetImagesResultOutput) Images() GetImagesImageArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []GetImagesImage { return v.Images }).(GetImagesImageArrayOutput)
}

func (o GetImagesResultOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetImagesResult) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

func (o GetImagesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetImagesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetImagesResultOutput{})
}
