// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetInternetServices(ctx *pulumi.Context, args *GetInternetServicesArgs, opts ...pulumi.InvokeOption) (*GetInternetServicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetInternetServicesResult
	err = ctx.InvokePackage("outscale:index/getInternetServices:getInternetServices", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInternetServices.
type GetInternetServicesArgs struct {
	Filters            []GetInternetServicesFilter `pulumi:"filters"`
	Id                 *string                     `pulumi:"id"`
	InternetServiceIds []string                    `pulumi:"internetServiceIds"`
}

// A collection of values returned by getInternetServices.
type GetInternetServicesResult struct {
	Filters            []GetInternetServicesFilter          `pulumi:"filters"`
	Id                 string                               `pulumi:"id"`
	InternetServiceIds []string                             `pulumi:"internetServiceIds"`
	InternetServices   []GetInternetServicesInternetService `pulumi:"internetServices"`
	RequestId          string                               `pulumi:"requestId"`
}

func GetInternetServicesOutput(ctx *pulumi.Context, args GetInternetServicesOutputArgs, opts ...pulumi.InvokeOption) GetInternetServicesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInternetServicesResultOutput, error) {
			args := v.(GetInternetServicesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetInternetServicesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getInternetServices:getInternetServices", args, GetInternetServicesResultOutput{}, options).(GetInternetServicesResultOutput), nil
		}).(GetInternetServicesResultOutput)
}

// A collection of arguments for invoking getInternetServices.
type GetInternetServicesOutputArgs struct {
	Filters            GetInternetServicesFilterArrayInput `pulumi:"filters"`
	Id                 pulumi.StringPtrInput               `pulumi:"id"`
	InternetServiceIds pulumi.StringArrayInput             `pulumi:"internetServiceIds"`
}

func (GetInternetServicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInternetServicesArgs)(nil)).Elem()
}

// A collection of values returned by getInternetServices.
type GetInternetServicesResultOutput struct{ *pulumi.OutputState }

func (GetInternetServicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInternetServicesResult)(nil)).Elem()
}

func (o GetInternetServicesResultOutput) ToGetInternetServicesResultOutput() GetInternetServicesResultOutput {
	return o
}

func (o GetInternetServicesResultOutput) ToGetInternetServicesResultOutputWithContext(ctx context.Context) GetInternetServicesResultOutput {
	return o
}

func (o GetInternetServicesResultOutput) Filters() GetInternetServicesFilterArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []GetInternetServicesFilter { return v.Filters }).(GetInternetServicesFilterArrayOutput)
}

func (o GetInternetServicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInternetServicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInternetServicesResultOutput) InternetServiceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []string { return v.InternetServiceIds }).(pulumi.StringArrayOutput)
}

func (o GetInternetServicesResultOutput) InternetServices() GetInternetServicesInternetServiceArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []GetInternetServicesInternetService { return v.InternetServices }).(GetInternetServicesInternetServiceArrayOutput)
}

func (o GetInternetServicesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetInternetServicesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInternetServicesResultOutput{})
}
