// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupInternetService(ctx *pulumi.Context, args *LookupInternetServiceArgs, opts ...pulumi.InvokeOption) (*LookupInternetServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupInternetServiceResult
	err = ctx.InvokePackage("outscale:index/getInternetService:getInternetService", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInternetService.
type LookupInternetServiceArgs struct {
	Filters []GetInternetServiceFilter `pulumi:"filters"`
	Id      *string                    `pulumi:"id"`
}

// A collection of values returned by getInternetService.
type LookupInternetServiceResult struct {
	Filters           []GetInternetServiceFilter `pulumi:"filters"`
	Id                string                     `pulumi:"id"`
	InternetServiceId string                     `pulumi:"internetServiceId"`
	NetId             string                     `pulumi:"netId"`
	RequestId         string                     `pulumi:"requestId"`
	State             string                     `pulumi:"state"`
	Tags              []GetInternetServiceTag    `pulumi:"tags"`
}

func LookupInternetServiceOutput(ctx *pulumi.Context, args LookupInternetServiceOutputArgs, opts ...pulumi.InvokeOption) LookupInternetServiceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupInternetServiceResultOutput, error) {
			args := v.(LookupInternetServiceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupInternetServiceResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getInternetService:getInternetService", args, LookupInternetServiceResultOutput{}, options).(LookupInternetServiceResultOutput), nil
		}).(LookupInternetServiceResultOutput)
}

// A collection of arguments for invoking getInternetService.
type LookupInternetServiceOutputArgs struct {
	Filters GetInternetServiceFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput              `pulumi:"id"`
}

func (LookupInternetServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInternetServiceArgs)(nil)).Elem()
}

// A collection of values returned by getInternetService.
type LookupInternetServiceResultOutput struct{ *pulumi.OutputState }

func (LookupInternetServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInternetServiceResult)(nil)).Elem()
}

func (o LookupInternetServiceResultOutput) ToLookupInternetServiceResultOutput() LookupInternetServiceResultOutput {
	return o
}

func (o LookupInternetServiceResultOutput) ToLookupInternetServiceResultOutputWithContext(ctx context.Context) LookupInternetServiceResultOutput {
	return o
}

func (o LookupInternetServiceResultOutput) Filters() GetInternetServiceFilterArrayOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) []GetInternetServiceFilter { return v.Filters }).(GetInternetServiceFilterArrayOutput)
}

func (o LookupInternetServiceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupInternetServiceResultOutput) InternetServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) string { return v.InternetServiceId }).(pulumi.StringOutput)
}

func (o LookupInternetServiceResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupInternetServiceResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupInternetServiceResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupInternetServiceResultOutput) Tags() GetInternetServiceTagArrayOutput {
	return o.ApplyT(func(v LookupInternetServiceResult) []GetInternetServiceTag { return v.Tags }).(GetInternetServiceTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInternetServiceResultOutput{})
}
