// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupImageExportTask(ctx *pulumi.Context, args *LookupImageExportTaskArgs, opts ...pulumi.InvokeOption) (*LookupImageExportTaskResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupImageExportTaskResult
	err = ctx.InvokePackage("outscale:index/getImageExportTask:getImageExportTask", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImageExportTask.
type LookupImageExportTaskArgs struct {
	DryRun   *bool                       `pulumi:"dryRun"`
	Filters  []GetImageExportTaskFilter  `pulumi:"filters"`
	Id       *string                     `pulumi:"id"`
	Timeouts *GetImageExportTaskTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getImageExportTask.
type LookupImageExportTaskResult struct {
	Comment    string                        `pulumi:"comment"`
	DryRun     bool                          `pulumi:"dryRun"`
	Filters    []GetImageExportTaskFilter    `pulumi:"filters"`
	Id         string                        `pulumi:"id"`
	ImageId    string                        `pulumi:"imageId"`
	OsuExports []GetImageExportTaskOsuExport `pulumi:"osuExports"`
	Progress   float64                       `pulumi:"progress"`
	RequestId  string                        `pulumi:"requestId"`
	State      string                        `pulumi:"state"`
	Tags       []GetImageExportTaskTag       `pulumi:"tags"`
	TaskId     string                        `pulumi:"taskId"`
	Timeouts   *GetImageExportTaskTimeouts   `pulumi:"timeouts"`
}

func LookupImageExportTaskOutput(ctx *pulumi.Context, args LookupImageExportTaskOutputArgs, opts ...pulumi.InvokeOption) LookupImageExportTaskResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupImageExportTaskResultOutput, error) {
			args := v.(LookupImageExportTaskArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupImageExportTaskResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getImageExportTask:getImageExportTask", args, LookupImageExportTaskResultOutput{}, options).(LookupImageExportTaskResultOutput), nil
		}).(LookupImageExportTaskResultOutput)
}

// A collection of arguments for invoking getImageExportTask.
type LookupImageExportTaskOutputArgs struct {
	DryRun   pulumi.BoolPtrInput                `pulumi:"dryRun"`
	Filters  GetImageExportTaskFilterArrayInput `pulumi:"filters"`
	Id       pulumi.StringPtrInput              `pulumi:"id"`
	Timeouts GetImageExportTaskTimeoutsPtrInput `pulumi:"timeouts"`
}

func (LookupImageExportTaskOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageExportTaskArgs)(nil)).Elem()
}

// A collection of values returned by getImageExportTask.
type LookupImageExportTaskResultOutput struct{ *pulumi.OutputState }

func (LookupImageExportTaskResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageExportTaskResult)(nil)).Elem()
}

func (o LookupImageExportTaskResultOutput) ToLookupImageExportTaskResultOutput() LookupImageExportTaskResultOutput {
	return o
}

func (o LookupImageExportTaskResultOutput) ToLookupImageExportTaskResultOutputWithContext(ctx context.Context) LookupImageExportTaskResultOutput {
	return o
}

func (o LookupImageExportTaskResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) DryRun() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) bool { return v.DryRun }).(pulumi.BoolOutput)
}

func (o LookupImageExportTaskResultOutput) Filters() GetImageExportTaskFilterArrayOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) []GetImageExportTaskFilter { return v.Filters }).(GetImageExportTaskFilterArrayOutput)
}

func (o LookupImageExportTaskResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.ImageId }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) OsuExports() GetImageExportTaskOsuExportArrayOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) []GetImageExportTaskOsuExport { return v.OsuExports }).(GetImageExportTaskOsuExportArrayOutput)
}

func (o LookupImageExportTaskResultOutput) Progress() pulumi.Float64Output {
	return o.ApplyT(func(v LookupImageExportTaskResult) float64 { return v.Progress }).(pulumi.Float64Output)
}

func (o LookupImageExportTaskResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) Tags() GetImageExportTaskTagArrayOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) []GetImageExportTaskTag { return v.Tags }).(GetImageExportTaskTagArrayOutput)
}

func (o LookupImageExportTaskResultOutput) TaskId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) string { return v.TaskId }).(pulumi.StringOutput)
}

func (o LookupImageExportTaskResultOutput) Timeouts() GetImageExportTaskTimeoutsPtrOutput {
	return o.ApplyT(func(v LookupImageExportTaskResult) *GetImageExportTaskTimeouts { return v.Timeouts }).(GetImageExportTaskTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupImageExportTaskResultOutput{})
}
