// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKeypair(ctx *pulumi.Context, args *LookupKeypairArgs, opts ...pulumi.InvokeOption) (*LookupKeypairResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupKeypairResult
	err = ctx.InvokePackage("outscale:index/getKeypair:getKeypair", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKeypair.
type LookupKeypairArgs struct {
	Filters     []GetKeypairFilter `pulumi:"filters"`
	Id          *string            `pulumi:"id"`
	KeypairName *string            `pulumi:"keypairName"`
}

// A collection of values returned by getKeypair.
type LookupKeypairResult struct {
	Filters            []GetKeypairFilter `pulumi:"filters"`
	Id                 string             `pulumi:"id"`
	KeypairFingerprint string             `pulumi:"keypairFingerprint"`
	KeypairId          string             `pulumi:"keypairId"`
	KeypairName        string             `pulumi:"keypairName"`
	KeypairType        string             `pulumi:"keypairType"`
	RequestId          string             `pulumi:"requestId"`
	Tags               []GetKeypairTag    `pulumi:"tags"`
}

func LookupKeypairOutput(ctx *pulumi.Context, args LookupKeypairOutputArgs, opts ...pulumi.InvokeOption) LookupKeypairResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupKeypairResultOutput, error) {
			args := v.(LookupKeypairArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupKeypairResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getKeypair:getKeypair", args, LookupKeypairResultOutput{}, options).(LookupKeypairResultOutput), nil
		}).(LookupKeypairResultOutput)
}

// A collection of arguments for invoking getKeypair.
type LookupKeypairOutputArgs struct {
	Filters     GetKeypairFilterArrayInput `pulumi:"filters"`
	Id          pulumi.StringPtrInput      `pulumi:"id"`
	KeypairName pulumi.StringPtrInput      `pulumi:"keypairName"`
}

func (LookupKeypairOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeypairArgs)(nil)).Elem()
}

// A collection of values returned by getKeypair.
type LookupKeypairResultOutput struct{ *pulumi.OutputState }

func (LookupKeypairResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKeypairResult)(nil)).Elem()
}

func (o LookupKeypairResultOutput) ToLookupKeypairResultOutput() LookupKeypairResultOutput {
	return o
}

func (o LookupKeypairResultOutput) ToLookupKeypairResultOutputWithContext(ctx context.Context) LookupKeypairResultOutput {
	return o
}

func (o LookupKeypairResultOutput) Filters() GetKeypairFilterArrayOutput {
	return o.ApplyT(func(v LookupKeypairResult) []GetKeypairFilter { return v.Filters }).(GetKeypairFilterArrayOutput)
}

func (o LookupKeypairResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) KeypairFingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.KeypairFingerprint }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) KeypairId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.KeypairId }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) KeypairName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.KeypairName }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) KeypairType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.KeypairType }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKeypairResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupKeypairResultOutput) Tags() GetKeypairTagArrayOutput {
	return o.ApplyT(func(v LookupKeypairResult) []GetKeypairTag { return v.Tags }).(GetKeypairTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKeypairResultOutput{})
}
