// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetKeypairs(ctx *pulumi.Context, args *GetKeypairsArgs, opts ...pulumi.InvokeOption) (*GetKeypairsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetKeypairsResult
	err = ctx.InvokePackage("outscale:index/getKeypairs:getKeypairs", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKeypairs.
type GetKeypairsArgs struct {
	Filters      []GetKeypairsFilter `pulumi:"filters"`
	Id           *string             `pulumi:"id"`
	KeypairNames []string            `pulumi:"keypairNames"`
}

// A collection of values returned by getKeypairs.
type GetKeypairsResult struct {
	Filters      []GetKeypairsFilter  `pulumi:"filters"`
	Id           string               `pulumi:"id"`
	KeypairNames []string             `pulumi:"keypairNames"`
	Keypairs     []GetKeypairsKeypair `pulumi:"keypairs"`
	RequestId    string               `pulumi:"requestId"`
}

func GetKeypairsOutput(ctx *pulumi.Context, args GetKeypairsOutputArgs, opts ...pulumi.InvokeOption) GetKeypairsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetKeypairsResultOutput, error) {
			args := v.(GetKeypairsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetKeypairsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getKeypairs:getKeypairs", args, GetKeypairsResultOutput{}, options).(GetKeypairsResultOutput), nil
		}).(GetKeypairsResultOutput)
}

// A collection of arguments for invoking getKeypairs.
type GetKeypairsOutputArgs struct {
	Filters      GetKeypairsFilterArrayInput `pulumi:"filters"`
	Id           pulumi.StringPtrInput       `pulumi:"id"`
	KeypairNames pulumi.StringArrayInput     `pulumi:"keypairNames"`
}

func (GetKeypairsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeypairsArgs)(nil)).Elem()
}

// A collection of values returned by getKeypairs.
type GetKeypairsResultOutput struct{ *pulumi.OutputState }

func (GetKeypairsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetKeypairsResult)(nil)).Elem()
}

func (o GetKeypairsResultOutput) ToGetKeypairsResultOutput() GetKeypairsResultOutput {
	return o
}

func (o GetKeypairsResultOutput) ToGetKeypairsResultOutputWithContext(ctx context.Context) GetKeypairsResultOutput {
	return o
}

func (o GetKeypairsResultOutput) Filters() GetKeypairsFilterArrayOutput {
	return o.ApplyT(func(v GetKeypairsResult) []GetKeypairsFilter { return v.Filters }).(GetKeypairsFilterArrayOutput)
}

func (o GetKeypairsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetKeypairsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetKeypairsResultOutput) KeypairNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetKeypairsResult) []string { return v.KeypairNames }).(pulumi.StringArrayOutput)
}

func (o GetKeypairsResultOutput) Keypairs() GetKeypairsKeypairArrayOutput {
	return o.ApplyT(func(v GetKeypairsResult) []GetKeypairsKeypair { return v.Keypairs }).(GetKeypairsKeypairArrayOutput)
}

func (o GetKeypairsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetKeypairsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetKeypairsResultOutput{})
}
