// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetLoadBalancerListenerRules(ctx *pulumi.Context, args *GetLoadBalancerListenerRulesArgs, opts ...pulumi.InvokeOption) (*GetLoadBalancerListenerRulesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetLoadBalancerListenerRulesResult
	err = ctx.InvokePackage("outscale:index/getLoadBalancerListenerRules:getLoadBalancerListenerRules", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLoadBalancerListenerRules.
type GetLoadBalancerListenerRulesArgs struct {
	Filters []GetLoadBalancerListenerRulesFilter `pulumi:"filters"`
	Id      *string                              `pulumi:"id"`
}

// A collection of values returned by getLoadBalancerListenerRules.
type GetLoadBalancerListenerRulesResult struct {
	Filters       []GetLoadBalancerListenerRulesFilter       `pulumi:"filters"`
	Id            string                                     `pulumi:"id"`
	ListenerRules []GetLoadBalancerListenerRulesListenerRule `pulumi:"listenerRules"`
	RequestId     string                                     `pulumi:"requestId"`
}

func GetLoadBalancerListenerRulesOutput(ctx *pulumi.Context, args GetLoadBalancerListenerRulesOutputArgs, opts ...pulumi.InvokeOption) GetLoadBalancerListenerRulesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetLoadBalancerListenerRulesResultOutput, error) {
			args := v.(GetLoadBalancerListenerRulesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetLoadBalancerListenerRulesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getLoadBalancerListenerRules:getLoadBalancerListenerRules", args, GetLoadBalancerListenerRulesResultOutput{}, options).(GetLoadBalancerListenerRulesResultOutput), nil
		}).(GetLoadBalancerListenerRulesResultOutput)
}

// A collection of arguments for invoking getLoadBalancerListenerRules.
type GetLoadBalancerListenerRulesOutputArgs struct {
	Filters GetLoadBalancerListenerRulesFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput                        `pulumi:"id"`
}

func (GetLoadBalancerListenerRulesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoadBalancerListenerRulesArgs)(nil)).Elem()
}

// A collection of values returned by getLoadBalancerListenerRules.
type GetLoadBalancerListenerRulesResultOutput struct{ *pulumi.OutputState }

func (GetLoadBalancerListenerRulesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoadBalancerListenerRulesResult)(nil)).Elem()
}

func (o GetLoadBalancerListenerRulesResultOutput) ToGetLoadBalancerListenerRulesResultOutput() GetLoadBalancerListenerRulesResultOutput {
	return o
}

func (o GetLoadBalancerListenerRulesResultOutput) ToGetLoadBalancerListenerRulesResultOutputWithContext(ctx context.Context) GetLoadBalancerListenerRulesResultOutput {
	return o
}

func (o GetLoadBalancerListenerRulesResultOutput) Filters() GetLoadBalancerListenerRulesFilterArrayOutput {
	return o.ApplyT(func(v GetLoadBalancerListenerRulesResult) []GetLoadBalancerListenerRulesFilter { return v.Filters }).(GetLoadBalancerListenerRulesFilterArrayOutput)
}

func (o GetLoadBalancerListenerRulesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetLoadBalancerListenerRulesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetLoadBalancerListenerRulesResultOutput) ListenerRules() GetLoadBalancerListenerRulesListenerRuleArrayOutput {
	return o.ApplyT(func(v GetLoadBalancerListenerRulesResult) []GetLoadBalancerListenerRulesListenerRule {
		return v.ListenerRules
	}).(GetLoadBalancerListenerRulesListenerRuleArrayOutput)
}

func (o GetLoadBalancerListenerRulesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetLoadBalancerListenerRulesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLoadBalancerListenerRulesResultOutput{})
}
