// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNic(ctx *pulumi.Context, args *LookupNicArgs, opts ...pulumi.InvokeOption) (*LookupNicResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNicResult
	err = ctx.InvokePackage("outscale:index/getNic:getNic", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNic.
type LookupNicArgs struct {
	Filters []GetNicFilter `pulumi:"filters"`
	Id      *string        `pulumi:"id"`
}

// A collection of values returned by getNic.
type LookupNicResult struct {
	AccountId           string                `pulumi:"accountId"`
	Description         string                `pulumi:"description"`
	Filters             []GetNicFilter        `pulumi:"filters"`
	Id                  string                `pulumi:"id"`
	IsSourceDestChecked bool                  `pulumi:"isSourceDestChecked"`
	LinkNics            []GetNicLinkNic       `pulumi:"linkNics"`
	LinkPublicIps       []GetNicLinkPublicIp  `pulumi:"linkPublicIps"`
	MacAddress          string                `pulumi:"macAddress"`
	NetId               string                `pulumi:"netId"`
	NicId               string                `pulumi:"nicId"`
	PrivateDnsName      string                `pulumi:"privateDnsName"`
	PrivateIp           string                `pulumi:"privateIp"`
	PrivateIps          []GetNicPrivateIpType `pulumi:"privateIps"`
	RequestId           string                `pulumi:"requestId"`
	RequesterManaged    bool                  `pulumi:"requesterManaged"`
	SecurityGroupIds    []string              `pulumi:"securityGroupIds"`
	SecurityGroups      []GetNicSecurityGroup `pulumi:"securityGroups"`
	State               string                `pulumi:"state"`
	SubnetId            string                `pulumi:"subnetId"`
	SubregionName       string                `pulumi:"subregionName"`
	Tags                []GetNicTag           `pulumi:"tags"`
}

func LookupNicOutput(ctx *pulumi.Context, args LookupNicOutputArgs, opts ...pulumi.InvokeOption) LookupNicResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNicResultOutput, error) {
			args := v.(LookupNicArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNicResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNic:getNic", args, LookupNicResultOutput{}, options).(LookupNicResultOutput), nil
		}).(LookupNicResultOutput)
}

// A collection of arguments for invoking getNic.
type LookupNicOutputArgs struct {
	Filters GetNicFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput  `pulumi:"id"`
}

func (LookupNicOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNicArgs)(nil)).Elem()
}

// A collection of values returned by getNic.
type LookupNicResultOutput struct{ *pulumi.OutputState }

func (LookupNicResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNicResult)(nil)).Elem()
}

func (o LookupNicResultOutput) ToLookupNicResultOutput() LookupNicResultOutput {
	return o
}

func (o LookupNicResultOutput) ToLookupNicResultOutputWithContext(ctx context.Context) LookupNicResultOutput {
	return o
}

func (o LookupNicResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.AccountId }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) Filters() GetNicFilterArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicFilter { return v.Filters }).(GetNicFilterArrayOutput)
}

func (o LookupNicResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) IsSourceDestChecked() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNicResult) bool { return v.IsSourceDestChecked }).(pulumi.BoolOutput)
}

func (o LookupNicResultOutput) LinkNics() GetNicLinkNicArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicLinkNic { return v.LinkNics }).(GetNicLinkNicArrayOutput)
}

func (o LookupNicResultOutput) LinkPublicIps() GetNicLinkPublicIpArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicLinkPublicIp { return v.LinkPublicIps }).(GetNicLinkPublicIpArrayOutput)
}

func (o LookupNicResultOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.MacAddress }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.NicId }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) PrivateDnsName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.PrivateDnsName }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) PrivateIps() GetNicPrivateIpTypeArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicPrivateIpType { return v.PrivateIps }).(GetNicPrivateIpTypeArrayOutput)
}

func (o LookupNicResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) RequesterManaged() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNicResult) bool { return v.RequesterManaged }).(pulumi.BoolOutput)
}

func (o LookupNicResultOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []string { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o LookupNicResultOutput) SecurityGroups() GetNicSecurityGroupArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicSecurityGroup { return v.SecurityGroups }).(GetNicSecurityGroupArrayOutput)
}

func (o LookupNicResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.SubnetId }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNicResult) string { return v.SubregionName }).(pulumi.StringOutput)
}

func (o LookupNicResultOutput) Tags() GetNicTagArrayOutput {
	return o.ApplyT(func(v LookupNicResult) []GetNicTag { return v.Tags }).(GetNicTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNicResultOutput{})
}
