// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetAccessPoints(ctx *pulumi.Context, args *GetNetAccessPointsArgs, opts ...pulumi.InvokeOption) (*GetNetAccessPointsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetAccessPointsResult
	err = ctx.InvokePackage("outscale:index/getNetAccessPoints:getNetAccessPoints", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetAccessPoints.
type GetNetAccessPointsArgs struct {
	Filters []GetNetAccessPointsFilter `pulumi:"filters"`
	Id      *string                    `pulumi:"id"`
}

// A collection of values returned by getNetAccessPoints.
type GetNetAccessPointsResult struct {
	Filters         []GetNetAccessPointsFilter         `pulumi:"filters"`
	Id              string                             `pulumi:"id"`
	NetAccessPoints []GetNetAccessPointsNetAccessPoint `pulumi:"netAccessPoints"`
	RequestId       string                             `pulumi:"requestId"`
}

func GetNetAccessPointsOutput(ctx *pulumi.Context, args GetNetAccessPointsOutputArgs, opts ...pulumi.InvokeOption) GetNetAccessPointsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetAccessPointsResultOutput, error) {
			args := v.(GetNetAccessPointsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetAccessPointsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNetAccessPoints:getNetAccessPoints", args, GetNetAccessPointsResultOutput{}, options).(GetNetAccessPointsResultOutput), nil
		}).(GetNetAccessPointsResultOutput)
}

// A collection of arguments for invoking getNetAccessPoints.
type GetNetAccessPointsOutputArgs struct {
	Filters GetNetAccessPointsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput              `pulumi:"id"`
}

func (GetNetAccessPointsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetAccessPointsArgs)(nil)).Elem()
}

// A collection of values returned by getNetAccessPoints.
type GetNetAccessPointsResultOutput struct{ *pulumi.OutputState }

func (GetNetAccessPointsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetAccessPointsResult)(nil)).Elem()
}

func (o GetNetAccessPointsResultOutput) ToGetNetAccessPointsResultOutput() GetNetAccessPointsResultOutput {
	return o
}

func (o GetNetAccessPointsResultOutput) ToGetNetAccessPointsResultOutputWithContext(ctx context.Context) GetNetAccessPointsResultOutput {
	return o
}

func (o GetNetAccessPointsResultOutput) Filters() GetNetAccessPointsFilterArrayOutput {
	return o.ApplyT(func(v GetNetAccessPointsResult) []GetNetAccessPointsFilter { return v.Filters }).(GetNetAccessPointsFilterArrayOutput)
}

func (o GetNetAccessPointsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetAccessPointsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetAccessPointsResultOutput) NetAccessPoints() GetNetAccessPointsNetAccessPointArrayOutput {
	return o.ApplyT(func(v GetNetAccessPointsResult) []GetNetAccessPointsNetAccessPoint { return v.NetAccessPoints }).(GetNetAccessPointsNetAccessPointArrayOutput)
}

func (o GetNetAccessPointsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetAccessPointsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetAccessPointsResultOutput{})
}
