// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNics(ctx *pulumi.Context, args *GetNicsArgs, opts ...pulumi.InvokeOption) (*GetNicsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNicsResult
	err = ctx.InvokePackage("outscale:index/getNics:getNics", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNics.
type GetNicsArgs struct {
	Filters []GetNicsFilter `pulumi:"filters"`
	Id      *string         `pulumi:"id"`
}

// A collection of values returned by getNics.
type GetNicsResult struct {
	Filters   []GetNicsFilter `pulumi:"filters"`
	Id        string          `pulumi:"id"`
	Nics      []GetNicsNic    `pulumi:"nics"`
	RequestId string          `pulumi:"requestId"`
}

func GetNicsOutput(ctx *pulumi.Context, args GetNicsOutputArgs, opts ...pulumi.InvokeOption) GetNicsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNicsResultOutput, error) {
			args := v.(GetNicsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNicsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNics:getNics", args, GetNicsResultOutput{}, options).(GetNicsResultOutput), nil
		}).(GetNicsResultOutput)
}

// A collection of arguments for invoking getNics.
type GetNicsOutputArgs struct {
	Filters GetNicsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput   `pulumi:"id"`
}

func (GetNicsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNicsArgs)(nil)).Elem()
}

// A collection of values returned by getNics.
type GetNicsResultOutput struct{ *pulumi.OutputState }

func (GetNicsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNicsResult)(nil)).Elem()
}

func (o GetNicsResultOutput) ToGetNicsResultOutput() GetNicsResultOutput {
	return o
}

func (o GetNicsResultOutput) ToGetNicsResultOutputWithContext(ctx context.Context) GetNicsResultOutput {
	return o
}

func (o GetNicsResultOutput) Filters() GetNicsFilterArrayOutput {
	return o.ApplyT(func(v GetNicsResult) []GetNicsFilter { return v.Filters }).(GetNicsFilterArrayOutput)
}

func (o GetNicsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNicsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNicsResultOutput) Nics() GetNicsNicArrayOutput {
	return o.ApplyT(func(v GetNicsResult) []GetNicsNic { return v.Nics }).(GetNicsNicArrayOutput)
}

func (o GetNicsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNicsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNicsResultOutput{})
}
