// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNets(ctx *pulumi.Context, args *GetNetsArgs, opts ...pulumi.InvokeOption) (*GetNetsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetsResult
	err = ctx.InvokePackage("outscale:index/getNets:getNets", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNets.
type GetNetsArgs struct {
	Filters []GetNetsFilter `pulumi:"filters"`
	Id      *string         `pulumi:"id"`
	NetIds  []string        `pulumi:"netIds"`
}

// A collection of values returned by getNets.
type GetNetsResult struct {
	Filters   []GetNetsFilter `pulumi:"filters"`
	Id        string          `pulumi:"id"`
	NetIds    []string        `pulumi:"netIds"`
	Nets      []GetNetsNet    `pulumi:"nets"`
	RequestId string          `pulumi:"requestId"`
}

func GetNetsOutput(ctx *pulumi.Context, args GetNetsOutputArgs, opts ...pulumi.InvokeOption) GetNetsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetsResultOutput, error) {
			args := v.(GetNetsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNets:getNets", args, GetNetsResultOutput{}, options).(GetNetsResultOutput), nil
		}).(GetNetsResultOutput)
}

// A collection of arguments for invoking getNets.
type GetNetsOutputArgs struct {
	Filters GetNetsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput   `pulumi:"id"`
	NetIds  pulumi.StringArrayInput `pulumi:"netIds"`
}

func (GetNetsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetsArgs)(nil)).Elem()
}

// A collection of values returned by getNets.
type GetNetsResultOutput struct{ *pulumi.OutputState }

func (GetNetsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetsResult)(nil)).Elem()
}

func (o GetNetsResultOutput) ToGetNetsResultOutput() GetNetsResultOutput {
	return o
}

func (o GetNetsResultOutput) ToGetNetsResultOutputWithContext(ctx context.Context) GetNetsResultOutput {
	return o
}

func (o GetNetsResultOutput) Filters() GetNetsFilterArrayOutput {
	return o.ApplyT(func(v GetNetsResult) []GetNetsFilter { return v.Filters }).(GetNetsFilterArrayOutput)
}

func (o GetNetsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetsResultOutput) NetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNetsResult) []string { return v.NetIds }).(pulumi.StringArrayOutput)
}

func (o GetNetsResultOutput) Nets() GetNetsNetArrayOutput {
	return o.ApplyT(func(v GetNetsResult) []GetNetsNet { return v.Nets }).(GetNetsNetArrayOutput)
}

func (o GetNetsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetsResultOutput{})
}
