// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNatServices(ctx *pulumi.Context, args *GetNatServicesArgs, opts ...pulumi.InvokeOption) (*GetNatServicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNatServicesResult
	err = ctx.InvokePackage("outscale:index/getNatServices:getNatServices", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNatServices.
type GetNatServicesArgs struct {
	Filters       []GetNatServicesFilter `pulumi:"filters"`
	Id            *string                `pulumi:"id"`
	NatServiceIds []string               `pulumi:"natServiceIds"`
}

// A collection of values returned by getNatServices.
type GetNatServicesResult struct {
	Filters       []GetNatServicesFilter     `pulumi:"filters"`
	Id            string                     `pulumi:"id"`
	NatServiceIds []string                   `pulumi:"natServiceIds"`
	NatServices   []GetNatServicesNatService `pulumi:"natServices"`
	RequestId     string                     `pulumi:"requestId"`
}

func GetNatServicesOutput(ctx *pulumi.Context, args GetNatServicesOutputArgs, opts ...pulumi.InvokeOption) GetNatServicesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNatServicesResultOutput, error) {
			args := v.(GetNatServicesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNatServicesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNatServices:getNatServices", args, GetNatServicesResultOutput{}, options).(GetNatServicesResultOutput), nil
		}).(GetNatServicesResultOutput)
}

// A collection of arguments for invoking getNatServices.
type GetNatServicesOutputArgs struct {
	Filters       GetNatServicesFilterArrayInput `pulumi:"filters"`
	Id            pulumi.StringPtrInput          `pulumi:"id"`
	NatServiceIds pulumi.StringArrayInput        `pulumi:"natServiceIds"`
}

func (GetNatServicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNatServicesArgs)(nil)).Elem()
}

// A collection of values returned by getNatServices.
type GetNatServicesResultOutput struct{ *pulumi.OutputState }

func (GetNatServicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNatServicesResult)(nil)).Elem()
}

func (o GetNatServicesResultOutput) ToGetNatServicesResultOutput() GetNatServicesResultOutput {
	return o
}

func (o GetNatServicesResultOutput) ToGetNatServicesResultOutputWithContext(ctx context.Context) GetNatServicesResultOutput {
	return o
}

func (o GetNatServicesResultOutput) Filters() GetNatServicesFilterArrayOutput {
	return o.ApplyT(func(v GetNatServicesResult) []GetNatServicesFilter { return v.Filters }).(GetNatServicesFilterArrayOutput)
}

func (o GetNatServicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNatServicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNatServicesResultOutput) NatServiceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetNatServicesResult) []string { return v.NatServiceIds }).(pulumi.StringArrayOutput)
}

func (o GetNatServicesResultOutput) NatServices() GetNatServicesNatServiceArrayOutput {
	return o.ApplyT(func(v GetNatServicesResult) []GetNatServicesNatService { return v.NatServices }).(GetNatServicesNatServiceArrayOutput)
}

func (o GetNatServicesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNatServicesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNatServicesResultOutput{})
}
