// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetAttributes(ctx *pulumi.Context, args *LookupNetAttributesArgs, opts ...pulumi.InvokeOption) (*LookupNetAttributesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetAttributesResult
	err = ctx.InvokePackage("outscale:index/getNetAttributes:getNetAttributes", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetAttributes.
type LookupNetAttributesArgs struct {
	Id    *string `pulumi:"id"`
	NetId string  `pulumi:"netId"`
}

// A collection of values returned by getNetAttributes.
type LookupNetAttributesResult struct {
	DhcpOptionsSetId string                `pulumi:"dhcpOptionsSetId"`
	Id               string                `pulumi:"id"`
	IpRange          string                `pulumi:"ipRange"`
	NetId            string                `pulumi:"netId"`
	RequestId        string                `pulumi:"requestId"`
	State            string                `pulumi:"state"`
	Tags             []GetNetAttributesTag `pulumi:"tags"`
	Tenancy          string                `pulumi:"tenancy"`
}

func LookupNetAttributesOutput(ctx *pulumi.Context, args LookupNetAttributesOutputArgs, opts ...pulumi.InvokeOption) LookupNetAttributesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetAttributesResultOutput, error) {
			args := v.(LookupNetAttributesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetAttributesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNetAttributes:getNetAttributes", args, LookupNetAttributesResultOutput{}, options).(LookupNetAttributesResultOutput), nil
		}).(LookupNetAttributesResultOutput)
}

// A collection of arguments for invoking getNetAttributes.
type LookupNetAttributesOutputArgs struct {
	Id    pulumi.StringPtrInput `pulumi:"id"`
	NetId pulumi.StringInput    `pulumi:"netId"`
}

func (LookupNetAttributesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAttributesArgs)(nil)).Elem()
}

// A collection of values returned by getNetAttributes.
type LookupNetAttributesResultOutput struct{ *pulumi.OutputState }

func (LookupNetAttributesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAttributesResult)(nil)).Elem()
}

func (o LookupNetAttributesResultOutput) ToLookupNetAttributesResultOutput() LookupNetAttributesResultOutput {
	return o
}

func (o LookupNetAttributesResultOutput) ToLookupNetAttributesResultOutputWithContext(ctx context.Context) LookupNetAttributesResultOutput {
	return o
}

func (o LookupNetAttributesResultOutput) DhcpOptionsSetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.DhcpOptionsSetId }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) IpRange() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.IpRange }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) Tags() GetNetAttributesTagArrayOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) []GetNetAttributesTag { return v.Tags }).(GetNetAttributesTagArrayOutput)
}

func (o LookupNetAttributesResultOutput) Tenancy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.Tenancy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetAttributesResultOutput{})
}
