// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetAccessPoint(ctx *pulumi.Context, args *LookupNetAccessPointArgs, opts ...pulumi.InvokeOption) (*LookupNetAccessPointResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetAccessPointResult
	err = ctx.InvokePackage("outscale:index/getNetAccessPoint:getNetAccessPoint", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetAccessPoint.
type LookupNetAccessPointArgs struct {
	Filters []GetNetAccessPointFilter `pulumi:"filters"`
	Id      *string                   `pulumi:"id"`
}

// A collection of values returned by getNetAccessPoint.
type LookupNetAccessPointResult struct {
	Filters          []GetNetAccessPointFilter `pulumi:"filters"`
	Id               string                    `pulumi:"id"`
	NetAccessPointId string                    `pulumi:"netAccessPointId"`
	NetId            string                    `pulumi:"netId"`
	RequestId        string                    `pulumi:"requestId"`
	RouteTableIds    []string                  `pulumi:"routeTableIds"`
	ServiceName      string                    `pulumi:"serviceName"`
	State            string                    `pulumi:"state"`
	Tags             []GetNetAccessPointTag    `pulumi:"tags"`
}

func LookupNetAccessPointOutput(ctx *pulumi.Context, args LookupNetAccessPointOutputArgs, opts ...pulumi.InvokeOption) LookupNetAccessPointResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetAccessPointResultOutput, error) {
			args := v.(LookupNetAccessPointArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetAccessPointResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNetAccessPoint:getNetAccessPoint", args, LookupNetAccessPointResultOutput{}, options).(LookupNetAccessPointResultOutput), nil
		}).(LookupNetAccessPointResultOutput)
}

// A collection of arguments for invoking getNetAccessPoint.
type LookupNetAccessPointOutputArgs struct {
	Filters GetNetAccessPointFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput             `pulumi:"id"`
}

func (LookupNetAccessPointOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAccessPointArgs)(nil)).Elem()
}

// A collection of values returned by getNetAccessPoint.
type LookupNetAccessPointResultOutput struct{ *pulumi.OutputState }

func (LookupNetAccessPointResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAccessPointResult)(nil)).Elem()
}

func (o LookupNetAccessPointResultOutput) ToLookupNetAccessPointResultOutput() LookupNetAccessPointResultOutput {
	return o
}

func (o LookupNetAccessPointResultOutput) ToLookupNetAccessPointResultOutputWithContext(ctx context.Context) LookupNetAccessPointResultOutput {
	return o
}

func (o LookupNetAccessPointResultOutput) Filters() GetNetAccessPointFilterArrayOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) []GetNetAccessPointFilter { return v.Filters }).(GetNetAccessPointFilterArrayOutput)
}

func (o LookupNetAccessPointResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) NetAccessPointId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.NetAccessPointId }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) RouteTableIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) []string { return v.RouteTableIds }).(pulumi.StringArrayOutput)
}

func (o LookupNetAccessPointResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNetAccessPointResultOutput) Tags() GetNetAccessPointTagArrayOutput {
	return o.ApplyT(func(v LookupNetAccessPointResult) []GetNetAccessPointTag { return v.Tags }).(GetNetAccessPointTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetAccessPointResultOutput{})
}
