// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetPeerings(ctx *pulumi.Context, args *GetNetPeeringsArgs, opts ...pulumi.InvokeOption) (*GetNetPeeringsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetPeeringsResult
	err = ctx.InvokePackage("outscale:index/getNetPeerings:getNetPeerings", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetPeerings.
type GetNetPeeringsArgs struct {
	Filters []GetNetPeeringsFilter `pulumi:"filters"`
	Id      *string                `pulumi:"id"`
}

// A collection of values returned by getNetPeerings.
type GetNetPeeringsResult struct {
	Filters     []GetNetPeeringsFilter     `pulumi:"filters"`
	Id          string                     `pulumi:"id"`
	NetPeerings []GetNetPeeringsNetPeering `pulumi:"netPeerings"`
	RequestId   string                     `pulumi:"requestId"`
}

func GetNetPeeringsOutput(ctx *pulumi.Context, args GetNetPeeringsOutputArgs, opts ...pulumi.InvokeOption) GetNetPeeringsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetPeeringsResultOutput, error) {
			args := v.(GetNetPeeringsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetPeeringsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getNetPeerings:getNetPeerings", args, GetNetPeeringsResultOutput{}, options).(GetNetPeeringsResultOutput), nil
		}).(GetNetPeeringsResultOutput)
}

// A collection of arguments for invoking getNetPeerings.
type GetNetPeeringsOutputArgs struct {
	Filters GetNetPeeringsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput          `pulumi:"id"`
}

func (GetNetPeeringsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetPeeringsArgs)(nil)).Elem()
}

// A collection of values returned by getNetPeerings.
type GetNetPeeringsResultOutput struct{ *pulumi.OutputState }

func (GetNetPeeringsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetPeeringsResult)(nil)).Elem()
}

func (o GetNetPeeringsResultOutput) ToGetNetPeeringsResultOutput() GetNetPeeringsResultOutput {
	return o
}

func (o GetNetPeeringsResultOutput) ToGetNetPeeringsResultOutputWithContext(ctx context.Context) GetNetPeeringsResultOutput {
	return o
}

func (o GetNetPeeringsResultOutput) Filters() GetNetPeeringsFilterArrayOutput {
	return o.ApplyT(func(v GetNetPeeringsResult) []GetNetPeeringsFilter { return v.Filters }).(GetNetPeeringsFilterArrayOutput)
}

func (o GetNetPeeringsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetPeeringsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetPeeringsResultOutput) NetPeerings() GetNetPeeringsNetPeeringArrayOutput {
	return o.ApplyT(func(v GetNetPeeringsResult) []GetNetPeeringsNetPeering { return v.NetPeerings }).(GetNetPeeringsNetPeeringArrayOutput)
}

func (o GetNetPeeringsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetPeeringsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetPeeringsResultOutput{})
}
