// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPoliciesLinkedToUser(ctx *pulumi.Context, args *GetPoliciesLinkedToUserArgs, opts ...pulumi.InvokeOption) (*GetPoliciesLinkedToUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetPoliciesLinkedToUserResult
	err = ctx.InvokePackage("outscale:index/getPoliciesLinkedToUser:getPoliciesLinkedToUser", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPoliciesLinkedToUser.
type GetPoliciesLinkedToUserArgs struct {
	Id       *string `pulumi:"id"`
	UserName string  `pulumi:"userName"`
}

// A collection of values returned by getPoliciesLinkedToUser.
type GetPoliciesLinkedToUserResult struct {
	Id       string                          `pulumi:"id"`
	Policies []GetPoliciesLinkedToUserPolicy `pulumi:"policies"`
	UserName string                          `pulumi:"userName"`
}

func GetPoliciesLinkedToUserOutput(ctx *pulumi.Context, args GetPoliciesLinkedToUserOutputArgs, opts ...pulumi.InvokeOption) GetPoliciesLinkedToUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPoliciesLinkedToUserResultOutput, error) {
			args := v.(GetPoliciesLinkedToUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetPoliciesLinkedToUserResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getPoliciesLinkedToUser:getPoliciesLinkedToUser", args, GetPoliciesLinkedToUserResultOutput{}, options).(GetPoliciesLinkedToUserResultOutput), nil
		}).(GetPoliciesLinkedToUserResultOutput)
}

// A collection of arguments for invoking getPoliciesLinkedToUser.
type GetPoliciesLinkedToUserOutputArgs struct {
	Id       pulumi.StringPtrInput `pulumi:"id"`
	UserName pulumi.StringInput    `pulumi:"userName"`
}

func (GetPoliciesLinkedToUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoliciesLinkedToUserArgs)(nil)).Elem()
}

// A collection of values returned by getPoliciesLinkedToUser.
type GetPoliciesLinkedToUserResultOutput struct{ *pulumi.OutputState }

func (GetPoliciesLinkedToUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoliciesLinkedToUserResult)(nil)).Elem()
}

func (o GetPoliciesLinkedToUserResultOutput) ToGetPoliciesLinkedToUserResultOutput() GetPoliciesLinkedToUserResultOutput {
	return o
}

func (o GetPoliciesLinkedToUserResultOutput) ToGetPoliciesLinkedToUserResultOutputWithContext(ctx context.Context) GetPoliciesLinkedToUserResultOutput {
	return o
}

func (o GetPoliciesLinkedToUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPoliciesLinkedToUserResultOutput) Policies() GetPoliciesLinkedToUserPolicyArrayOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserResult) []GetPoliciesLinkedToUserPolicy { return v.Policies }).(GetPoliciesLinkedToUserPolicyArrayOutput)
}

func (o GetPoliciesLinkedToUserResultOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserResult) string { return v.UserName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPoliciesLinkedToUserResultOutput{})
}
