// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPoliciesLinkedToUserGroup(ctx *pulumi.Context, args *GetPoliciesLinkedToUserGroupArgs, opts ...pulumi.InvokeOption) (*GetPoliciesLinkedToUserGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetPoliciesLinkedToUserGroupResult
	err = ctx.InvokePackage("outscale:index/getPoliciesLinkedToUserGroup:getPoliciesLinkedToUserGroup", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPoliciesLinkedToUserGroup.
type GetPoliciesLinkedToUserGroupArgs struct {
	Filters       []GetPoliciesLinkedToUserGroupFilter `pulumi:"filters"`
	Id            *string                              `pulumi:"id"`
	UserGroupName string                               `pulumi:"userGroupName"`
}

// A collection of values returned by getPoliciesLinkedToUserGroup.
type GetPoliciesLinkedToUserGroupResult struct {
	Filters       []GetPoliciesLinkedToUserGroupFilter `pulumi:"filters"`
	Id            string                               `pulumi:"id"`
	Policies      []GetPoliciesLinkedToUserGroupPolicy `pulumi:"policies"`
	UserGroupName string                               `pulumi:"userGroupName"`
}

func GetPoliciesLinkedToUserGroupOutput(ctx *pulumi.Context, args GetPoliciesLinkedToUserGroupOutputArgs, opts ...pulumi.InvokeOption) GetPoliciesLinkedToUserGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPoliciesLinkedToUserGroupResultOutput, error) {
			args := v.(GetPoliciesLinkedToUserGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetPoliciesLinkedToUserGroupResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getPoliciesLinkedToUserGroup:getPoliciesLinkedToUserGroup", args, GetPoliciesLinkedToUserGroupResultOutput{}, options).(GetPoliciesLinkedToUserGroupResultOutput), nil
		}).(GetPoliciesLinkedToUserGroupResultOutput)
}

// A collection of arguments for invoking getPoliciesLinkedToUserGroup.
type GetPoliciesLinkedToUserGroupOutputArgs struct {
	Filters       GetPoliciesLinkedToUserGroupFilterArrayInput `pulumi:"filters"`
	Id            pulumi.StringPtrInput                        `pulumi:"id"`
	UserGroupName pulumi.StringInput                           `pulumi:"userGroupName"`
}

func (GetPoliciesLinkedToUserGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoliciesLinkedToUserGroupArgs)(nil)).Elem()
}

// A collection of values returned by getPoliciesLinkedToUserGroup.
type GetPoliciesLinkedToUserGroupResultOutput struct{ *pulumi.OutputState }

func (GetPoliciesLinkedToUserGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPoliciesLinkedToUserGroupResult)(nil)).Elem()
}

func (o GetPoliciesLinkedToUserGroupResultOutput) ToGetPoliciesLinkedToUserGroupResultOutput() GetPoliciesLinkedToUserGroupResultOutput {
	return o
}

func (o GetPoliciesLinkedToUserGroupResultOutput) ToGetPoliciesLinkedToUserGroupResultOutputWithContext(ctx context.Context) GetPoliciesLinkedToUserGroupResultOutput {
	return o
}

func (o GetPoliciesLinkedToUserGroupResultOutput) Filters() GetPoliciesLinkedToUserGroupFilterArrayOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserGroupResult) []GetPoliciesLinkedToUserGroupFilter { return v.Filters }).(GetPoliciesLinkedToUserGroupFilterArrayOutput)
}

func (o GetPoliciesLinkedToUserGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPoliciesLinkedToUserGroupResultOutput) Policies() GetPoliciesLinkedToUserGroupPolicyArrayOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserGroupResult) []GetPoliciesLinkedToUserGroupPolicy { return v.Policies }).(GetPoliciesLinkedToUserGroupPolicyArrayOutput)
}

func (o GetPoliciesLinkedToUserGroupResultOutput) UserGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPoliciesLinkedToUserGroupResult) string { return v.UserGroupName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPoliciesLinkedToUserGroupResultOutput{})
}
