// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetProductTypes(ctx *pulumi.Context, args *GetProductTypesArgs, opts ...pulumi.InvokeOption) (*GetProductTypesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetProductTypesResult
	err = ctx.InvokePackage("outscale:index/getProductTypes:getProductTypes", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProductTypes.
type GetProductTypesArgs struct {
	Filters []GetProductTypesFilter `pulumi:"filters"`
	Id      *string                 `pulumi:"id"`
}

// A collection of values returned by getProductTypes.
type GetProductTypesResult struct {
	Filters      []GetProductTypesFilter      `pulumi:"filters"`
	Id           string                       `pulumi:"id"`
	ProductTypes []GetProductTypesProductType `pulumi:"productTypes"`
	RequestId    string                       `pulumi:"requestId"`
}

func GetProductTypesOutput(ctx *pulumi.Context, args GetProductTypesOutputArgs, opts ...pulumi.InvokeOption) GetProductTypesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetProductTypesResultOutput, error) {
			args := v.(GetProductTypesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetProductTypesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getProductTypes:getProductTypes", args, GetProductTypesResultOutput{}, options).(GetProductTypesResultOutput), nil
		}).(GetProductTypesResultOutput)
}

// A collection of arguments for invoking getProductTypes.
type GetProductTypesOutputArgs struct {
	Filters GetProductTypesFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput           `pulumi:"id"`
}

func (GetProductTypesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductTypesArgs)(nil)).Elem()
}

// A collection of values returned by getProductTypes.
type GetProductTypesResultOutput struct{ *pulumi.OutputState }

func (GetProductTypesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductTypesResult)(nil)).Elem()
}

func (o GetProductTypesResultOutput) ToGetProductTypesResultOutput() GetProductTypesResultOutput {
	return o
}

func (o GetProductTypesResultOutput) ToGetProductTypesResultOutputWithContext(ctx context.Context) GetProductTypesResultOutput {
	return o
}

func (o GetProductTypesResultOutput) Filters() GetProductTypesFilterArrayOutput {
	return o.ApplyT(func(v GetProductTypesResult) []GetProductTypesFilter { return v.Filters }).(GetProductTypesFilterArrayOutput)
}

func (o GetProductTypesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductTypesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetProductTypesResultOutput) ProductTypes() GetProductTypesProductTypeArrayOutput {
	return o.ApplyT(func(v GetProductTypesResult) []GetProductTypesProductType { return v.ProductTypes }).(GetProductTypesProductTypeArrayOutput)
}

func (o GetProductTypesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductTypesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProductTypesResultOutput{})
}
