// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupRouteTable(ctx *pulumi.Context, args *LookupRouteTableArgs, opts ...pulumi.InvokeOption) (*LookupRouteTableResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupRouteTableResult
	err = ctx.InvokePackage("outscale:index/getRouteTable:getRouteTable", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getRouteTable.
type LookupRouteTableArgs struct {
	Filters      []GetRouteTableFilter `pulumi:"filters"`
	Id           *string               `pulumi:"id"`
	RouteTableId *string               `pulumi:"routeTableId"`
}

// A collection of values returned by getRouteTable.
type LookupRouteTableResult struct {
	Filters                         []GetRouteTableFilter                         `pulumi:"filters"`
	Id                              string                                        `pulumi:"id"`
	LinkRouteTables                 []GetRouteTableLinkRouteTable                 `pulumi:"linkRouteTables"`
	NetId                           string                                        `pulumi:"netId"`
	RequestId                       string                                        `pulumi:"requestId"`
	RoutePropagatingVirtualGateways []GetRouteTableRoutePropagatingVirtualGateway `pulumi:"routePropagatingVirtualGateways"`
	RouteTableId                    string                                        `pulumi:"routeTableId"`
	Routes                          []GetRouteTableRoute                          `pulumi:"routes"`
	Tags                            []GetRouteTableTag                            `pulumi:"tags"`
}

func LookupRouteTableOutput(ctx *pulumi.Context, args LookupRouteTableOutputArgs, opts ...pulumi.InvokeOption) LookupRouteTableResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupRouteTableResultOutput, error) {
			args := v.(LookupRouteTableArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupRouteTableResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getRouteTable:getRouteTable", args, LookupRouteTableResultOutput{}, options).(LookupRouteTableResultOutput), nil
		}).(LookupRouteTableResultOutput)
}

// A collection of arguments for invoking getRouteTable.
type LookupRouteTableOutputArgs struct {
	Filters      GetRouteTableFilterArrayInput `pulumi:"filters"`
	Id           pulumi.StringPtrInput         `pulumi:"id"`
	RouteTableId pulumi.StringPtrInput         `pulumi:"routeTableId"`
}

func (LookupRouteTableOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouteTableArgs)(nil)).Elem()
}

// A collection of values returned by getRouteTable.
type LookupRouteTableResultOutput struct{ *pulumi.OutputState }

func (LookupRouteTableResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupRouteTableResult)(nil)).Elem()
}

func (o LookupRouteTableResultOutput) ToLookupRouteTableResultOutput() LookupRouteTableResultOutput {
	return o
}

func (o LookupRouteTableResultOutput) ToLookupRouteTableResultOutputWithContext(ctx context.Context) LookupRouteTableResultOutput {
	return o
}

func (o LookupRouteTableResultOutput) Filters() GetRouteTableFilterArrayOutput {
	return o.ApplyT(func(v LookupRouteTableResult) []GetRouteTableFilter { return v.Filters }).(GetRouteTableFilterArrayOutput)
}

func (o LookupRouteTableResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteTableResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupRouteTableResultOutput) LinkRouteTables() GetRouteTableLinkRouteTableArrayOutput {
	return o.ApplyT(func(v LookupRouteTableResult) []GetRouteTableLinkRouteTable { return v.LinkRouteTables }).(GetRouteTableLinkRouteTableArrayOutput)
}

func (o LookupRouteTableResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteTableResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupRouteTableResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteTableResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupRouteTableResultOutput) RoutePropagatingVirtualGateways() GetRouteTableRoutePropagatingVirtualGatewayArrayOutput {
	return o.ApplyT(func(v LookupRouteTableResult) []GetRouteTableRoutePropagatingVirtualGateway {
		return v.RoutePropagatingVirtualGateways
	}).(GetRouteTableRoutePropagatingVirtualGatewayArrayOutput)
}

func (o LookupRouteTableResultOutput) RouteTableId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupRouteTableResult) string { return v.RouteTableId }).(pulumi.StringOutput)
}

func (o LookupRouteTableResultOutput) Routes() GetRouteTableRouteArrayOutput {
	return o.ApplyT(func(v LookupRouteTableResult) []GetRouteTableRoute { return v.Routes }).(GetRouteTableRouteArrayOutput)
}

func (o LookupRouteTableResultOutput) Tags() GetRouteTableTagArrayOutput {
	return o.ApplyT(func(v LookupRouteTableResult) []GetRouteTableTag { return v.Tags }).(GetRouteTableTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupRouteTableResultOutput{})
}
