// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSnapshotExportTasks(ctx *pulumi.Context, args *GetSnapshotExportTasksArgs, opts ...pulumi.InvokeOption) (*GetSnapshotExportTasksResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetSnapshotExportTasksResult
	err = ctx.InvokePackage("outscale:index/getSnapshotExportTasks:getSnapshotExportTasks", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSnapshotExportTasks.
type GetSnapshotExportTasksArgs struct {
	DryRun   *bool                           `pulumi:"dryRun"`
	Filters  []GetSnapshotExportTasksFilter  `pulumi:"filters"`
	Id       *string                         `pulumi:"id"`
	Timeouts *GetSnapshotExportTasksTimeouts `pulumi:"timeouts"`
}

// A collection of values returned by getSnapshotExportTasks.
type GetSnapshotExportTasksResult struct {
	DryRun              bool                                       `pulumi:"dryRun"`
	Filters             []GetSnapshotExportTasksFilter             `pulumi:"filters"`
	Id                  string                                     `pulumi:"id"`
	RequestId           string                                     `pulumi:"requestId"`
	SnapshotExportTasks []GetSnapshotExportTasksSnapshotExportTask `pulumi:"snapshotExportTasks"`
	Timeouts            *GetSnapshotExportTasksTimeouts            `pulumi:"timeouts"`
}

func GetSnapshotExportTasksOutput(ctx *pulumi.Context, args GetSnapshotExportTasksOutputArgs, opts ...pulumi.InvokeOption) GetSnapshotExportTasksResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSnapshotExportTasksResultOutput, error) {
			args := v.(GetSnapshotExportTasksArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetSnapshotExportTasksResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getSnapshotExportTasks:getSnapshotExportTasks", args, GetSnapshotExportTasksResultOutput{}, options).(GetSnapshotExportTasksResultOutput), nil
		}).(GetSnapshotExportTasksResultOutput)
}

// A collection of arguments for invoking getSnapshotExportTasks.
type GetSnapshotExportTasksOutputArgs struct {
	DryRun   pulumi.BoolPtrInput                    `pulumi:"dryRun"`
	Filters  GetSnapshotExportTasksFilterArrayInput `pulumi:"filters"`
	Id       pulumi.StringPtrInput                  `pulumi:"id"`
	Timeouts GetSnapshotExportTasksTimeoutsPtrInput `pulumi:"timeouts"`
}

func (GetSnapshotExportTasksOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSnapshotExportTasksArgs)(nil)).Elem()
}

// A collection of values returned by getSnapshotExportTasks.
type GetSnapshotExportTasksResultOutput struct{ *pulumi.OutputState }

func (GetSnapshotExportTasksResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSnapshotExportTasksResult)(nil)).Elem()
}

func (o GetSnapshotExportTasksResultOutput) ToGetSnapshotExportTasksResultOutput() GetSnapshotExportTasksResultOutput {
	return o
}

func (o GetSnapshotExportTasksResultOutput) ToGetSnapshotExportTasksResultOutputWithContext(ctx context.Context) GetSnapshotExportTasksResultOutput {
	return o
}

func (o GetSnapshotExportTasksResultOutput) DryRun() pulumi.BoolOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) bool { return v.DryRun }).(pulumi.BoolOutput)
}

func (o GetSnapshotExportTasksResultOutput) Filters() GetSnapshotExportTasksFilterArrayOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) []GetSnapshotExportTasksFilter { return v.Filters }).(GetSnapshotExportTasksFilterArrayOutput)
}

func (o GetSnapshotExportTasksResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSnapshotExportTasksResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetSnapshotExportTasksResultOutput) SnapshotExportTasks() GetSnapshotExportTasksSnapshotExportTaskArrayOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) []GetSnapshotExportTasksSnapshotExportTask {
		return v.SnapshotExportTasks
	}).(GetSnapshotExportTasksSnapshotExportTaskArrayOutput)
}

func (o GetSnapshotExportTasksResultOutput) Timeouts() GetSnapshotExportTasksTimeoutsPtrOutput {
	return o.ApplyT(func(v GetSnapshotExportTasksResult) *GetSnapshotExportTasksTimeouts { return v.Timeouts }).(GetSnapshotExportTasksTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSnapshotExportTasksResultOutput{})
}
