// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetSnapshots(ctx *pulumi.Context, args *GetSnapshotsArgs, opts ...pulumi.InvokeOption) (*GetSnapshotsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetSnapshotsResult
	err = ctx.InvokePackage("outscale:index/getSnapshots:getSnapshots", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSnapshots.
type GetSnapshotsArgs struct {
	AccountIds                []string             `pulumi:"accountIds"`
	Filters                   []GetSnapshotsFilter `pulumi:"filters"`
	Id                        *string              `pulumi:"id"`
	PermissionToCreateVolumes []string             `pulumi:"permissionToCreateVolumes"`
	SnapshotIds               []string             `pulumi:"snapshotIds"`
}

// A collection of values returned by getSnapshots.
type GetSnapshotsResult struct {
	AccountIds                []string               `pulumi:"accountIds"`
	Filters                   []GetSnapshotsFilter   `pulumi:"filters"`
	Id                        string                 `pulumi:"id"`
	PermissionToCreateVolumes []string               `pulumi:"permissionToCreateVolumes"`
	RequestId                 string                 `pulumi:"requestId"`
	SnapshotIds               []string               `pulumi:"snapshotIds"`
	Snapshots                 []GetSnapshotsSnapshot `pulumi:"snapshots"`
}

func GetSnapshotsOutput(ctx *pulumi.Context, args GetSnapshotsOutputArgs, opts ...pulumi.InvokeOption) GetSnapshotsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetSnapshotsResultOutput, error) {
			args := v.(GetSnapshotsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetSnapshotsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getSnapshots:getSnapshots", args, GetSnapshotsResultOutput{}, options).(GetSnapshotsResultOutput), nil
		}).(GetSnapshotsResultOutput)
}

// A collection of arguments for invoking getSnapshots.
type GetSnapshotsOutputArgs struct {
	AccountIds                pulumi.StringArrayInput      `pulumi:"accountIds"`
	Filters                   GetSnapshotsFilterArrayInput `pulumi:"filters"`
	Id                        pulumi.StringPtrInput        `pulumi:"id"`
	PermissionToCreateVolumes pulumi.StringArrayInput      `pulumi:"permissionToCreateVolumes"`
	SnapshotIds               pulumi.StringArrayInput      `pulumi:"snapshotIds"`
}

func (GetSnapshotsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSnapshotsArgs)(nil)).Elem()
}

// A collection of values returned by getSnapshots.
type GetSnapshotsResultOutput struct{ *pulumi.OutputState }

func (GetSnapshotsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetSnapshotsResult)(nil)).Elem()
}

func (o GetSnapshotsResultOutput) ToGetSnapshotsResultOutput() GetSnapshotsResultOutput {
	return o
}

func (o GetSnapshotsResultOutput) ToGetSnapshotsResultOutputWithContext(ctx context.Context) GetSnapshotsResultOutput {
	return o
}

func (o GetSnapshotsResultOutput) AccountIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSnapshotsResult) []string { return v.AccountIds }).(pulumi.StringArrayOutput)
}

func (o GetSnapshotsResultOutput) Filters() GetSnapshotsFilterArrayOutput {
	return o.ApplyT(func(v GetSnapshotsResult) []GetSnapshotsFilter { return v.Filters }).(GetSnapshotsFilterArrayOutput)
}

func (o GetSnapshotsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetSnapshotsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetSnapshotsResultOutput) PermissionToCreateVolumes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSnapshotsResult) []string { return v.PermissionToCreateVolumes }).(pulumi.StringArrayOutput)
}

func (o GetSnapshotsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetSnapshotsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetSnapshotsResultOutput) SnapshotIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetSnapshotsResult) []string { return v.SnapshotIds }).(pulumi.StringArrayOutput)
}

func (o GetSnapshotsResultOutput) Snapshots() GetSnapshotsSnapshotArrayOutput {
	return o.ApplyT(func(v GetSnapshotsResult) []GetSnapshotsSnapshot { return v.Snapshots }).(GetSnapshotsSnapshotArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetSnapshotsResultOutput{})
}
