// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetServerCertificates(ctx *pulumi.Context, args *GetServerCertificatesArgs, opts ...pulumi.InvokeOption) (*GetServerCertificatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetServerCertificatesResult
	err = ctx.InvokePackage("outscale:index/getServerCertificates:getServerCertificates", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getServerCertificates.
type GetServerCertificatesArgs struct {
	Filters []GetServerCertificatesFilter `pulumi:"filters"`
	Id      *string                       `pulumi:"id"`
}

// A collection of values returned by getServerCertificates.
type GetServerCertificatesResult struct {
	Filters            []GetServerCertificatesFilter            `pulumi:"filters"`
	Id                 string                                   `pulumi:"id"`
	RequestId          string                                   `pulumi:"requestId"`
	ServerCertificates []GetServerCertificatesServerCertificate `pulumi:"serverCertificates"`
}

func GetServerCertificatesOutput(ctx *pulumi.Context, args GetServerCertificatesOutputArgs, opts ...pulumi.InvokeOption) GetServerCertificatesResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetServerCertificatesResultOutput, error) {
			args := v.(GetServerCertificatesArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetServerCertificatesResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getServerCertificates:getServerCertificates", args, GetServerCertificatesResultOutput{}, options).(GetServerCertificatesResultOutput), nil
		}).(GetServerCertificatesResultOutput)
}

// A collection of arguments for invoking getServerCertificates.
type GetServerCertificatesOutputArgs struct {
	Filters GetServerCertificatesFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput                 `pulumi:"id"`
}

func (GetServerCertificatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerCertificatesArgs)(nil)).Elem()
}

// A collection of values returned by getServerCertificates.
type GetServerCertificatesResultOutput struct{ *pulumi.OutputState }

func (GetServerCertificatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetServerCertificatesResult)(nil)).Elem()
}

func (o GetServerCertificatesResultOutput) ToGetServerCertificatesResultOutput() GetServerCertificatesResultOutput {
	return o
}

func (o GetServerCertificatesResultOutput) ToGetServerCertificatesResultOutputWithContext(ctx context.Context) GetServerCertificatesResultOutput {
	return o
}

func (o GetServerCertificatesResultOutput) Filters() GetServerCertificatesFilterArrayOutput {
	return o.ApplyT(func(v GetServerCertificatesResult) []GetServerCertificatesFilter { return v.Filters }).(GetServerCertificatesFilterArrayOutput)
}

func (o GetServerCertificatesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerCertificatesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetServerCertificatesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetServerCertificatesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetServerCertificatesResultOutput) ServerCertificates() GetServerCertificatesServerCertificateArrayOutput {
	return o.ApplyT(func(v GetServerCertificatesResult) []GetServerCertificatesServerCertificate {
		return v.ServerCertificates
	}).(GetServerCertificatesServerCertificateArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetServerCertificatesResultOutput{})
}
