// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupTag(ctx *pulumi.Context, args *LookupTagArgs, opts ...pulumi.InvokeOption) (*LookupTagResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupTagResult
	err = ctx.InvokePackage("outscale:index/getTag:getTag", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTag.
type LookupTagArgs struct {
	Filters []GetTagFilter `pulumi:"filters"`
	Id      *string        `pulumi:"id"`
}

// A collection of values returned by getTag.
type LookupTagResult struct {
	Filters      []GetTagFilter `pulumi:"filters"`
	Id           string         `pulumi:"id"`
	Key          string         `pulumi:"key"`
	ResourceId   string         `pulumi:"resourceId"`
	ResourceType string         `pulumi:"resourceType"`
	Value        string         `pulumi:"value"`
}

func LookupTagOutput(ctx *pulumi.Context, args LookupTagOutputArgs, opts ...pulumi.InvokeOption) LookupTagResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupTagResultOutput, error) {
			args := v.(LookupTagArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupTagResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getTag:getTag", args, LookupTagResultOutput{}, options).(LookupTagResultOutput), nil
		}).(LookupTagResultOutput)
}

// A collection of arguments for invoking getTag.
type LookupTagOutputArgs struct {
	Filters GetTagFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput  `pulumi:"id"`
}

func (LookupTagOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTagArgs)(nil)).Elem()
}

// A collection of values returned by getTag.
type LookupTagResultOutput struct{ *pulumi.OutputState }

func (LookupTagResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupTagResult)(nil)).Elem()
}

func (o LookupTagResultOutput) ToLookupTagResultOutput() LookupTagResultOutput {
	return o
}

func (o LookupTagResultOutput) ToLookupTagResultOutputWithContext(ctx context.Context) LookupTagResultOutput {
	return o
}

func (o LookupTagResultOutput) Filters() GetTagFilterArrayOutput {
	return o.ApplyT(func(v LookupTagResult) []GetTagFilter { return v.Filters }).(GetTagFilterArrayOutput)
}

func (o LookupTagResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupTagResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Key }).(pulumi.StringOutput)
}

func (o LookupTagResultOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.ResourceId }).(pulumi.StringOutput)
}

func (o LookupTagResultOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.ResourceType }).(pulumi.StringOutput)
}

func (o LookupTagResultOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v LookupTagResult) string { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupTagResultOutput{})
}
