// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupUserGroup(ctx *pulumi.Context, args *LookupUserGroupArgs, opts ...pulumi.InvokeOption) (*LookupUserGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupUserGroupResult
	err = ctx.InvokePackage("outscale:index/getUserGroup:getUserGroup", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUserGroup.
type LookupUserGroupArgs struct {
	Id            *string            `pulumi:"id"`
	Path          *string            `pulumi:"path"`
	UserGroupName string             `pulumi:"userGroupName"`
	Users         []GetUserGroupUser `pulumi:"users"`
}

// A collection of values returned by getUserGroup.
type LookupUserGroupResult struct {
	CreationDate         string             `pulumi:"creationDate"`
	Id                   string             `pulumi:"id"`
	LastModificationDate string             `pulumi:"lastModificationDate"`
	Orn                  string             `pulumi:"orn"`
	Path                 *string            `pulumi:"path"`
	UserGroupId          string             `pulumi:"userGroupId"`
	UserGroupName        string             `pulumi:"userGroupName"`
	Users                []GetUserGroupUser `pulumi:"users"`
}

func LookupUserGroupOutput(ctx *pulumi.Context, args LookupUserGroupOutputArgs, opts ...pulumi.InvokeOption) LookupUserGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupUserGroupResultOutput, error) {
			args := v.(LookupUserGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupUserGroupResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getUserGroup:getUserGroup", args, LookupUserGroupResultOutput{}, options).(LookupUserGroupResultOutput), nil
		}).(LookupUserGroupResultOutput)
}

// A collection of arguments for invoking getUserGroup.
type LookupUserGroupOutputArgs struct {
	Id            pulumi.StringPtrInput      `pulumi:"id"`
	Path          pulumi.StringPtrInput      `pulumi:"path"`
	UserGroupName pulumi.StringInput         `pulumi:"userGroupName"`
	Users         GetUserGroupUserArrayInput `pulumi:"users"`
}

func (LookupUserGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserGroupArgs)(nil)).Elem()
}

// A collection of values returned by getUserGroup.
type LookupUserGroupResultOutput struct{ *pulumi.OutputState }

func (LookupUserGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserGroupResult)(nil)).Elem()
}

func (o LookupUserGroupResultOutput) ToLookupUserGroupResultOutput() LookupUserGroupResultOutput {
	return o
}

func (o LookupUserGroupResultOutput) ToLookupUserGroupResultOutputWithContext(ctx context.Context) LookupUserGroupResultOutput {
	return o
}

func (o LookupUserGroupResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) LastModificationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.LastModificationDate }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) Orn() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.Orn }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupUserGroupResult) *string { return v.Path }).(pulumi.StringPtrOutput)
}

func (o LookupUserGroupResultOutput) UserGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.UserGroupId }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) UserGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.UserGroupName }).(pulumi.StringOutput)
}

func (o LookupUserGroupResultOutput) Users() GetUserGroupUserArrayOutput {
	return o.ApplyT(func(v LookupUserGroupResult) []GetUserGroupUser { return v.Users }).(GetUserGroupUserArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserGroupResultOutput{})
}
