// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetUserGroups(ctx *pulumi.Context, args *GetUserGroupsArgs, opts ...pulumi.InvokeOption) (*GetUserGroupsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetUserGroupsResult
	err = ctx.InvokePackage("outscale:index/getUserGroups:getUserGroups", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUserGroups.
type GetUserGroupsArgs struct {
	Filters []GetUserGroupsFilter `pulumi:"filters"`
	Id      *string               `pulumi:"id"`
}

// A collection of values returned by getUserGroups.
type GetUserGroupsResult struct {
	Filters    []GetUserGroupsFilter    `pulumi:"filters"`
	Id         string                   `pulumi:"id"`
	UserGroups []GetUserGroupsUserGroup `pulumi:"userGroups"`
}

func GetUserGroupsOutput(ctx *pulumi.Context, args GetUserGroupsOutputArgs, opts ...pulumi.InvokeOption) GetUserGroupsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetUserGroupsResultOutput, error) {
			args := v.(GetUserGroupsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetUserGroupsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getUserGroups:getUserGroups", args, GetUserGroupsResultOutput{}, options).(GetUserGroupsResultOutput), nil
		}).(GetUserGroupsResultOutput)
}

// A collection of arguments for invoking getUserGroups.
type GetUserGroupsOutputArgs struct {
	Filters GetUserGroupsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput         `pulumi:"id"`
}

func (GetUserGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getUserGroups.
type GetUserGroupsResultOutput struct{ *pulumi.OutputState }

func (GetUserGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserGroupsResult)(nil)).Elem()
}

func (o GetUserGroupsResultOutput) ToGetUserGroupsResultOutput() GetUserGroupsResultOutput {
	return o
}

func (o GetUserGroupsResultOutput) ToGetUserGroupsResultOutputWithContext(ctx context.Context) GetUserGroupsResultOutput {
	return o
}

func (o GetUserGroupsResultOutput) Filters() GetUserGroupsFilterArrayOutput {
	return o.ApplyT(func(v GetUserGroupsResult) []GetUserGroupsFilter { return v.Filters }).(GetUserGroupsFilterArrayOutput)
}

func (o GetUserGroupsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserGroupsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetUserGroupsResultOutput) UserGroups() GetUserGroupsUserGroupArrayOutput {
	return o.ApplyT(func(v GetUserGroupsResult) []GetUserGroupsUserGroup { return v.UserGroups }).(GetUserGroupsUserGroupArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUserGroupsResultOutput{})
}
