// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVms(ctx *pulumi.Context, args *GetVmsArgs, opts ...pulumi.InvokeOption) (*GetVmsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetVmsResult
	err = ctx.InvokePackage("outscale:index/getVms:getVms", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVms.
type GetVmsArgs struct {
	Filters []GetVmsFilter `pulumi:"filters"`
	Id      *string        `pulumi:"id"`
}

// A collection of values returned by getVms.
type GetVmsResult struct {
	Filters   []GetVmsFilter `pulumi:"filters"`
	Id        string         `pulumi:"id"`
	RequestId string         `pulumi:"requestId"`
	Vms       []GetVmsVm     `pulumi:"vms"`
}

func GetVmsOutput(ctx *pulumi.Context, args GetVmsOutputArgs, opts ...pulumi.InvokeOption) GetVmsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVmsResultOutput, error) {
			args := v.(GetVmsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetVmsResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getVms:getVms", args, GetVmsResultOutput{}, options).(GetVmsResultOutput), nil
		}).(GetVmsResultOutput)
}

// A collection of arguments for invoking getVms.
type GetVmsOutputArgs struct {
	Filters GetVmsFilterArrayInput `pulumi:"filters"`
	Id      pulumi.StringPtrInput  `pulumi:"id"`
}

func (GetVmsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmsArgs)(nil)).Elem()
}

// A collection of values returned by getVms.
type GetVmsResultOutput struct{ *pulumi.OutputState }

func (GetVmsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmsResult)(nil)).Elem()
}

func (o GetVmsResultOutput) ToGetVmsResultOutput() GetVmsResultOutput {
	return o
}

func (o GetVmsResultOutput) ToGetVmsResultOutputWithContext(ctx context.Context) GetVmsResultOutput {
	return o
}

func (o GetVmsResultOutput) Filters() GetVmsFilterArrayOutput {
	return o.ApplyT(func(v GetVmsResult) []GetVmsFilter { return v.Filters }).(GetVmsFilterArrayOutput)
}

func (o GetVmsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVmsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetVmsResultOutput) Vms() GetVmsVmArrayOutput {
	return o.ApplyT(func(v GetVmsResult) []GetVmsVm { return v.Vms }).(GetVmsVmArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVmsResultOutput{})
}
