// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetVirtualGateways(ctx *pulumi.Context, args *GetVirtualGatewaysArgs, opts ...pulumi.InvokeOption) (*GetVirtualGatewaysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetVirtualGatewaysResult
	err = ctx.InvokePackage("outscale:index/getVirtualGateways:getVirtualGateways", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVirtualGateways.
type GetVirtualGatewaysArgs struct {
	Filters           []GetVirtualGatewaysFilter `pulumi:"filters"`
	Id                *string                    `pulumi:"id"`
	VirtualGatewayIds []string                   `pulumi:"virtualGatewayIds"`
}

// A collection of values returned by getVirtualGateways.
type GetVirtualGatewaysResult struct {
	Filters           []GetVirtualGatewaysFilter         `pulumi:"filters"`
	Id                string                             `pulumi:"id"`
	RequestId         string                             `pulumi:"requestId"`
	VirtualGatewayIds []string                           `pulumi:"virtualGatewayIds"`
	VirtualGateways   []GetVirtualGatewaysVirtualGateway `pulumi:"virtualGateways"`
}

func GetVirtualGatewaysOutput(ctx *pulumi.Context, args GetVirtualGatewaysOutputArgs, opts ...pulumi.InvokeOption) GetVirtualGatewaysResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetVirtualGatewaysResultOutput, error) {
			args := v.(GetVirtualGatewaysArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetVirtualGatewaysResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("outscale:index/getVirtualGateways:getVirtualGateways", args, GetVirtualGatewaysResultOutput{}, options).(GetVirtualGatewaysResultOutput), nil
		}).(GetVirtualGatewaysResultOutput)
}

// A collection of arguments for invoking getVirtualGateways.
type GetVirtualGatewaysOutputArgs struct {
	Filters           GetVirtualGatewaysFilterArrayInput `pulumi:"filters"`
	Id                pulumi.StringPtrInput              `pulumi:"id"`
	VirtualGatewayIds pulumi.StringArrayInput            `pulumi:"virtualGatewayIds"`
}

func (GetVirtualGatewaysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualGatewaysArgs)(nil)).Elem()
}

// A collection of values returned by getVirtualGateways.
type GetVirtualGatewaysResultOutput struct{ *pulumi.OutputState }

func (GetVirtualGatewaysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualGatewaysResult)(nil)).Elem()
}

func (o GetVirtualGatewaysResultOutput) ToGetVirtualGatewaysResultOutput() GetVirtualGatewaysResultOutput {
	return o
}

func (o GetVirtualGatewaysResultOutput) ToGetVirtualGatewaysResultOutputWithContext(ctx context.Context) GetVirtualGatewaysResultOutput {
	return o
}

func (o GetVirtualGatewaysResultOutput) Filters() GetVirtualGatewaysFilterArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []GetVirtualGatewaysFilter { return v.Filters }).(GetVirtualGatewaysFilterArrayOutput)
}

func (o GetVirtualGatewaysResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVirtualGatewaysResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetVirtualGatewaysResultOutput) VirtualGatewayIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []string { return v.VirtualGatewayIds }).(pulumi.StringArrayOutput)
}

func (o GetVirtualGatewaysResultOutput) VirtualGateways() GetVirtualGatewaysVirtualGatewayArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []GetVirtualGatewaysVirtualGateway { return v.VirtualGateways }).(GetVirtualGatewaysVirtualGatewayArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVirtualGatewaysResultOutput{})
}
