// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Image struct {
	pulumi.CustomResourceState

	AccountAlias          pulumi.StringOutput                 `pulumi:"accountAlias"`
	AccountId             pulumi.StringOutput                 `pulumi:"accountId"`
	Architecture          pulumi.StringOutput                 `pulumi:"architecture"`
	BlockDeviceMappings   ImageBlockDeviceMappingArrayOutput  `pulumi:"blockDeviceMappings"`
	BootModes             pulumi.StringArrayOutput            `pulumi:"bootModes"`
	CreationDate          pulumi.StringOutput                 `pulumi:"creationDate"`
	Description           pulumi.StringOutput                 `pulumi:"description"`
	FileLocation          pulumi.StringOutput                 `pulumi:"fileLocation"`
	ImageId               pulumi.StringOutput                 `pulumi:"imageId"`
	ImageName             pulumi.StringOutput                 `pulumi:"imageName"`
	ImageType             pulumi.StringOutput                 `pulumi:"imageType"`
	IsPublic              pulumi.BoolOutput                   `pulumi:"isPublic"`
	NoReboot              pulumi.BoolOutput                   `pulumi:"noReboot"`
	OutscaleImageId       pulumi.StringOutput                 `pulumi:"outscaleImageId"`
	PermissionsToLaunches ImagePermissionsToLaunchArrayOutput `pulumi:"permissionsToLaunches"`
	ProductCodes          pulumi.StringArrayOutput            `pulumi:"productCodes"`
	RequestId             pulumi.StringOutput                 `pulumi:"requestId"`
	RootDeviceName        pulumi.StringOutput                 `pulumi:"rootDeviceName"`
	RootDeviceType        pulumi.StringOutput                 `pulumi:"rootDeviceType"`
	SourceImageId         pulumi.StringOutput                 `pulumi:"sourceImageId"`
	SourceRegionName      pulumi.StringPtrOutput              `pulumi:"sourceRegionName"`
	State                 pulumi.StringOutput                 `pulumi:"state"`
	StateComments         ImageStateCommentArrayOutput        `pulumi:"stateComments"`
	Tags                  ImageTagArrayOutput                 `pulumi:"tags"`
	Timeouts              ImageTimeoutsPtrOutput              `pulumi:"timeouts"`
	VmId                  pulumi.StringOutput                 `pulumi:"vmId"`
}

// NewImage registers a new resource with the given unique name, arguments, and options.
func NewImage(ctx *pulumi.Context,
	name string, args *ImageArgs, opts ...pulumi.ResourceOption) (*Image, error) {
	if args == nil {
		args = &ImageArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Image
	err = ctx.RegisterPackageResource("outscale:index/image:Image", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImage gets an existing Image resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImage(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageState, opts ...pulumi.ResourceOption) (*Image, error) {
	var resource Image
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/image:Image", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Image resources.
type imageState struct {
	AccountAlias          *string                    `pulumi:"accountAlias"`
	AccountId             *string                    `pulumi:"accountId"`
	Architecture          *string                    `pulumi:"architecture"`
	BlockDeviceMappings   []ImageBlockDeviceMapping  `pulumi:"blockDeviceMappings"`
	BootModes             []string                   `pulumi:"bootModes"`
	CreationDate          *string                    `pulumi:"creationDate"`
	Description           *string                    `pulumi:"description"`
	FileLocation          *string                    `pulumi:"fileLocation"`
	ImageId               *string                    `pulumi:"imageId"`
	ImageName             *string                    `pulumi:"imageName"`
	ImageType             *string                    `pulumi:"imageType"`
	IsPublic              *bool                      `pulumi:"isPublic"`
	NoReboot              *bool                      `pulumi:"noReboot"`
	OutscaleImageId       *string                    `pulumi:"outscaleImageId"`
	PermissionsToLaunches []ImagePermissionsToLaunch `pulumi:"permissionsToLaunches"`
	ProductCodes          []string                   `pulumi:"productCodes"`
	RequestId             *string                    `pulumi:"requestId"`
	RootDeviceName        *string                    `pulumi:"rootDeviceName"`
	RootDeviceType        *string                    `pulumi:"rootDeviceType"`
	SourceImageId         *string                    `pulumi:"sourceImageId"`
	SourceRegionName      *string                    `pulumi:"sourceRegionName"`
	State                 *string                    `pulumi:"state"`
	StateComments         []ImageStateComment        `pulumi:"stateComments"`
	Tags                  []ImageTag                 `pulumi:"tags"`
	Timeouts              *ImageTimeouts             `pulumi:"timeouts"`
	VmId                  *string                    `pulumi:"vmId"`
}

type ImageState struct {
	AccountAlias          pulumi.StringPtrInput
	AccountId             pulumi.StringPtrInput
	Architecture          pulumi.StringPtrInput
	BlockDeviceMappings   ImageBlockDeviceMappingArrayInput
	BootModes             pulumi.StringArrayInput
	CreationDate          pulumi.StringPtrInput
	Description           pulumi.StringPtrInput
	FileLocation          pulumi.StringPtrInput
	ImageId               pulumi.StringPtrInput
	ImageName             pulumi.StringPtrInput
	ImageType             pulumi.StringPtrInput
	IsPublic              pulumi.BoolPtrInput
	NoReboot              pulumi.BoolPtrInput
	OutscaleImageId       pulumi.StringPtrInput
	PermissionsToLaunches ImagePermissionsToLaunchArrayInput
	ProductCodes          pulumi.StringArrayInput
	RequestId             pulumi.StringPtrInput
	RootDeviceName        pulumi.StringPtrInput
	RootDeviceType        pulumi.StringPtrInput
	SourceImageId         pulumi.StringPtrInput
	SourceRegionName      pulumi.StringPtrInput
	State                 pulumi.StringPtrInput
	StateComments         ImageStateCommentArrayInput
	Tags                  ImageTagArrayInput
	Timeouts              ImageTimeoutsPtrInput
	VmId                  pulumi.StringPtrInput
}

func (ImageState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageState)(nil)).Elem()
}

type imageArgs struct {
	Architecture        *string                   `pulumi:"architecture"`
	BlockDeviceMappings []ImageBlockDeviceMapping `pulumi:"blockDeviceMappings"`
	BootModes           []string                  `pulumi:"bootModes"`
	Description         *string                   `pulumi:"description"`
	FileLocation        *string                   `pulumi:"fileLocation"`
	ImageName           *string                   `pulumi:"imageName"`
	NoReboot            *bool                     `pulumi:"noReboot"`
	OutscaleImageId     *string                   `pulumi:"outscaleImageId"`
	RootDeviceName      *string                   `pulumi:"rootDeviceName"`
	SourceImageId       *string                   `pulumi:"sourceImageId"`
	SourceRegionName    *string                   `pulumi:"sourceRegionName"`
	Tags                []ImageTag                `pulumi:"tags"`
	Timeouts            *ImageTimeouts            `pulumi:"timeouts"`
	VmId                *string                   `pulumi:"vmId"`
}

// The set of arguments for constructing a Image resource.
type ImageArgs struct {
	Architecture        pulumi.StringPtrInput
	BlockDeviceMappings ImageBlockDeviceMappingArrayInput
	BootModes           pulumi.StringArrayInput
	Description         pulumi.StringPtrInput
	FileLocation        pulumi.StringPtrInput
	ImageName           pulumi.StringPtrInput
	NoReboot            pulumi.BoolPtrInput
	OutscaleImageId     pulumi.StringPtrInput
	RootDeviceName      pulumi.StringPtrInput
	SourceImageId       pulumi.StringPtrInput
	SourceRegionName    pulumi.StringPtrInput
	Tags                ImageTagArrayInput
	Timeouts            ImageTimeoutsPtrInput
	VmId                pulumi.StringPtrInput
}

func (ImageArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageArgs)(nil)).Elem()
}

type ImageInput interface {
	pulumi.Input

	ToImageOutput() ImageOutput
	ToImageOutputWithContext(ctx context.Context) ImageOutput
}

func (*Image) ElementType() reflect.Type {
	return reflect.TypeOf((**Image)(nil)).Elem()
}

func (i *Image) ToImageOutput() ImageOutput {
	return i.ToImageOutputWithContext(context.Background())
}

func (i *Image) ToImageOutputWithContext(ctx context.Context) ImageOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageOutput)
}

type ImageOutput struct{ *pulumi.OutputState }

func (ImageOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Image)(nil)).Elem()
}

func (o ImageOutput) ToImageOutput() ImageOutput {
	return o
}

func (o ImageOutput) ToImageOutputWithContext(ctx context.Context) ImageOutput {
	return o
}

func (o ImageOutput) AccountAlias() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.AccountAlias }).(pulumi.StringOutput)
}

func (o ImageOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

func (o ImageOutput) Architecture() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.Architecture }).(pulumi.StringOutput)
}

func (o ImageOutput) BlockDeviceMappings() ImageBlockDeviceMappingArrayOutput {
	return o.ApplyT(func(v *Image) ImageBlockDeviceMappingArrayOutput { return v.BlockDeviceMappings }).(ImageBlockDeviceMappingArrayOutput)
}

func (o ImageOutput) BootModes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Image) pulumi.StringArrayOutput { return v.BootModes }).(pulumi.StringArrayOutput)
}

func (o ImageOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o ImageOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o ImageOutput) FileLocation() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.FileLocation }).(pulumi.StringOutput)
}

func (o ImageOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

func (o ImageOutput) ImageName() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.ImageName }).(pulumi.StringOutput)
}

func (o ImageOutput) ImageType() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.ImageType }).(pulumi.StringOutput)
}

func (o ImageOutput) IsPublic() pulumi.BoolOutput {
	return o.ApplyT(func(v *Image) pulumi.BoolOutput { return v.IsPublic }).(pulumi.BoolOutput)
}

func (o ImageOutput) NoReboot() pulumi.BoolOutput {
	return o.ApplyT(func(v *Image) pulumi.BoolOutput { return v.NoReboot }).(pulumi.BoolOutput)
}

func (o ImageOutput) OutscaleImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.OutscaleImageId }).(pulumi.StringOutput)
}

func (o ImageOutput) PermissionsToLaunches() ImagePermissionsToLaunchArrayOutput {
	return o.ApplyT(func(v *Image) ImagePermissionsToLaunchArrayOutput { return v.PermissionsToLaunches }).(ImagePermissionsToLaunchArrayOutput)
}

func (o ImageOutput) ProductCodes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Image) pulumi.StringArrayOutput { return v.ProductCodes }).(pulumi.StringArrayOutput)
}

func (o ImageOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o ImageOutput) RootDeviceName() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.RootDeviceName }).(pulumi.StringOutput)
}

func (o ImageOutput) RootDeviceType() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.RootDeviceType }).(pulumi.StringOutput)
}

func (o ImageOutput) SourceImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.SourceImageId }).(pulumi.StringOutput)
}

func (o ImageOutput) SourceRegionName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Image) pulumi.StringPtrOutput { return v.SourceRegionName }).(pulumi.StringPtrOutput)
}

func (o ImageOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o ImageOutput) StateComments() ImageStateCommentArrayOutput {
	return o.ApplyT(func(v *Image) ImageStateCommentArrayOutput { return v.StateComments }).(ImageStateCommentArrayOutput)
}

func (o ImageOutput) Tags() ImageTagArrayOutput {
	return o.ApplyT(func(v *Image) ImageTagArrayOutput { return v.Tags }).(ImageTagArrayOutput)
}

func (o ImageOutput) Timeouts() ImageTimeoutsPtrOutput {
	return o.ApplyT(func(v *Image) ImageTimeoutsPtrOutput { return v.Timeouts }).(ImageTimeoutsPtrOutput)
}

func (o ImageOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageInput)(nil)).Elem(), &Image{})
	pulumi.RegisterOutputType(ImageOutput{})
}
