// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ImageLaunchPermission struct {
	pulumi.CustomResourceState

	Description             pulumi.StringOutput                                 `pulumi:"description"`
	ImageId                 pulumi.StringOutput                                 `pulumi:"imageId"`
	ImageLaunchPermissionId pulumi.StringOutput                                 `pulumi:"imageLaunchPermissionId"`
	PermissionAdditions     ImageLaunchPermissionPermissionAdditionsPtrOutput   `pulumi:"permissionAdditions"`
	PermissionRemovals      ImageLaunchPermissionPermissionRemovalsPtrOutput    `pulumi:"permissionRemovals"`
	PermissionsToLaunches   ImageLaunchPermissionPermissionsToLaunchArrayOutput `pulumi:"permissionsToLaunches"`
	RequestId               pulumi.StringOutput                                 `pulumi:"requestId"`
}

// NewImageLaunchPermission registers a new resource with the given unique name, arguments, and options.
func NewImageLaunchPermission(ctx *pulumi.Context,
	name string, args *ImageLaunchPermissionArgs, opts ...pulumi.ResourceOption) (*ImageLaunchPermission, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ImageId == nil {
		return nil, errors.New("invalid value for required argument 'ImageId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ImageLaunchPermission
	err = ctx.RegisterPackageResource("outscale:index/imageLaunchPermission:ImageLaunchPermission", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImageLaunchPermission gets an existing ImageLaunchPermission resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImageLaunchPermission(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageLaunchPermissionState, opts ...pulumi.ResourceOption) (*ImageLaunchPermission, error) {
	var resource ImageLaunchPermission
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/imageLaunchPermission:ImageLaunchPermission", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ImageLaunchPermission resources.
type imageLaunchPermissionState struct {
	Description             *string                                    `pulumi:"description"`
	ImageId                 *string                                    `pulumi:"imageId"`
	ImageLaunchPermissionId *string                                    `pulumi:"imageLaunchPermissionId"`
	PermissionAdditions     *ImageLaunchPermissionPermissionAdditions  `pulumi:"permissionAdditions"`
	PermissionRemovals      *ImageLaunchPermissionPermissionRemovals   `pulumi:"permissionRemovals"`
	PermissionsToLaunches   []ImageLaunchPermissionPermissionsToLaunch `pulumi:"permissionsToLaunches"`
	RequestId               *string                                    `pulumi:"requestId"`
}

type ImageLaunchPermissionState struct {
	Description             pulumi.StringPtrInput
	ImageId                 pulumi.StringPtrInput
	ImageLaunchPermissionId pulumi.StringPtrInput
	PermissionAdditions     ImageLaunchPermissionPermissionAdditionsPtrInput
	PermissionRemovals      ImageLaunchPermissionPermissionRemovalsPtrInput
	PermissionsToLaunches   ImageLaunchPermissionPermissionsToLaunchArrayInput
	RequestId               pulumi.StringPtrInput
}

func (ImageLaunchPermissionState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageLaunchPermissionState)(nil)).Elem()
}

type imageLaunchPermissionArgs struct {
	ImageId                 string                                    `pulumi:"imageId"`
	ImageLaunchPermissionId *string                                   `pulumi:"imageLaunchPermissionId"`
	PermissionAdditions     *ImageLaunchPermissionPermissionAdditions `pulumi:"permissionAdditions"`
	PermissionRemovals      *ImageLaunchPermissionPermissionRemovals  `pulumi:"permissionRemovals"`
}

// The set of arguments for constructing a ImageLaunchPermission resource.
type ImageLaunchPermissionArgs struct {
	ImageId                 pulumi.StringInput
	ImageLaunchPermissionId pulumi.StringPtrInput
	PermissionAdditions     ImageLaunchPermissionPermissionAdditionsPtrInput
	PermissionRemovals      ImageLaunchPermissionPermissionRemovalsPtrInput
}

func (ImageLaunchPermissionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageLaunchPermissionArgs)(nil)).Elem()
}

type ImageLaunchPermissionInput interface {
	pulumi.Input

	ToImageLaunchPermissionOutput() ImageLaunchPermissionOutput
	ToImageLaunchPermissionOutputWithContext(ctx context.Context) ImageLaunchPermissionOutput
}

func (*ImageLaunchPermission) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageLaunchPermission)(nil)).Elem()
}

func (i *ImageLaunchPermission) ToImageLaunchPermissionOutput() ImageLaunchPermissionOutput {
	return i.ToImageLaunchPermissionOutputWithContext(context.Background())
}

func (i *ImageLaunchPermission) ToImageLaunchPermissionOutputWithContext(ctx context.Context) ImageLaunchPermissionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageLaunchPermissionOutput)
}

type ImageLaunchPermissionOutput struct{ *pulumi.OutputState }

func (ImageLaunchPermissionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ImageLaunchPermission)(nil)).Elem()
}

func (o ImageLaunchPermissionOutput) ToImageLaunchPermissionOutput() ImageLaunchPermissionOutput {
	return o
}

func (o ImageLaunchPermissionOutput) ToImageLaunchPermissionOutputWithContext(ctx context.Context) ImageLaunchPermissionOutput {
	return o
}

func (o ImageLaunchPermissionOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o ImageLaunchPermissionOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

func (o ImageLaunchPermissionOutput) ImageLaunchPermissionId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) pulumi.StringOutput { return v.ImageLaunchPermissionId }).(pulumi.StringOutput)
}

func (o ImageLaunchPermissionOutput) PermissionAdditions() ImageLaunchPermissionPermissionAdditionsPtrOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) ImageLaunchPermissionPermissionAdditionsPtrOutput {
		return v.PermissionAdditions
	}).(ImageLaunchPermissionPermissionAdditionsPtrOutput)
}

func (o ImageLaunchPermissionOutput) PermissionRemovals() ImageLaunchPermissionPermissionRemovalsPtrOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) ImageLaunchPermissionPermissionRemovalsPtrOutput {
		return v.PermissionRemovals
	}).(ImageLaunchPermissionPermissionRemovalsPtrOutput)
}

func (o ImageLaunchPermissionOutput) PermissionsToLaunches() ImageLaunchPermissionPermissionsToLaunchArrayOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) ImageLaunchPermissionPermissionsToLaunchArrayOutput {
		return v.PermissionsToLaunches
	}).(ImageLaunchPermissionPermissionsToLaunchArrayOutput)
}

func (o ImageLaunchPermissionOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *ImageLaunchPermission) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageLaunchPermissionInput)(nil)).Elem(), &ImageLaunchPermission{})
	pulumi.RegisterOutputType(ImageLaunchPermissionOutput{})
}
