// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type InternetServiceLink struct {
	pulumi.CustomResourceState

	InternetServiceId pulumi.StringOutput                  `pulumi:"internetServiceId"`
	NetId             pulumi.StringOutput                  `pulumi:"netId"`
	RequestId         pulumi.StringOutput                  `pulumi:"requestId"`
	State             pulumi.StringOutput                  `pulumi:"state"`
	Tags              InternetServiceLinkTagArrayOutput    `pulumi:"tags"`
	Timeouts          InternetServiceLinkTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewInternetServiceLink registers a new resource with the given unique name, arguments, and options.
func NewInternetServiceLink(ctx *pulumi.Context,
	name string, args *InternetServiceLinkArgs, opts ...pulumi.ResourceOption) (*InternetServiceLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.InternetServiceId == nil {
		return nil, errors.New("invalid value for required argument 'InternetServiceId'")
	}
	if args.NetId == nil {
		return nil, errors.New("invalid value for required argument 'NetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource InternetServiceLink
	err = ctx.RegisterPackageResource("outscale:index/internetServiceLink:InternetServiceLink", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInternetServiceLink gets an existing InternetServiceLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInternetServiceLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InternetServiceLinkState, opts ...pulumi.ResourceOption) (*InternetServiceLink, error) {
	var resource InternetServiceLink
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/internetServiceLink:InternetServiceLink", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InternetServiceLink resources.
type internetServiceLinkState struct {
	InternetServiceId *string                      `pulumi:"internetServiceId"`
	NetId             *string                      `pulumi:"netId"`
	RequestId         *string                      `pulumi:"requestId"`
	State             *string                      `pulumi:"state"`
	Tags              []InternetServiceLinkTag     `pulumi:"tags"`
	Timeouts          *InternetServiceLinkTimeouts `pulumi:"timeouts"`
}

type InternetServiceLinkState struct {
	InternetServiceId pulumi.StringPtrInput
	NetId             pulumi.StringPtrInput
	RequestId         pulumi.StringPtrInput
	State             pulumi.StringPtrInput
	Tags              InternetServiceLinkTagArrayInput
	Timeouts          InternetServiceLinkTimeoutsPtrInput
}

func (InternetServiceLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*internetServiceLinkState)(nil)).Elem()
}

type internetServiceLinkArgs struct {
	InternetServiceId string                       `pulumi:"internetServiceId"`
	NetId             string                       `pulumi:"netId"`
	Timeouts          *InternetServiceLinkTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a InternetServiceLink resource.
type InternetServiceLinkArgs struct {
	InternetServiceId pulumi.StringInput
	NetId             pulumi.StringInput
	Timeouts          InternetServiceLinkTimeoutsPtrInput
}

func (InternetServiceLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*internetServiceLinkArgs)(nil)).Elem()
}

type InternetServiceLinkInput interface {
	pulumi.Input

	ToInternetServiceLinkOutput() InternetServiceLinkOutput
	ToInternetServiceLinkOutputWithContext(ctx context.Context) InternetServiceLinkOutput
}

func (*InternetServiceLink) ElementType() reflect.Type {
	return reflect.TypeOf((**InternetServiceLink)(nil)).Elem()
}

func (i *InternetServiceLink) ToInternetServiceLinkOutput() InternetServiceLinkOutput {
	return i.ToInternetServiceLinkOutputWithContext(context.Background())
}

func (i *InternetServiceLink) ToInternetServiceLinkOutputWithContext(ctx context.Context) InternetServiceLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InternetServiceLinkOutput)
}

type InternetServiceLinkOutput struct{ *pulumi.OutputState }

func (InternetServiceLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InternetServiceLink)(nil)).Elem()
}

func (o InternetServiceLinkOutput) ToInternetServiceLinkOutput() InternetServiceLinkOutput {
	return o
}

func (o InternetServiceLinkOutput) ToInternetServiceLinkOutputWithContext(ctx context.Context) InternetServiceLinkOutput {
	return o
}

func (o InternetServiceLinkOutput) InternetServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *InternetServiceLink) pulumi.StringOutput { return v.InternetServiceId }).(pulumi.StringOutput)
}

func (o InternetServiceLinkOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *InternetServiceLink) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o InternetServiceLinkOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *InternetServiceLink) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o InternetServiceLinkOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *InternetServiceLink) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o InternetServiceLinkOutput) Tags() InternetServiceLinkTagArrayOutput {
	return o.ApplyT(func(v *InternetServiceLink) InternetServiceLinkTagArrayOutput { return v.Tags }).(InternetServiceLinkTagArrayOutput)
}

func (o InternetServiceLinkOutput) Timeouts() InternetServiceLinkTimeoutsPtrOutput {
	return o.ApplyT(func(v *InternetServiceLink) InternetServiceLinkTimeoutsPtrOutput { return v.Timeouts }).(InternetServiceLinkTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InternetServiceLinkInput)(nil)).Elem(), &InternetServiceLink{})
	pulumi.RegisterOutputType(InternetServiceLinkOutput{})
}
