// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type LoadBalancerAttributes struct {
	pulumi.CustomResourceState

	AccessLog                        LoadBalancerAttributesAccessLogPtrOutput                        `pulumi:"accessLog"`
	ApplicationStickyCookiePolicies  LoadBalancerAttributesApplicationStickyCookiePolicyArrayOutput  `pulumi:"applicationStickyCookiePolicies"`
	BackendVmIds                     pulumi.StringArrayOutput                                        `pulumi:"backendVmIds"`
	DnsName                          pulumi.StringOutput                                             `pulumi:"dnsName"`
	HealthCheck                      LoadBalancerAttributesHealthCheckPtrOutput                      `pulumi:"healthCheck"`
	Listeners                        LoadBalancerAttributesListenerArrayOutput                       `pulumi:"listeners"`
	LoadBalancerAttributesId         pulumi.StringOutput                                             `pulumi:"loadBalancerAttributesId"`
	LoadBalancerName                 pulumi.StringOutput                                             `pulumi:"loadBalancerName"`
	LoadBalancerPort                 pulumi.Float64PtrOutput                                         `pulumi:"loadBalancerPort"`
	LoadBalancerStickyCookiePolicies LoadBalancerAttributesLoadBalancerStickyCookiePolicyArrayOutput `pulumi:"loadBalancerStickyCookiePolicies"`
	LoadBalancerType                 pulumi.StringOutput                                             `pulumi:"loadBalancerType"`
	PolicyNames                      pulumi.StringArrayOutput                                        `pulumi:"policyNames"`
	RequestId                        pulumi.StringOutput                                             `pulumi:"requestId"`
	SecurityGroups                   pulumi.StringArrayOutput                                        `pulumi:"securityGroups"`
	ServerCertificateId              pulumi.StringPtrOutput                                          `pulumi:"serverCertificateId"`
	SourceSecurityGroups             LoadBalancerAttributesSourceSecurityGroupArrayOutput            `pulumi:"sourceSecurityGroups"`
	Subnets                          pulumi.StringArrayOutput                                        `pulumi:"subnets"`
	SubregionNames                   pulumi.StringArrayOutput                                        `pulumi:"subregionNames"`
	Tags                             LoadBalancerAttributesTagArrayOutput                            `pulumi:"tags"`
}

// NewLoadBalancerAttributes registers a new resource with the given unique name, arguments, and options.
func NewLoadBalancerAttributes(ctx *pulumi.Context,
	name string, args *LoadBalancerAttributesArgs, opts ...pulumi.ResourceOption) (*LoadBalancerAttributes, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.LoadBalancerName == nil {
		return nil, errors.New("invalid value for required argument 'LoadBalancerName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource LoadBalancerAttributes
	err = ctx.RegisterPackageResource("outscale:index/loadBalancerAttributes:LoadBalancerAttributes", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLoadBalancerAttributes gets an existing LoadBalancerAttributes resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLoadBalancerAttributes(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LoadBalancerAttributesState, opts ...pulumi.ResourceOption) (*LoadBalancerAttributes, error) {
	var resource LoadBalancerAttributes
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/loadBalancerAttributes:LoadBalancerAttributes", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LoadBalancerAttributes resources.
type loadBalancerAttributesState struct {
	AccessLog                        *LoadBalancerAttributesAccessLog                       `pulumi:"accessLog"`
	ApplicationStickyCookiePolicies  []LoadBalancerAttributesApplicationStickyCookiePolicy  `pulumi:"applicationStickyCookiePolicies"`
	BackendVmIds                     []string                                               `pulumi:"backendVmIds"`
	DnsName                          *string                                                `pulumi:"dnsName"`
	HealthCheck                      *LoadBalancerAttributesHealthCheck                     `pulumi:"healthCheck"`
	Listeners                        []LoadBalancerAttributesListener                       `pulumi:"listeners"`
	LoadBalancerAttributesId         *string                                                `pulumi:"loadBalancerAttributesId"`
	LoadBalancerName                 *string                                                `pulumi:"loadBalancerName"`
	LoadBalancerPort                 *float64                                               `pulumi:"loadBalancerPort"`
	LoadBalancerStickyCookiePolicies []LoadBalancerAttributesLoadBalancerStickyCookiePolicy `pulumi:"loadBalancerStickyCookiePolicies"`
	LoadBalancerType                 *string                                                `pulumi:"loadBalancerType"`
	PolicyNames                      []string                                               `pulumi:"policyNames"`
	RequestId                        *string                                                `pulumi:"requestId"`
	SecurityGroups                   []string                                               `pulumi:"securityGroups"`
	ServerCertificateId              *string                                                `pulumi:"serverCertificateId"`
	SourceSecurityGroups             []LoadBalancerAttributesSourceSecurityGroup            `pulumi:"sourceSecurityGroups"`
	Subnets                          []string                                               `pulumi:"subnets"`
	SubregionNames                   []string                                               `pulumi:"subregionNames"`
	Tags                             []LoadBalancerAttributesTag                            `pulumi:"tags"`
}

type LoadBalancerAttributesState struct {
	AccessLog                        LoadBalancerAttributesAccessLogPtrInput
	ApplicationStickyCookiePolicies  LoadBalancerAttributesApplicationStickyCookiePolicyArrayInput
	BackendVmIds                     pulumi.StringArrayInput
	DnsName                          pulumi.StringPtrInput
	HealthCheck                      LoadBalancerAttributesHealthCheckPtrInput
	Listeners                        LoadBalancerAttributesListenerArrayInput
	LoadBalancerAttributesId         pulumi.StringPtrInput
	LoadBalancerName                 pulumi.StringPtrInput
	LoadBalancerPort                 pulumi.Float64PtrInput
	LoadBalancerStickyCookiePolicies LoadBalancerAttributesLoadBalancerStickyCookiePolicyArrayInput
	LoadBalancerType                 pulumi.StringPtrInput
	PolicyNames                      pulumi.StringArrayInput
	RequestId                        pulumi.StringPtrInput
	SecurityGroups                   pulumi.StringArrayInput
	ServerCertificateId              pulumi.StringPtrInput
	SourceSecurityGroups             LoadBalancerAttributesSourceSecurityGroupArrayInput
	Subnets                          pulumi.StringArrayInput
	SubregionNames                   pulumi.StringArrayInput
	Tags                             LoadBalancerAttributesTagArrayInput
}

func (LoadBalancerAttributesState) ElementType() reflect.Type {
	return reflect.TypeOf((*loadBalancerAttributesState)(nil)).Elem()
}

type loadBalancerAttributesArgs struct {
	AccessLog                *LoadBalancerAttributesAccessLog   `pulumi:"accessLog"`
	HealthCheck              *LoadBalancerAttributesHealthCheck `pulumi:"healthCheck"`
	LoadBalancerAttributesId *string                            `pulumi:"loadBalancerAttributesId"`
	LoadBalancerName         string                             `pulumi:"loadBalancerName"`
	LoadBalancerPort         *float64                           `pulumi:"loadBalancerPort"`
	PolicyNames              []string                           `pulumi:"policyNames"`
	ServerCertificateId      *string                            `pulumi:"serverCertificateId"`
}

// The set of arguments for constructing a LoadBalancerAttributes resource.
type LoadBalancerAttributesArgs struct {
	AccessLog                LoadBalancerAttributesAccessLogPtrInput
	HealthCheck              LoadBalancerAttributesHealthCheckPtrInput
	LoadBalancerAttributesId pulumi.StringPtrInput
	LoadBalancerName         pulumi.StringInput
	LoadBalancerPort         pulumi.Float64PtrInput
	PolicyNames              pulumi.StringArrayInput
	ServerCertificateId      pulumi.StringPtrInput
}

func (LoadBalancerAttributesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*loadBalancerAttributesArgs)(nil)).Elem()
}

type LoadBalancerAttributesInput interface {
	pulumi.Input

	ToLoadBalancerAttributesOutput() LoadBalancerAttributesOutput
	ToLoadBalancerAttributesOutputWithContext(ctx context.Context) LoadBalancerAttributesOutput
}

func (*LoadBalancerAttributes) ElementType() reflect.Type {
	return reflect.TypeOf((**LoadBalancerAttributes)(nil)).Elem()
}

func (i *LoadBalancerAttributes) ToLoadBalancerAttributesOutput() LoadBalancerAttributesOutput {
	return i.ToLoadBalancerAttributesOutputWithContext(context.Background())
}

func (i *LoadBalancerAttributes) ToLoadBalancerAttributesOutputWithContext(ctx context.Context) LoadBalancerAttributesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LoadBalancerAttributesOutput)
}

type LoadBalancerAttributesOutput struct{ *pulumi.OutputState }

func (LoadBalancerAttributesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LoadBalancerAttributes)(nil)).Elem()
}

func (o LoadBalancerAttributesOutput) ToLoadBalancerAttributesOutput() LoadBalancerAttributesOutput {
	return o
}

func (o LoadBalancerAttributesOutput) ToLoadBalancerAttributesOutputWithContext(ctx context.Context) LoadBalancerAttributesOutput {
	return o
}

func (o LoadBalancerAttributesOutput) AccessLog() LoadBalancerAttributesAccessLogPtrOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesAccessLogPtrOutput { return v.AccessLog }).(LoadBalancerAttributesAccessLogPtrOutput)
}

func (o LoadBalancerAttributesOutput) ApplicationStickyCookiePolicies() LoadBalancerAttributesApplicationStickyCookiePolicyArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesApplicationStickyCookiePolicyArrayOutput {
		return v.ApplicationStickyCookiePolicies
	}).(LoadBalancerAttributesApplicationStickyCookiePolicyArrayOutput)
}

func (o LoadBalancerAttributesOutput) BackendVmIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringArrayOutput { return v.BackendVmIds }).(pulumi.StringArrayOutput)
}

func (o LoadBalancerAttributesOutput) DnsName() pulumi.StringOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringOutput { return v.DnsName }).(pulumi.StringOutput)
}

func (o LoadBalancerAttributesOutput) HealthCheck() LoadBalancerAttributesHealthCheckPtrOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesHealthCheckPtrOutput { return v.HealthCheck }).(LoadBalancerAttributesHealthCheckPtrOutput)
}

func (o LoadBalancerAttributesOutput) Listeners() LoadBalancerAttributesListenerArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesListenerArrayOutput { return v.Listeners }).(LoadBalancerAttributesListenerArrayOutput)
}

func (o LoadBalancerAttributesOutput) LoadBalancerAttributesId() pulumi.StringOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringOutput { return v.LoadBalancerAttributesId }).(pulumi.StringOutput)
}

func (o LoadBalancerAttributesOutput) LoadBalancerName() pulumi.StringOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringOutput { return v.LoadBalancerName }).(pulumi.StringOutput)
}

func (o LoadBalancerAttributesOutput) LoadBalancerPort() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.Float64PtrOutput { return v.LoadBalancerPort }).(pulumi.Float64PtrOutput)
}

func (o LoadBalancerAttributesOutput) LoadBalancerStickyCookiePolicies() LoadBalancerAttributesLoadBalancerStickyCookiePolicyArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesLoadBalancerStickyCookiePolicyArrayOutput {
		return v.LoadBalancerStickyCookiePolicies
	}).(LoadBalancerAttributesLoadBalancerStickyCookiePolicyArrayOutput)
}

func (o LoadBalancerAttributesOutput) LoadBalancerType() pulumi.StringOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringOutput { return v.LoadBalancerType }).(pulumi.StringOutput)
}

func (o LoadBalancerAttributesOutput) PolicyNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringArrayOutput { return v.PolicyNames }).(pulumi.StringArrayOutput)
}

func (o LoadBalancerAttributesOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o LoadBalancerAttributesOutput) SecurityGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringArrayOutput { return v.SecurityGroups }).(pulumi.StringArrayOutput)
}

func (o LoadBalancerAttributesOutput) ServerCertificateId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringPtrOutput { return v.ServerCertificateId }).(pulumi.StringPtrOutput)
}

func (o LoadBalancerAttributesOutput) SourceSecurityGroups() LoadBalancerAttributesSourceSecurityGroupArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesSourceSecurityGroupArrayOutput {
		return v.SourceSecurityGroups
	}).(LoadBalancerAttributesSourceSecurityGroupArrayOutput)
}

func (o LoadBalancerAttributesOutput) Subnets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringArrayOutput { return v.Subnets }).(pulumi.StringArrayOutput)
}

func (o LoadBalancerAttributesOutput) SubregionNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) pulumi.StringArrayOutput { return v.SubregionNames }).(pulumi.StringArrayOutput)
}

func (o LoadBalancerAttributesOutput) Tags() LoadBalancerAttributesTagArrayOutput {
	return o.ApplyT(func(v *LoadBalancerAttributes) LoadBalancerAttributesTagArrayOutput { return v.Tags }).(LoadBalancerAttributesTagArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LoadBalancerAttributesInput)(nil)).Elem(), &LoadBalancerAttributes{})
	pulumi.RegisterOutputType(LoadBalancerAttributesOutput{})
}
