// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NatService struct {
	pulumi.CustomResourceState

	NatServiceId         pulumi.StringOutput           `pulumi:"natServiceId"`
	NetId                pulumi.StringOutput           `pulumi:"netId"`
	OutscaleNatServiceId pulumi.StringOutput           `pulumi:"outscaleNatServiceId"`
	PublicIpId           pulumi.StringOutput           `pulumi:"publicIpId"`
	PublicIps            NatServicePublicIpArrayOutput `pulumi:"publicIps"`
	RequestId            pulumi.StringOutput           `pulumi:"requestId"`
	State                pulumi.StringOutput           `pulumi:"state"`
	SubnetId             pulumi.StringOutput           `pulumi:"subnetId"`
	Tags                 NatServiceTagArrayOutput      `pulumi:"tags"`
}

// NewNatService registers a new resource with the given unique name, arguments, and options.
func NewNatService(ctx *pulumi.Context,
	name string, args *NatServiceArgs, opts ...pulumi.ResourceOption) (*NatService, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PublicIpId == nil {
		return nil, errors.New("invalid value for required argument 'PublicIpId'")
	}
	if args.SubnetId == nil {
		return nil, errors.New("invalid value for required argument 'SubnetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NatService
	err = ctx.RegisterPackageResource("outscale:index/natService:NatService", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNatService gets an existing NatService resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNatService(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NatServiceState, opts ...pulumi.ResourceOption) (*NatService, error) {
	var resource NatService
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/natService:NatService", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NatService resources.
type natServiceState struct {
	NatServiceId         *string              `pulumi:"natServiceId"`
	NetId                *string              `pulumi:"netId"`
	OutscaleNatServiceId *string              `pulumi:"outscaleNatServiceId"`
	PublicIpId           *string              `pulumi:"publicIpId"`
	PublicIps            []NatServicePublicIp `pulumi:"publicIps"`
	RequestId            *string              `pulumi:"requestId"`
	State                *string              `pulumi:"state"`
	SubnetId             *string              `pulumi:"subnetId"`
	Tags                 []NatServiceTag      `pulumi:"tags"`
}

type NatServiceState struct {
	NatServiceId         pulumi.StringPtrInput
	NetId                pulumi.StringPtrInput
	OutscaleNatServiceId pulumi.StringPtrInput
	PublicIpId           pulumi.StringPtrInput
	PublicIps            NatServicePublicIpArrayInput
	RequestId            pulumi.StringPtrInput
	State                pulumi.StringPtrInput
	SubnetId             pulumi.StringPtrInput
	Tags                 NatServiceTagArrayInput
}

func (NatServiceState) ElementType() reflect.Type {
	return reflect.TypeOf((*natServiceState)(nil)).Elem()
}

type natServiceArgs struct {
	OutscaleNatServiceId *string         `pulumi:"outscaleNatServiceId"`
	PublicIpId           string          `pulumi:"publicIpId"`
	SubnetId             string          `pulumi:"subnetId"`
	Tags                 []NatServiceTag `pulumi:"tags"`
}

// The set of arguments for constructing a NatService resource.
type NatServiceArgs struct {
	OutscaleNatServiceId pulumi.StringPtrInput
	PublicIpId           pulumi.StringInput
	SubnetId             pulumi.StringInput
	Tags                 NatServiceTagArrayInput
}

func (NatServiceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*natServiceArgs)(nil)).Elem()
}

type NatServiceInput interface {
	pulumi.Input

	ToNatServiceOutput() NatServiceOutput
	ToNatServiceOutputWithContext(ctx context.Context) NatServiceOutput
}

func (*NatService) ElementType() reflect.Type {
	return reflect.TypeOf((**NatService)(nil)).Elem()
}

func (i *NatService) ToNatServiceOutput() NatServiceOutput {
	return i.ToNatServiceOutputWithContext(context.Background())
}

func (i *NatService) ToNatServiceOutputWithContext(ctx context.Context) NatServiceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NatServiceOutput)
}

type NatServiceOutput struct{ *pulumi.OutputState }

func (NatServiceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NatService)(nil)).Elem()
}

func (o NatServiceOutput) ToNatServiceOutput() NatServiceOutput {
	return o
}

func (o NatServiceOutput) ToNatServiceOutputWithContext(ctx context.Context) NatServiceOutput {
	return o
}

func (o NatServiceOutput) NatServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.NatServiceId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) OutscaleNatServiceId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.OutscaleNatServiceId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) PublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.PublicIpId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) PublicIps() NatServicePublicIpArrayOutput {
	return o.ApplyT(func(v *NatService) NatServicePublicIpArrayOutput { return v.PublicIps }).(NatServicePublicIpArrayOutput)
}

func (o NatServiceOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o NatServiceOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NatService) pulumi.StringOutput { return v.SubnetId }).(pulumi.StringOutput)
}

func (o NatServiceOutput) Tags() NatServiceTagArrayOutput {
	return o.ApplyT(func(v *NatService) NatServiceTagArrayOutput { return v.Tags }).(NatServiceTagArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NatServiceInput)(nil)).Elem(), &NatService{})
	pulumi.RegisterOutputType(NatServiceOutput{})
}
