// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetAccessPoint struct {
	pulumi.CustomResourceState

	NetAccessPointId pulumi.StringOutput             `pulumi:"netAccessPointId"`
	NetId            pulumi.StringOutput             `pulumi:"netId"`
	RequestId        pulumi.StringOutput             `pulumi:"requestId"`
	RouteTableIds    pulumi.StringArrayOutput        `pulumi:"routeTableIds"`
	ServiceName      pulumi.StringOutput             `pulumi:"serviceName"`
	State            pulumi.StringOutput             `pulumi:"state"`
	Tags             NetAccessPointTagArrayOutput    `pulumi:"tags"`
	Timeouts         NetAccessPointTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewNetAccessPoint registers a new resource with the given unique name, arguments, and options.
func NewNetAccessPoint(ctx *pulumi.Context,
	name string, args *NetAccessPointArgs, opts ...pulumi.ResourceOption) (*NetAccessPoint, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NetId == nil {
		return nil, errors.New("invalid value for required argument 'NetId'")
	}
	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetAccessPoint
	err = ctx.RegisterPackageResource("outscale:index/netAccessPoint:NetAccessPoint", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetAccessPoint gets an existing NetAccessPoint resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetAccessPoint(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetAccessPointState, opts ...pulumi.ResourceOption) (*NetAccessPoint, error) {
	var resource NetAccessPoint
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/netAccessPoint:NetAccessPoint", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetAccessPoint resources.
type netAccessPointState struct {
	NetAccessPointId *string                 `pulumi:"netAccessPointId"`
	NetId            *string                 `pulumi:"netId"`
	RequestId        *string                 `pulumi:"requestId"`
	RouteTableIds    []string                `pulumi:"routeTableIds"`
	ServiceName      *string                 `pulumi:"serviceName"`
	State            *string                 `pulumi:"state"`
	Tags             []NetAccessPointTag     `pulumi:"tags"`
	Timeouts         *NetAccessPointTimeouts `pulumi:"timeouts"`
}

type NetAccessPointState struct {
	NetAccessPointId pulumi.StringPtrInput
	NetId            pulumi.StringPtrInput
	RequestId        pulumi.StringPtrInput
	RouteTableIds    pulumi.StringArrayInput
	ServiceName      pulumi.StringPtrInput
	State            pulumi.StringPtrInput
	Tags             NetAccessPointTagArrayInput
	Timeouts         NetAccessPointTimeoutsPtrInput
}

func (NetAccessPointState) ElementType() reflect.Type {
	return reflect.TypeOf((*netAccessPointState)(nil)).Elem()
}

type netAccessPointArgs struct {
	NetId         string                  `pulumi:"netId"`
	RouteTableIds []string                `pulumi:"routeTableIds"`
	ServiceName   string                  `pulumi:"serviceName"`
	Tags          []NetAccessPointTag     `pulumi:"tags"`
	Timeouts      *NetAccessPointTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a NetAccessPoint resource.
type NetAccessPointArgs struct {
	NetId         pulumi.StringInput
	RouteTableIds pulumi.StringArrayInput
	ServiceName   pulumi.StringInput
	Tags          NetAccessPointTagArrayInput
	Timeouts      NetAccessPointTimeoutsPtrInput
}

func (NetAccessPointArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netAccessPointArgs)(nil)).Elem()
}

type NetAccessPointInput interface {
	pulumi.Input

	ToNetAccessPointOutput() NetAccessPointOutput
	ToNetAccessPointOutputWithContext(ctx context.Context) NetAccessPointOutput
}

func (*NetAccessPoint) ElementType() reflect.Type {
	return reflect.TypeOf((**NetAccessPoint)(nil)).Elem()
}

func (i *NetAccessPoint) ToNetAccessPointOutput() NetAccessPointOutput {
	return i.ToNetAccessPointOutputWithContext(context.Background())
}

func (i *NetAccessPoint) ToNetAccessPointOutputWithContext(ctx context.Context) NetAccessPointOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetAccessPointOutput)
}

type NetAccessPointOutput struct{ *pulumi.OutputState }

func (NetAccessPointOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetAccessPoint)(nil)).Elem()
}

func (o NetAccessPointOutput) ToNetAccessPointOutput() NetAccessPointOutput {
	return o
}

func (o NetAccessPointOutput) ToNetAccessPointOutputWithContext(ctx context.Context) NetAccessPointOutput {
	return o
}

func (o NetAccessPointOutput) NetAccessPointId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringOutput { return v.NetAccessPointId }).(pulumi.StringOutput)
}

func (o NetAccessPointOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o NetAccessPointOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NetAccessPointOutput) RouteTableIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringArrayOutput { return v.RouteTableIds }).(pulumi.StringArrayOutput)
}

func (o NetAccessPointOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringOutput { return v.ServiceName }).(pulumi.StringOutput)
}

func (o NetAccessPointOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAccessPoint) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o NetAccessPointOutput) Tags() NetAccessPointTagArrayOutput {
	return o.ApplyT(func(v *NetAccessPoint) NetAccessPointTagArrayOutput { return v.Tags }).(NetAccessPointTagArrayOutput)
}

func (o NetAccessPointOutput) Timeouts() NetAccessPointTimeoutsPtrOutput {
	return o.ApplyT(func(v *NetAccessPoint) NetAccessPointTimeoutsPtrOutput { return v.Timeouts }).(NetAccessPointTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetAccessPointInput)(nil)).Elem(), &NetAccessPoint{})
	pulumi.RegisterOutputType(NetAccessPointOutput{})
}
