// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetAttributes struct {
	pulumi.CustomResourceState

	DhcpOptionsSetId pulumi.StringOutput            `pulumi:"dhcpOptionsSetId"`
	IpRange          pulumi.StringOutput            `pulumi:"ipRange"`
	NetId            pulumi.StringOutput            `pulumi:"netId"`
	RequestId        pulumi.StringOutput            `pulumi:"requestId"`
	State            pulumi.StringOutput            `pulumi:"state"`
	Tags             NetAttributesTagArrayOutput    `pulumi:"tags"`
	Tenancy          pulumi.StringOutput            `pulumi:"tenancy"`
	Timeouts         NetAttributesTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewNetAttributes registers a new resource with the given unique name, arguments, and options.
func NewNetAttributes(ctx *pulumi.Context,
	name string, args *NetAttributesArgs, opts ...pulumi.ResourceOption) (*NetAttributes, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DhcpOptionsSetId == nil {
		return nil, errors.New("invalid value for required argument 'DhcpOptionsSetId'")
	}
	if args.NetId == nil {
		return nil, errors.New("invalid value for required argument 'NetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetAttributes
	err = ctx.RegisterPackageResource("outscale:index/netAttributes:NetAttributes", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetAttributes gets an existing NetAttributes resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetAttributes(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetAttributesState, opts ...pulumi.ResourceOption) (*NetAttributes, error) {
	var resource NetAttributes
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/netAttributes:NetAttributes", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetAttributes resources.
type netAttributesState struct {
	DhcpOptionsSetId *string                `pulumi:"dhcpOptionsSetId"`
	IpRange          *string                `pulumi:"ipRange"`
	NetId            *string                `pulumi:"netId"`
	RequestId        *string                `pulumi:"requestId"`
	State            *string                `pulumi:"state"`
	Tags             []NetAttributesTag     `pulumi:"tags"`
	Tenancy          *string                `pulumi:"tenancy"`
	Timeouts         *NetAttributesTimeouts `pulumi:"timeouts"`
}

type NetAttributesState struct {
	DhcpOptionsSetId pulumi.StringPtrInput
	IpRange          pulumi.StringPtrInput
	NetId            pulumi.StringPtrInput
	RequestId        pulumi.StringPtrInput
	State            pulumi.StringPtrInput
	Tags             NetAttributesTagArrayInput
	Tenancy          pulumi.StringPtrInput
	Timeouts         NetAttributesTimeoutsPtrInput
}

func (NetAttributesState) ElementType() reflect.Type {
	return reflect.TypeOf((*netAttributesState)(nil)).Elem()
}

type netAttributesArgs struct {
	DhcpOptionsSetId string                 `pulumi:"dhcpOptionsSetId"`
	NetId            string                 `pulumi:"netId"`
	Timeouts         *NetAttributesTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a NetAttributes resource.
type NetAttributesArgs struct {
	DhcpOptionsSetId pulumi.StringInput
	NetId            pulumi.StringInput
	Timeouts         NetAttributesTimeoutsPtrInput
}

func (NetAttributesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netAttributesArgs)(nil)).Elem()
}

type NetAttributesInput interface {
	pulumi.Input

	ToNetAttributesOutput() NetAttributesOutput
	ToNetAttributesOutputWithContext(ctx context.Context) NetAttributesOutput
}

func (*NetAttributes) ElementType() reflect.Type {
	return reflect.TypeOf((**NetAttributes)(nil)).Elem()
}

func (i *NetAttributes) ToNetAttributesOutput() NetAttributesOutput {
	return i.ToNetAttributesOutputWithContext(context.Background())
}

func (i *NetAttributes) ToNetAttributesOutputWithContext(ctx context.Context) NetAttributesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetAttributesOutput)
}

type NetAttributesOutput struct{ *pulumi.OutputState }

func (NetAttributesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetAttributes)(nil)).Elem()
}

func (o NetAttributesOutput) ToNetAttributesOutput() NetAttributesOutput {
	return o
}

func (o NetAttributesOutput) ToNetAttributesOutputWithContext(ctx context.Context) NetAttributesOutput {
	return o
}

func (o NetAttributesOutput) DhcpOptionsSetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.DhcpOptionsSetId }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) IpRange() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.IpRange }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) Tags() NetAttributesTagArrayOutput {
	return o.ApplyT(func(v *NetAttributes) NetAttributesTagArrayOutput { return v.Tags }).(NetAttributesTagArrayOutput)
}

func (o NetAttributesOutput) Tenancy() pulumi.StringOutput {
	return o.ApplyT(func(v *NetAttributes) pulumi.StringOutput { return v.Tenancy }).(pulumi.StringOutput)
}

func (o NetAttributesOutput) Timeouts() NetAttributesTimeoutsPtrOutput {
	return o.ApplyT(func(v *NetAttributes) NetAttributesTimeoutsPtrOutput { return v.Timeouts }).(NetAttributesTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetAttributesInput)(nil)).Elem(), &NetAttributes{})
	pulumi.RegisterOutputType(NetAttributesOutput{})
}
