// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetPeering struct {
	pulumi.CustomResourceState

	AccepterNetId      pulumi.StringOutput              `pulumi:"accepterNetId"`
	AccepterNets       NetPeeringAccepterNetArrayOutput `pulumi:"accepterNets"`
	AccepterOwnerId    pulumi.StringOutput              `pulumi:"accepterOwnerId"`
	ExpirationDate     pulumi.StringOutput              `pulumi:"expirationDate"`
	NetPeeringId       pulumi.StringOutput              `pulumi:"netPeeringId"`
	RequestId          pulumi.StringOutput              `pulumi:"requestId"`
	SourceNetAccountId pulumi.StringOutput              `pulumi:"sourceNetAccountId"`
	SourceNetId        pulumi.StringOutput              `pulumi:"sourceNetId"`
	SourceNets         NetPeeringSourceNetArrayOutput   `pulumi:"sourceNets"`
	States             NetPeeringStateTypeArrayOutput   `pulumi:"states"`
	Tags               NetPeeringTagArrayOutput         `pulumi:"tags"`
	Timeouts           NetPeeringTimeoutsPtrOutput      `pulumi:"timeouts"`
}

// NewNetPeering registers a new resource with the given unique name, arguments, and options.
func NewNetPeering(ctx *pulumi.Context,
	name string, args *NetPeeringArgs, opts ...pulumi.ResourceOption) (*NetPeering, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AccepterNetId == nil {
		return nil, errors.New("invalid value for required argument 'AccepterNetId'")
	}
	if args.SourceNetId == nil {
		return nil, errors.New("invalid value for required argument 'SourceNetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetPeering
	err = ctx.RegisterPackageResource("outscale:index/netPeering:NetPeering", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetPeering gets an existing NetPeering resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetPeering(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetPeeringState, opts ...pulumi.ResourceOption) (*NetPeering, error) {
	var resource NetPeering
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/netPeering:NetPeering", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetPeering resources.
type netPeeringState struct {
	AccepterNetId      *string                 `pulumi:"accepterNetId"`
	AccepterNets       []NetPeeringAccepterNet `pulumi:"accepterNets"`
	AccepterOwnerId    *string                 `pulumi:"accepterOwnerId"`
	ExpirationDate     *string                 `pulumi:"expirationDate"`
	NetPeeringId       *string                 `pulumi:"netPeeringId"`
	RequestId          *string                 `pulumi:"requestId"`
	SourceNetAccountId *string                 `pulumi:"sourceNetAccountId"`
	SourceNetId        *string                 `pulumi:"sourceNetId"`
	SourceNets         []NetPeeringSourceNet   `pulumi:"sourceNets"`
	States             []NetPeeringStateType   `pulumi:"states"`
	Tags               []NetPeeringTag         `pulumi:"tags"`
	Timeouts           *NetPeeringTimeouts     `pulumi:"timeouts"`
}

type NetPeeringState struct {
	AccepterNetId      pulumi.StringPtrInput
	AccepterNets       NetPeeringAccepterNetArrayInput
	AccepterOwnerId    pulumi.StringPtrInput
	ExpirationDate     pulumi.StringPtrInput
	NetPeeringId       pulumi.StringPtrInput
	RequestId          pulumi.StringPtrInput
	SourceNetAccountId pulumi.StringPtrInput
	SourceNetId        pulumi.StringPtrInput
	SourceNets         NetPeeringSourceNetArrayInput
	States             NetPeeringStateTypeArrayInput
	Tags               NetPeeringTagArrayInput
	Timeouts           NetPeeringTimeoutsPtrInput
}

func (NetPeeringState) ElementType() reflect.Type {
	return reflect.TypeOf((*netPeeringState)(nil)).Elem()
}

type netPeeringArgs struct {
	AccepterNetId      string              `pulumi:"accepterNetId"`
	AccepterOwnerId    *string             `pulumi:"accepterOwnerId"`
	SourceNetAccountId *string             `pulumi:"sourceNetAccountId"`
	SourceNetId        string              `pulumi:"sourceNetId"`
	Tags               []NetPeeringTag     `pulumi:"tags"`
	Timeouts           *NetPeeringTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a NetPeering resource.
type NetPeeringArgs struct {
	AccepterNetId      pulumi.StringInput
	AccepterOwnerId    pulumi.StringPtrInput
	SourceNetAccountId pulumi.StringPtrInput
	SourceNetId        pulumi.StringInput
	Tags               NetPeeringTagArrayInput
	Timeouts           NetPeeringTimeoutsPtrInput
}

func (NetPeeringArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netPeeringArgs)(nil)).Elem()
}

type NetPeeringInput interface {
	pulumi.Input

	ToNetPeeringOutput() NetPeeringOutput
	ToNetPeeringOutputWithContext(ctx context.Context) NetPeeringOutput
}

func (*NetPeering) ElementType() reflect.Type {
	return reflect.TypeOf((**NetPeering)(nil)).Elem()
}

func (i *NetPeering) ToNetPeeringOutput() NetPeeringOutput {
	return i.ToNetPeeringOutputWithContext(context.Background())
}

func (i *NetPeering) ToNetPeeringOutputWithContext(ctx context.Context) NetPeeringOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetPeeringOutput)
}

type NetPeeringOutput struct{ *pulumi.OutputState }

func (NetPeeringOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetPeering)(nil)).Elem()
}

func (o NetPeeringOutput) ToNetPeeringOutput() NetPeeringOutput {
	return o
}

func (o NetPeeringOutput) ToNetPeeringOutputWithContext(ctx context.Context) NetPeeringOutput {
	return o
}

func (o NetPeeringOutput) AccepterNetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.AccepterNetId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) AccepterNets() NetPeeringAccepterNetArrayOutput {
	return o.ApplyT(func(v *NetPeering) NetPeeringAccepterNetArrayOutput { return v.AccepterNets }).(NetPeeringAccepterNetArrayOutput)
}

func (o NetPeeringOutput) AccepterOwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.AccepterOwnerId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) NetPeeringId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.NetPeeringId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) SourceNetAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.SourceNetAccountId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) SourceNetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeering) pulumi.StringOutput { return v.SourceNetId }).(pulumi.StringOutput)
}

func (o NetPeeringOutput) SourceNets() NetPeeringSourceNetArrayOutput {
	return o.ApplyT(func(v *NetPeering) NetPeeringSourceNetArrayOutput { return v.SourceNets }).(NetPeeringSourceNetArrayOutput)
}

func (o NetPeeringOutput) States() NetPeeringStateTypeArrayOutput {
	return o.ApplyT(func(v *NetPeering) NetPeeringStateTypeArrayOutput { return v.States }).(NetPeeringStateTypeArrayOutput)
}

func (o NetPeeringOutput) Tags() NetPeeringTagArrayOutput {
	return o.ApplyT(func(v *NetPeering) NetPeeringTagArrayOutput { return v.Tags }).(NetPeeringTagArrayOutput)
}

func (o NetPeeringOutput) Timeouts() NetPeeringTimeoutsPtrOutput {
	return o.ApplyT(func(v *NetPeering) NetPeeringTimeoutsPtrOutput { return v.Timeouts }).(NetPeeringTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetPeeringInput)(nil)).Elem(), &NetPeering{})
	pulumi.RegisterOutputType(NetPeeringOutput{})
}
