// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetPeeringAcceptation struct {
	pulumi.CustomResourceState

	AccepterNetId      pulumi.StringOutput                         `pulumi:"accepterNetId"`
	AccepterNets       NetPeeringAcceptationAccepterNetArrayOutput `pulumi:"accepterNets"`
	AccepterOwnerId    pulumi.StringOutput                         `pulumi:"accepterOwnerId"`
	ExpirationDate     pulumi.StringOutput                         `pulumi:"expirationDate"`
	NetPeeringId       pulumi.StringOutput                         `pulumi:"netPeeringId"`
	RequestId          pulumi.StringOutput                         `pulumi:"requestId"`
	SourceNetAccountId pulumi.StringOutput                         `pulumi:"sourceNetAccountId"`
	SourceNetId        pulumi.StringOutput                         `pulumi:"sourceNetId"`
	SourceNets         NetPeeringAcceptationSourceNetArrayOutput   `pulumi:"sourceNets"`
	States             NetPeeringAcceptationStateTypeArrayOutput   `pulumi:"states"`
	Tags               NetPeeringAcceptationTagArrayOutput         `pulumi:"tags"`
	Timeouts           NetPeeringAcceptationTimeoutsPtrOutput      `pulumi:"timeouts"`
}

// NewNetPeeringAcceptation registers a new resource with the given unique name, arguments, and options.
func NewNetPeeringAcceptation(ctx *pulumi.Context,
	name string, args *NetPeeringAcceptationArgs, opts ...pulumi.ResourceOption) (*NetPeeringAcceptation, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.NetPeeringId == nil {
		return nil, errors.New("invalid value for required argument 'NetPeeringId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetPeeringAcceptation
	err = ctx.RegisterPackageResource("outscale:index/netPeeringAcceptation:NetPeeringAcceptation", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetPeeringAcceptation gets an existing NetPeeringAcceptation resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetPeeringAcceptation(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetPeeringAcceptationState, opts ...pulumi.ResourceOption) (*NetPeeringAcceptation, error) {
	var resource NetPeeringAcceptation
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/netPeeringAcceptation:NetPeeringAcceptation", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetPeeringAcceptation resources.
type netPeeringAcceptationState struct {
	AccepterNetId      *string                            `pulumi:"accepterNetId"`
	AccepterNets       []NetPeeringAcceptationAccepterNet `pulumi:"accepterNets"`
	AccepterOwnerId    *string                            `pulumi:"accepterOwnerId"`
	ExpirationDate     *string                            `pulumi:"expirationDate"`
	NetPeeringId       *string                            `pulumi:"netPeeringId"`
	RequestId          *string                            `pulumi:"requestId"`
	SourceNetAccountId *string                            `pulumi:"sourceNetAccountId"`
	SourceNetId        *string                            `pulumi:"sourceNetId"`
	SourceNets         []NetPeeringAcceptationSourceNet   `pulumi:"sourceNets"`
	States             []NetPeeringAcceptationStateType   `pulumi:"states"`
	Tags               []NetPeeringAcceptationTag         `pulumi:"tags"`
	Timeouts           *NetPeeringAcceptationTimeouts     `pulumi:"timeouts"`
}

type NetPeeringAcceptationState struct {
	AccepterNetId      pulumi.StringPtrInput
	AccepterNets       NetPeeringAcceptationAccepterNetArrayInput
	AccepterOwnerId    pulumi.StringPtrInput
	ExpirationDate     pulumi.StringPtrInput
	NetPeeringId       pulumi.StringPtrInput
	RequestId          pulumi.StringPtrInput
	SourceNetAccountId pulumi.StringPtrInput
	SourceNetId        pulumi.StringPtrInput
	SourceNets         NetPeeringAcceptationSourceNetArrayInput
	States             NetPeeringAcceptationStateTypeArrayInput
	Tags               NetPeeringAcceptationTagArrayInput
	Timeouts           NetPeeringAcceptationTimeoutsPtrInput
}

func (NetPeeringAcceptationState) ElementType() reflect.Type {
	return reflect.TypeOf((*netPeeringAcceptationState)(nil)).Elem()
}

type netPeeringAcceptationArgs struct {
	NetPeeringId string                         `pulumi:"netPeeringId"`
	Timeouts     *NetPeeringAcceptationTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a NetPeeringAcceptation resource.
type NetPeeringAcceptationArgs struct {
	NetPeeringId pulumi.StringInput
	Timeouts     NetPeeringAcceptationTimeoutsPtrInput
}

func (NetPeeringAcceptationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*netPeeringAcceptationArgs)(nil)).Elem()
}

type NetPeeringAcceptationInput interface {
	pulumi.Input

	ToNetPeeringAcceptationOutput() NetPeeringAcceptationOutput
	ToNetPeeringAcceptationOutputWithContext(ctx context.Context) NetPeeringAcceptationOutput
}

func (*NetPeeringAcceptation) ElementType() reflect.Type {
	return reflect.TypeOf((**NetPeeringAcceptation)(nil)).Elem()
}

func (i *NetPeeringAcceptation) ToNetPeeringAcceptationOutput() NetPeeringAcceptationOutput {
	return i.ToNetPeeringAcceptationOutputWithContext(context.Background())
}

func (i *NetPeeringAcceptation) ToNetPeeringAcceptationOutputWithContext(ctx context.Context) NetPeeringAcceptationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetPeeringAcceptationOutput)
}

type NetPeeringAcceptationOutput struct{ *pulumi.OutputState }

func (NetPeeringAcceptationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetPeeringAcceptation)(nil)).Elem()
}

func (o NetPeeringAcceptationOutput) ToNetPeeringAcceptationOutput() NetPeeringAcceptationOutput {
	return o
}

func (o NetPeeringAcceptationOutput) ToNetPeeringAcceptationOutputWithContext(ctx context.Context) NetPeeringAcceptationOutput {
	return o
}

func (o NetPeeringAcceptationOutput) AccepterNetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.AccepterNetId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) AccepterNets() NetPeeringAcceptationAccepterNetArrayOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) NetPeeringAcceptationAccepterNetArrayOutput { return v.AccepterNets }).(NetPeeringAcceptationAccepterNetArrayOutput)
}

func (o NetPeeringAcceptationOutput) AccepterOwnerId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.AccepterOwnerId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) NetPeeringId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.NetPeeringId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) SourceNetAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.SourceNetAccountId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) SourceNetId() pulumi.StringOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) pulumi.StringOutput { return v.SourceNetId }).(pulumi.StringOutput)
}

func (o NetPeeringAcceptationOutput) SourceNets() NetPeeringAcceptationSourceNetArrayOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) NetPeeringAcceptationSourceNetArrayOutput { return v.SourceNets }).(NetPeeringAcceptationSourceNetArrayOutput)
}

func (o NetPeeringAcceptationOutput) States() NetPeeringAcceptationStateTypeArrayOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) NetPeeringAcceptationStateTypeArrayOutput { return v.States }).(NetPeeringAcceptationStateTypeArrayOutput)
}

func (o NetPeeringAcceptationOutput) Tags() NetPeeringAcceptationTagArrayOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) NetPeeringAcceptationTagArrayOutput { return v.Tags }).(NetPeeringAcceptationTagArrayOutput)
}

func (o NetPeeringAcceptationOutput) Timeouts() NetPeeringAcceptationTimeoutsPtrOutput {
	return o.ApplyT(func(v *NetPeeringAcceptation) NetPeeringAcceptationTimeoutsPtrOutput { return v.Timeouts }).(NetPeeringAcceptationTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetPeeringAcceptationInput)(nil)).Elem(), &NetPeeringAcceptation{})
	pulumi.RegisterOutputType(NetPeeringAcceptationOutput{})
}
