// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Nic struct {
	pulumi.CustomResourceState

	AccountId           pulumi.StringOutput         `pulumi:"accountId"`
	Description         pulumi.StringOutput         `pulumi:"description"`
	IsSourceDestChecked pulumi.BoolOutput           `pulumi:"isSourceDestChecked"`
	LinkNics            NicLinkNicArrayOutput       `pulumi:"linkNics"`
	LinkPublicIps       NicLinkPublicIpArrayOutput  `pulumi:"linkPublicIps"`
	MacAddress          pulumi.StringOutput         `pulumi:"macAddress"`
	NetId               pulumi.StringOutput         `pulumi:"netId"`
	NicId               pulumi.StringOutput         `pulumi:"nicId"`
	OutscaleNicId       pulumi.StringOutput         `pulumi:"outscaleNicId"`
	PrivateDnsName      pulumi.StringOutput         `pulumi:"privateDnsName"`
	PrivateIp           pulumi.StringOutput         `pulumi:"privateIp"`
	PrivateIps          NicPrivateIpTypeArrayOutput `pulumi:"privateIps"`
	RequestId           pulumi.StringOutput         `pulumi:"requestId"`
	RequesterManaged    pulumi.BoolOutput           `pulumi:"requesterManaged"`
	SecurityGroupIds    pulumi.StringArrayOutput    `pulumi:"securityGroupIds"`
	SecurityGroups      NicSecurityGroupArrayOutput `pulumi:"securityGroups"`
	State               pulumi.StringOutput         `pulumi:"state"`
	SubnetId            pulumi.StringOutput         `pulumi:"subnetId"`
	SubregionName       pulumi.StringOutput         `pulumi:"subregionName"`
	Tags                NicTagArrayOutput           `pulumi:"tags"`
	Timeouts            NicTimeoutsPtrOutput        `pulumi:"timeouts"`
}

// NewNic registers a new resource with the given unique name, arguments, and options.
func NewNic(ctx *pulumi.Context,
	name string, args *NicArgs, opts ...pulumi.ResourceOption) (*Nic, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SubnetId == nil {
		return nil, errors.New("invalid value for required argument 'SubnetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Nic
	err = ctx.RegisterPackageResource("outscale:index/nic:Nic", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNic gets an existing Nic resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNic(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NicState, opts ...pulumi.ResourceOption) (*Nic, error) {
	var resource Nic
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/nic:Nic", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Nic resources.
type nicState struct {
	AccountId           *string            `pulumi:"accountId"`
	Description         *string            `pulumi:"description"`
	IsSourceDestChecked *bool              `pulumi:"isSourceDestChecked"`
	LinkNics            []NicLinkNic       `pulumi:"linkNics"`
	LinkPublicIps       []NicLinkPublicIp  `pulumi:"linkPublicIps"`
	MacAddress          *string            `pulumi:"macAddress"`
	NetId               *string            `pulumi:"netId"`
	NicId               *string            `pulumi:"nicId"`
	OutscaleNicId       *string            `pulumi:"outscaleNicId"`
	PrivateDnsName      *string            `pulumi:"privateDnsName"`
	PrivateIp           *string            `pulumi:"privateIp"`
	PrivateIps          []NicPrivateIpType `pulumi:"privateIps"`
	RequestId           *string            `pulumi:"requestId"`
	RequesterManaged    *bool              `pulumi:"requesterManaged"`
	SecurityGroupIds    []string           `pulumi:"securityGroupIds"`
	SecurityGroups      []NicSecurityGroup `pulumi:"securityGroups"`
	State               *string            `pulumi:"state"`
	SubnetId            *string            `pulumi:"subnetId"`
	SubregionName       *string            `pulumi:"subregionName"`
	Tags                []NicTag           `pulumi:"tags"`
	Timeouts            *NicTimeouts       `pulumi:"timeouts"`
}

type NicState struct {
	AccountId           pulumi.StringPtrInput
	Description         pulumi.StringPtrInput
	IsSourceDestChecked pulumi.BoolPtrInput
	LinkNics            NicLinkNicArrayInput
	LinkPublicIps       NicLinkPublicIpArrayInput
	MacAddress          pulumi.StringPtrInput
	NetId               pulumi.StringPtrInput
	NicId               pulumi.StringPtrInput
	OutscaleNicId       pulumi.StringPtrInput
	PrivateDnsName      pulumi.StringPtrInput
	PrivateIp           pulumi.StringPtrInput
	PrivateIps          NicPrivateIpTypeArrayInput
	RequestId           pulumi.StringPtrInput
	RequesterManaged    pulumi.BoolPtrInput
	SecurityGroupIds    pulumi.StringArrayInput
	SecurityGroups      NicSecurityGroupArrayInput
	State               pulumi.StringPtrInput
	SubnetId            pulumi.StringPtrInput
	SubregionName       pulumi.StringPtrInput
	Tags                NicTagArrayInput
	Timeouts            NicTimeoutsPtrInput
}

func (NicState) ElementType() reflect.Type {
	return reflect.TypeOf((*nicState)(nil)).Elem()
}

type nicArgs struct {
	Description      *string            `pulumi:"description"`
	OutscaleNicId    *string            `pulumi:"outscaleNicId"`
	PrivateIp        *string            `pulumi:"privateIp"`
	PrivateIps       []NicPrivateIpType `pulumi:"privateIps"`
	SecurityGroupIds []string           `pulumi:"securityGroupIds"`
	SubnetId         string             `pulumi:"subnetId"`
	Tags             []NicTag           `pulumi:"tags"`
	Timeouts         *NicTimeouts       `pulumi:"timeouts"`
}

// The set of arguments for constructing a Nic resource.
type NicArgs struct {
	Description      pulumi.StringPtrInput
	OutscaleNicId    pulumi.StringPtrInput
	PrivateIp        pulumi.StringPtrInput
	PrivateIps       NicPrivateIpTypeArrayInput
	SecurityGroupIds pulumi.StringArrayInput
	SubnetId         pulumi.StringInput
	Tags             NicTagArrayInput
	Timeouts         NicTimeoutsPtrInput
}

func (NicArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nicArgs)(nil)).Elem()
}

type NicInput interface {
	pulumi.Input

	ToNicOutput() NicOutput
	ToNicOutputWithContext(ctx context.Context) NicOutput
}

func (*Nic) ElementType() reflect.Type {
	return reflect.TypeOf((**Nic)(nil)).Elem()
}

func (i *Nic) ToNicOutput() NicOutput {
	return i.ToNicOutputWithContext(context.Background())
}

func (i *Nic) ToNicOutputWithContext(ctx context.Context) NicOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NicOutput)
}

type NicOutput struct{ *pulumi.OutputState }

func (NicOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Nic)(nil)).Elem()
}

func (o NicOutput) ToNicOutput() NicOutput {
	return o
}

func (o NicOutput) ToNicOutputWithContext(ctx context.Context) NicOutput {
	return o
}

func (o NicOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

func (o NicOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NicOutput) IsSourceDestChecked() pulumi.BoolOutput {
	return o.ApplyT(func(v *Nic) pulumi.BoolOutput { return v.IsSourceDestChecked }).(pulumi.BoolOutput)
}

func (o NicOutput) LinkNics() NicLinkNicArrayOutput {
	return o.ApplyT(func(v *Nic) NicLinkNicArrayOutput { return v.LinkNics }).(NicLinkNicArrayOutput)
}

func (o NicOutput) LinkPublicIps() NicLinkPublicIpArrayOutput {
	return o.ApplyT(func(v *Nic) NicLinkPublicIpArrayOutput { return v.LinkPublicIps }).(NicLinkPublicIpArrayOutput)
}

func (o NicOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

func (o NicOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o NicOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.NicId }).(pulumi.StringOutput)
}

func (o NicOutput) OutscaleNicId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.OutscaleNicId }).(pulumi.StringOutput)
}

func (o NicOutput) PrivateDnsName() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.PrivateDnsName }).(pulumi.StringOutput)
}

func (o NicOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o NicOutput) PrivateIps() NicPrivateIpTypeArrayOutput {
	return o.ApplyT(func(v *Nic) NicPrivateIpTypeArrayOutput { return v.PrivateIps }).(NicPrivateIpTypeArrayOutput)
}

func (o NicOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NicOutput) RequesterManaged() pulumi.BoolOutput {
	return o.ApplyT(func(v *Nic) pulumi.BoolOutput { return v.RequesterManaged }).(pulumi.BoolOutput)
}

func (o NicOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

func (o NicOutput) SecurityGroups() NicSecurityGroupArrayOutput {
	return o.ApplyT(func(v *Nic) NicSecurityGroupArrayOutput { return v.SecurityGroups }).(NicSecurityGroupArrayOutput)
}

func (o NicOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o NicOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.SubnetId }).(pulumi.StringOutput)
}

func (o NicOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v *Nic) pulumi.StringOutput { return v.SubregionName }).(pulumi.StringOutput)
}

func (o NicOutput) Tags() NicTagArrayOutput {
	return o.ApplyT(func(v *Nic) NicTagArrayOutput { return v.Tags }).(NicTagArrayOutput)
}

func (o NicOutput) Timeouts() NicTimeoutsPtrOutput {
	return o.ApplyT(func(v *Nic) NicTimeoutsPtrOutput { return v.Timeouts }).(NicTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NicInput)(nil)).Elem(), &Nic{})
	pulumi.RegisterOutputType(NicOutput{})
}
