// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NicLink struct {
	pulumi.CustomResourceState

	DeleteOnVmDeletion pulumi.BoolOutput    `pulumi:"deleteOnVmDeletion"`
	DeviceNumber       pulumi.Float64Output `pulumi:"deviceNumber"`
	LinkNicId          pulumi.StringOutput  `pulumi:"linkNicId"`
	NicId              pulumi.StringOutput  `pulumi:"nicId"`
	NicLinkId          pulumi.StringOutput  `pulumi:"nicLinkId"`
	RequestId          pulumi.StringOutput  `pulumi:"requestId"`
	State              pulumi.StringOutput  `pulumi:"state"`
	VmAccountId        pulumi.StringOutput  `pulumi:"vmAccountId"`
	VmId               pulumi.StringOutput  `pulumi:"vmId"`
}

// NewNicLink registers a new resource with the given unique name, arguments, and options.
func NewNicLink(ctx *pulumi.Context,
	name string, args *NicLinkArgs, opts ...pulumi.ResourceOption) (*NicLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DeviceNumber == nil {
		return nil, errors.New("invalid value for required argument 'DeviceNumber'")
	}
	if args.NicId == nil {
		return nil, errors.New("invalid value for required argument 'NicId'")
	}
	if args.VmId == nil {
		return nil, errors.New("invalid value for required argument 'VmId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NicLink
	err = ctx.RegisterPackageResource("outscale:index/nicLink:NicLink", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNicLink gets an existing NicLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNicLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NicLinkState, opts ...pulumi.ResourceOption) (*NicLink, error) {
	var resource NicLink
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/nicLink:NicLink", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NicLink resources.
type nicLinkState struct {
	DeleteOnVmDeletion *bool    `pulumi:"deleteOnVmDeletion"`
	DeviceNumber       *float64 `pulumi:"deviceNumber"`
	LinkNicId          *string  `pulumi:"linkNicId"`
	NicId              *string  `pulumi:"nicId"`
	NicLinkId          *string  `pulumi:"nicLinkId"`
	RequestId          *string  `pulumi:"requestId"`
	State              *string  `pulumi:"state"`
	VmAccountId        *string  `pulumi:"vmAccountId"`
	VmId               *string  `pulumi:"vmId"`
}

type NicLinkState struct {
	DeleteOnVmDeletion pulumi.BoolPtrInput
	DeviceNumber       pulumi.Float64PtrInput
	LinkNicId          pulumi.StringPtrInput
	NicId              pulumi.StringPtrInput
	NicLinkId          pulumi.StringPtrInput
	RequestId          pulumi.StringPtrInput
	State              pulumi.StringPtrInput
	VmAccountId        pulumi.StringPtrInput
	VmId               pulumi.StringPtrInput
}

func (NicLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*nicLinkState)(nil)).Elem()
}

type nicLinkArgs struct {
	DeviceNumber float64 `pulumi:"deviceNumber"`
	NicId        string  `pulumi:"nicId"`
	NicLinkId    *string `pulumi:"nicLinkId"`
	VmId         string  `pulumi:"vmId"`
}

// The set of arguments for constructing a NicLink resource.
type NicLinkArgs struct {
	DeviceNumber pulumi.Float64Input
	NicId        pulumi.StringInput
	NicLinkId    pulumi.StringPtrInput
	VmId         pulumi.StringInput
}

func (NicLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*nicLinkArgs)(nil)).Elem()
}

type NicLinkInput interface {
	pulumi.Input

	ToNicLinkOutput() NicLinkOutput
	ToNicLinkOutputWithContext(ctx context.Context) NicLinkOutput
}

func (*NicLink) ElementType() reflect.Type {
	return reflect.TypeOf((**NicLink)(nil)).Elem()
}

func (i *NicLink) ToNicLinkOutput() NicLinkOutput {
	return i.ToNicLinkOutputWithContext(context.Background())
}

func (i *NicLink) ToNicLinkOutputWithContext(ctx context.Context) NicLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NicLinkOutput)
}

type NicLinkOutput struct{ *pulumi.OutputState }

func (NicLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NicLink)(nil)).Elem()
}

func (o NicLinkOutput) ToNicLinkOutput() NicLinkOutput {
	return o
}

func (o NicLinkOutput) ToNicLinkOutputWithContext(ctx context.Context) NicLinkOutput {
	return o
}

func (o NicLinkOutput) DeleteOnVmDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *NicLink) pulumi.BoolOutput { return v.DeleteOnVmDeletion }).(pulumi.BoolOutput)
}

func (o NicLinkOutput) DeviceNumber() pulumi.Float64Output {
	return o.ApplyT(func(v *NicLink) pulumi.Float64Output { return v.DeviceNumber }).(pulumi.Float64Output)
}

func (o NicLinkOutput) LinkNicId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.LinkNicId }).(pulumi.StringOutput)
}

func (o NicLinkOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.NicId }).(pulumi.StringOutput)
}

func (o NicLinkOutput) NicLinkId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.NicLinkId }).(pulumi.StringOutput)
}

func (o NicLinkOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o NicLinkOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o NicLinkOutput) VmAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.VmAccountId }).(pulumi.StringOutput)
}

func (o NicLinkOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *NicLink) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NicLinkInput)(nil)).Elem(), &NicLink{})
	pulumi.RegisterOutputType(NicLinkOutput{})
}
