// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PublicIpLink struct {
	pulumi.CustomResourceState

	AllowRelink    pulumi.BoolPtrOutput          `pulumi:"allowRelink"`
	LinkPublicIpId pulumi.StringOutput           `pulumi:"linkPublicIpId"`
	NicAccountId   pulumi.StringOutput           `pulumi:"nicAccountId"`
	NicId          pulumi.StringOutput           `pulumi:"nicId"`
	PrivateIp      pulumi.StringOutput           `pulumi:"privateIp"`
	PublicIp       pulumi.StringOutput           `pulumi:"publicIp"`
	PublicIpId     pulumi.StringOutput           `pulumi:"publicIpId"`
	PublicIpLinkId pulumi.StringOutput           `pulumi:"publicIpLinkId"`
	RequestId      pulumi.StringOutput           `pulumi:"requestId"`
	Tags           PublicIpLinkTagArrayOutput    `pulumi:"tags"`
	Timeouts       PublicIpLinkTimeoutsPtrOutput `pulumi:"timeouts"`
	VmId           pulumi.StringOutput           `pulumi:"vmId"`
}

// NewPublicIpLink registers a new resource with the given unique name, arguments, and options.
func NewPublicIpLink(ctx *pulumi.Context,
	name string, args *PublicIpLinkArgs, opts ...pulumi.ResourceOption) (*PublicIpLink, error) {
	if args == nil {
		args = &PublicIpLinkArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource PublicIpLink
	err = ctx.RegisterPackageResource("outscale:index/publicIpLink:PublicIpLink", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPublicIpLink gets an existing PublicIpLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPublicIpLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PublicIpLinkState, opts ...pulumi.ResourceOption) (*PublicIpLink, error) {
	var resource PublicIpLink
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/publicIpLink:PublicIpLink", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PublicIpLink resources.
type publicIpLinkState struct {
	AllowRelink    *bool                 `pulumi:"allowRelink"`
	LinkPublicIpId *string               `pulumi:"linkPublicIpId"`
	NicAccountId   *string               `pulumi:"nicAccountId"`
	NicId          *string               `pulumi:"nicId"`
	PrivateIp      *string               `pulumi:"privateIp"`
	PublicIp       *string               `pulumi:"publicIp"`
	PublicIpId     *string               `pulumi:"publicIpId"`
	PublicIpLinkId *string               `pulumi:"publicIpLinkId"`
	RequestId      *string               `pulumi:"requestId"`
	Tags           []PublicIpLinkTag     `pulumi:"tags"`
	Timeouts       *PublicIpLinkTimeouts `pulumi:"timeouts"`
	VmId           *string               `pulumi:"vmId"`
}

type PublicIpLinkState struct {
	AllowRelink    pulumi.BoolPtrInput
	LinkPublicIpId pulumi.StringPtrInput
	NicAccountId   pulumi.StringPtrInput
	NicId          pulumi.StringPtrInput
	PrivateIp      pulumi.StringPtrInput
	PublicIp       pulumi.StringPtrInput
	PublicIpId     pulumi.StringPtrInput
	PublicIpLinkId pulumi.StringPtrInput
	RequestId      pulumi.StringPtrInput
	Tags           PublicIpLinkTagArrayInput
	Timeouts       PublicIpLinkTimeoutsPtrInput
	VmId           pulumi.StringPtrInput
}

func (PublicIpLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*publicIpLinkState)(nil)).Elem()
}

type publicIpLinkArgs struct {
	AllowRelink    *bool                 `pulumi:"allowRelink"`
	NicId          *string               `pulumi:"nicId"`
	PrivateIp      *string               `pulumi:"privateIp"`
	PublicIp       *string               `pulumi:"publicIp"`
	PublicIpId     *string               `pulumi:"publicIpId"`
	PublicIpLinkId *string               `pulumi:"publicIpLinkId"`
	Timeouts       *PublicIpLinkTimeouts `pulumi:"timeouts"`
	VmId           *string               `pulumi:"vmId"`
}

// The set of arguments for constructing a PublicIpLink resource.
type PublicIpLinkArgs struct {
	AllowRelink    pulumi.BoolPtrInput
	NicId          pulumi.StringPtrInput
	PrivateIp      pulumi.StringPtrInput
	PublicIp       pulumi.StringPtrInput
	PublicIpId     pulumi.StringPtrInput
	PublicIpLinkId pulumi.StringPtrInput
	Timeouts       PublicIpLinkTimeoutsPtrInput
	VmId           pulumi.StringPtrInput
}

func (PublicIpLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*publicIpLinkArgs)(nil)).Elem()
}

type PublicIpLinkInput interface {
	pulumi.Input

	ToPublicIpLinkOutput() PublicIpLinkOutput
	ToPublicIpLinkOutputWithContext(ctx context.Context) PublicIpLinkOutput
}

func (*PublicIpLink) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicIpLink)(nil)).Elem()
}

func (i *PublicIpLink) ToPublicIpLinkOutput() PublicIpLinkOutput {
	return i.ToPublicIpLinkOutputWithContext(context.Background())
}

func (i *PublicIpLink) ToPublicIpLinkOutputWithContext(ctx context.Context) PublicIpLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PublicIpLinkOutput)
}

type PublicIpLinkOutput struct{ *pulumi.OutputState }

func (PublicIpLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicIpLink)(nil)).Elem()
}

func (o PublicIpLinkOutput) ToPublicIpLinkOutput() PublicIpLinkOutput {
	return o
}

func (o PublicIpLinkOutput) ToPublicIpLinkOutputWithContext(ctx context.Context) PublicIpLinkOutput {
	return o
}

func (o PublicIpLinkOutput) AllowRelink() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.BoolPtrOutput { return v.AllowRelink }).(pulumi.BoolPtrOutput)
}

func (o PublicIpLinkOutput) LinkPublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.LinkPublicIpId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) NicAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.NicAccountId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.NicId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.PublicIp }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) PublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.PublicIpId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) PublicIpLinkId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.PublicIpLinkId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o PublicIpLinkOutput) Tags() PublicIpLinkTagArrayOutput {
	return o.ApplyT(func(v *PublicIpLink) PublicIpLinkTagArrayOutput { return v.Tags }).(PublicIpLinkTagArrayOutput)
}

func (o PublicIpLinkOutput) Timeouts() PublicIpLinkTimeoutsPtrOutput {
	return o.ApplyT(func(v *PublicIpLink) PublicIpLinkTimeoutsPtrOutput { return v.Timeouts }).(PublicIpLinkTimeoutsPtrOutput)
}

func (o PublicIpLinkOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIpLink) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PublicIpLinkInput)(nil)).Elem(), &PublicIpLink{})
	pulumi.RegisterOutputType(PublicIpLinkOutput{})
}
