// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PublicIp struct {
	pulumi.CustomResourceState

	LinkPublicIpId     pulumi.StringOutput       `pulumi:"linkPublicIpId"`
	NicAccountId       pulumi.StringOutput       `pulumi:"nicAccountId"`
	NicId              pulumi.StringOutput       `pulumi:"nicId"`
	OutscalePublicIpId pulumi.StringOutput       `pulumi:"outscalePublicIpId"`
	PrivateIp          pulumi.StringOutput       `pulumi:"privateIp"`
	PublicIp           pulumi.StringOutput       `pulumi:"publicIp"`
	PublicIpId         pulumi.StringOutput       `pulumi:"publicIpId"`
	RequestId          pulumi.StringOutput       `pulumi:"requestId"`
	Tags               PublicIpTagArrayOutput    `pulumi:"tags"`
	Timeouts           PublicIpTimeoutsPtrOutput `pulumi:"timeouts"`
	VmId               pulumi.StringOutput       `pulumi:"vmId"`
}

// NewPublicIp registers a new resource with the given unique name, arguments, and options.
func NewPublicIp(ctx *pulumi.Context,
	name string, args *PublicIpArgs, opts ...pulumi.ResourceOption) (*PublicIp, error) {
	if args == nil {
		args = &PublicIpArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource PublicIp
	err = ctx.RegisterPackageResource("outscale:index/publicIp:PublicIp", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPublicIp gets an existing PublicIp resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPublicIp(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PublicIpState, opts ...pulumi.ResourceOption) (*PublicIp, error) {
	var resource PublicIp
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/publicIp:PublicIp", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PublicIp resources.
type publicIpState struct {
	LinkPublicIpId     *string           `pulumi:"linkPublicIpId"`
	NicAccountId       *string           `pulumi:"nicAccountId"`
	NicId              *string           `pulumi:"nicId"`
	OutscalePublicIpId *string           `pulumi:"outscalePublicIpId"`
	PrivateIp          *string           `pulumi:"privateIp"`
	PublicIp           *string           `pulumi:"publicIp"`
	PublicIpId         *string           `pulumi:"publicIpId"`
	RequestId          *string           `pulumi:"requestId"`
	Tags               []PublicIpTag     `pulumi:"tags"`
	Timeouts           *PublicIpTimeouts `pulumi:"timeouts"`
	VmId               *string           `pulumi:"vmId"`
}

type PublicIpState struct {
	LinkPublicIpId     pulumi.StringPtrInput
	NicAccountId       pulumi.StringPtrInput
	NicId              pulumi.StringPtrInput
	OutscalePublicIpId pulumi.StringPtrInput
	PrivateIp          pulumi.StringPtrInput
	PublicIp           pulumi.StringPtrInput
	PublicIpId         pulumi.StringPtrInput
	RequestId          pulumi.StringPtrInput
	Tags               PublicIpTagArrayInput
	Timeouts           PublicIpTimeoutsPtrInput
	VmId               pulumi.StringPtrInput
}

func (PublicIpState) ElementType() reflect.Type {
	return reflect.TypeOf((*publicIpState)(nil)).Elem()
}

type publicIpArgs struct {
	OutscalePublicIpId *string           `pulumi:"outscalePublicIpId"`
	Tags               []PublicIpTag     `pulumi:"tags"`
	Timeouts           *PublicIpTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a PublicIp resource.
type PublicIpArgs struct {
	OutscalePublicIpId pulumi.StringPtrInput
	Tags               PublicIpTagArrayInput
	Timeouts           PublicIpTimeoutsPtrInput
}

func (PublicIpArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*publicIpArgs)(nil)).Elem()
}

type PublicIpInput interface {
	pulumi.Input

	ToPublicIpOutput() PublicIpOutput
	ToPublicIpOutputWithContext(ctx context.Context) PublicIpOutput
}

func (*PublicIp) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicIp)(nil)).Elem()
}

func (i *PublicIp) ToPublicIpOutput() PublicIpOutput {
	return i.ToPublicIpOutputWithContext(context.Background())
}

func (i *PublicIp) ToPublicIpOutputWithContext(ctx context.Context) PublicIpOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PublicIpOutput)
}

type PublicIpOutput struct{ *pulumi.OutputState }

func (PublicIpOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PublicIp)(nil)).Elem()
}

func (o PublicIpOutput) ToPublicIpOutput() PublicIpOutput {
	return o
}

func (o PublicIpOutput) ToPublicIpOutputWithContext(ctx context.Context) PublicIpOutput {
	return o
}

func (o PublicIpOutput) LinkPublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.LinkPublicIpId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) NicAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.NicAccountId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.NicId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) OutscalePublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.OutscalePublicIpId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o PublicIpOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.PublicIp }).(pulumi.StringOutput)
}

func (o PublicIpOutput) PublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.PublicIpId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o PublicIpOutput) Tags() PublicIpTagArrayOutput {
	return o.ApplyT(func(v *PublicIp) PublicIpTagArrayOutput { return v.Tags }).(PublicIpTagArrayOutput)
}

func (o PublicIpOutput) Timeouts() PublicIpTimeoutsPtrOutput {
	return o.ApplyT(func(v *PublicIp) PublicIpTimeoutsPtrOutput { return v.Timeouts }).(PublicIpTimeoutsPtrOutput)
}

func (o PublicIpOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *PublicIp) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PublicIpInput)(nil)).Elem(), &PublicIp{})
	pulumi.RegisterOutputType(PublicIpOutput{})
}
