// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SecurityGroup struct {
	pulumi.CustomResourceState

	AccountId                 pulumi.StringOutput                  `pulumi:"accountId"`
	Description               pulumi.StringOutput                  `pulumi:"description"`
	InboundRules              SecurityGroupInboundRuleArrayOutput  `pulumi:"inboundRules"`
	NetId                     pulumi.StringOutput                  `pulumi:"netId"`
	OutboundRules             SecurityGroupOutboundRuleArrayOutput `pulumi:"outboundRules"`
	RemoveDefaultOutboundRule pulumi.BoolOutput                    `pulumi:"removeDefaultOutboundRule"`
	RequestId                 pulumi.StringOutput                  `pulumi:"requestId"`
	SecurityGroupId           pulumi.StringOutput                  `pulumi:"securityGroupId"`
	SecurityGroupName         pulumi.StringOutput                  `pulumi:"securityGroupName"`
	Tags                      SecurityGroupTagArrayOutput          `pulumi:"tags"`
	Timeouts                  SecurityGroupTimeoutsPtrOutput       `pulumi:"timeouts"`
}

// NewSecurityGroup registers a new resource with the given unique name, arguments, and options.
func NewSecurityGroup(ctx *pulumi.Context,
	name string, args *SecurityGroupArgs, opts ...pulumi.ResourceOption) (*SecurityGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.SecurityGroupName == nil {
		return nil, errors.New("invalid value for required argument 'SecurityGroupName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SecurityGroup
	err = ctx.RegisterPackageResource("outscale:index/securityGroup:SecurityGroup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecurityGroup gets an existing SecurityGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecurityGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecurityGroupState, opts ...pulumi.ResourceOption) (*SecurityGroup, error) {
	var resource SecurityGroup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/securityGroup:SecurityGroup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecurityGroup resources.
type securityGroupState struct {
	AccountId                 *string                     `pulumi:"accountId"`
	Description               *string                     `pulumi:"description"`
	InboundRules              []SecurityGroupInboundRule  `pulumi:"inboundRules"`
	NetId                     *string                     `pulumi:"netId"`
	OutboundRules             []SecurityGroupOutboundRule `pulumi:"outboundRules"`
	RemoveDefaultOutboundRule *bool                       `pulumi:"removeDefaultOutboundRule"`
	RequestId                 *string                     `pulumi:"requestId"`
	SecurityGroupId           *string                     `pulumi:"securityGroupId"`
	SecurityGroupName         *string                     `pulumi:"securityGroupName"`
	Tags                      []SecurityGroupTag          `pulumi:"tags"`
	Timeouts                  *SecurityGroupTimeouts      `pulumi:"timeouts"`
}

type SecurityGroupState struct {
	AccountId                 pulumi.StringPtrInput
	Description               pulumi.StringPtrInput
	InboundRules              SecurityGroupInboundRuleArrayInput
	NetId                     pulumi.StringPtrInput
	OutboundRules             SecurityGroupOutboundRuleArrayInput
	RemoveDefaultOutboundRule pulumi.BoolPtrInput
	RequestId                 pulumi.StringPtrInput
	SecurityGroupId           pulumi.StringPtrInput
	SecurityGroupName         pulumi.StringPtrInput
	Tags                      SecurityGroupTagArrayInput
	Timeouts                  SecurityGroupTimeoutsPtrInput
}

func (SecurityGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupState)(nil)).Elem()
}

type securityGroupArgs struct {
	Description               string                 `pulumi:"description"`
	NetId                     *string                `pulumi:"netId"`
	RemoveDefaultOutboundRule *bool                  `pulumi:"removeDefaultOutboundRule"`
	SecurityGroupName         string                 `pulumi:"securityGroupName"`
	Tags                      []SecurityGroupTag     `pulumi:"tags"`
	Timeouts                  *SecurityGroupTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a SecurityGroup resource.
type SecurityGroupArgs struct {
	Description               pulumi.StringInput
	NetId                     pulumi.StringPtrInput
	RemoveDefaultOutboundRule pulumi.BoolPtrInput
	SecurityGroupName         pulumi.StringInput
	Tags                      SecurityGroupTagArrayInput
	Timeouts                  SecurityGroupTimeoutsPtrInput
}

func (SecurityGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupArgs)(nil)).Elem()
}

type SecurityGroupInput interface {
	pulumi.Input

	ToSecurityGroupOutput() SecurityGroupOutput
	ToSecurityGroupOutputWithContext(ctx context.Context) SecurityGroupOutput
}

func (*SecurityGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroup)(nil)).Elem()
}

func (i *SecurityGroup) ToSecurityGroupOutput() SecurityGroupOutput {
	return i.ToSecurityGroupOutputWithContext(context.Background())
}

func (i *SecurityGroup) ToSecurityGroupOutputWithContext(ctx context.Context) SecurityGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupOutput)
}

type SecurityGroupOutput struct{ *pulumi.OutputState }

func (SecurityGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroup)(nil)).Elem()
}

func (o SecurityGroupOutput) ToSecurityGroupOutput() SecurityGroupOutput {
	return o
}

func (o SecurityGroupOutput) ToSecurityGroupOutputWithContext(ctx context.Context) SecurityGroupOutput {
	return o
}

func (o SecurityGroupOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) InboundRules() SecurityGroupInboundRuleArrayOutput {
	return o.ApplyT(func(v *SecurityGroup) SecurityGroupInboundRuleArrayOutput { return v.InboundRules }).(SecurityGroupInboundRuleArrayOutput)
}

func (o SecurityGroupOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) OutboundRules() SecurityGroupOutboundRuleArrayOutput {
	return o.ApplyT(func(v *SecurityGroup) SecurityGroupOutboundRuleArrayOutput { return v.OutboundRules }).(SecurityGroupOutboundRuleArrayOutput)
}

func (o SecurityGroupOutput) RemoveDefaultOutboundRule() pulumi.BoolOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.BoolOutput { return v.RemoveDefaultOutboundRule }).(pulumi.BoolOutput)
}

func (o SecurityGroupOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) SecurityGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.SecurityGroupId }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) SecurityGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroup) pulumi.StringOutput { return v.SecurityGroupName }).(pulumi.StringOutput)
}

func (o SecurityGroupOutput) Tags() SecurityGroupTagArrayOutput {
	return o.ApplyT(func(v *SecurityGroup) SecurityGroupTagArrayOutput { return v.Tags }).(SecurityGroupTagArrayOutput)
}

func (o SecurityGroupOutput) Timeouts() SecurityGroupTimeoutsPtrOutput {
	return o.ApplyT(func(v *SecurityGroup) SecurityGroupTimeoutsPtrOutput { return v.Timeouts }).(SecurityGroupTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupInput)(nil)).Elem(), &SecurityGroup{})
	pulumi.RegisterOutputType(SecurityGroupOutput{})
}
