// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServerCertificate struct {
	pulumi.CustomResourceState

	Body                pulumi.StringPtrOutput `pulumi:"body"`
	Chain               pulumi.StringPtrOutput `pulumi:"chain"`
	DryRun              pulumi.StringPtrOutput `pulumi:"dryRun"`
	ExpirationDate      pulumi.StringOutput    `pulumi:"expirationDate"`
	Name                pulumi.StringOutput    `pulumi:"name"`
	Orn                 pulumi.StringOutput    `pulumi:"orn"`
	Path                pulumi.StringOutput    `pulumi:"path"`
	PrivateKey          pulumi.StringPtrOutput `pulumi:"privateKey"`
	RequestId           pulumi.StringOutput    `pulumi:"requestId"`
	ServerCertificateId pulumi.StringOutput    `pulumi:"serverCertificateId"`
	UploadDate          pulumi.StringOutput    `pulumi:"uploadDate"`
}

// NewServerCertificate registers a new resource with the given unique name, arguments, and options.
func NewServerCertificate(ctx *pulumi.Context,
	name string, args *ServerCertificateArgs, opts ...pulumi.ResourceOption) (*ServerCertificate, error) {
	if args == nil {
		args = &ServerCertificateArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ServerCertificate
	err = ctx.RegisterPackageResource("outscale:index/serverCertificate:ServerCertificate", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerCertificate gets an existing ServerCertificate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerCertificate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerCertificateState, opts ...pulumi.ResourceOption) (*ServerCertificate, error) {
	var resource ServerCertificate
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/serverCertificate:ServerCertificate", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerCertificate resources.
type serverCertificateState struct {
	Body                *string `pulumi:"body"`
	Chain               *string `pulumi:"chain"`
	DryRun              *string `pulumi:"dryRun"`
	ExpirationDate      *string `pulumi:"expirationDate"`
	Name                *string `pulumi:"name"`
	Orn                 *string `pulumi:"orn"`
	Path                *string `pulumi:"path"`
	PrivateKey          *string `pulumi:"privateKey"`
	RequestId           *string `pulumi:"requestId"`
	ServerCertificateId *string `pulumi:"serverCertificateId"`
	UploadDate          *string `pulumi:"uploadDate"`
}

type ServerCertificateState struct {
	Body                pulumi.StringPtrInput
	Chain               pulumi.StringPtrInput
	DryRun              pulumi.StringPtrInput
	ExpirationDate      pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	Orn                 pulumi.StringPtrInput
	Path                pulumi.StringPtrInput
	PrivateKey          pulumi.StringPtrInput
	RequestId           pulumi.StringPtrInput
	ServerCertificateId pulumi.StringPtrInput
	UploadDate          pulumi.StringPtrInput
}

func (ServerCertificateState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCertificateState)(nil)).Elem()
}

type serverCertificateArgs struct {
	Body                *string `pulumi:"body"`
	Chain               *string `pulumi:"chain"`
	DryRun              *string `pulumi:"dryRun"`
	Name                *string `pulumi:"name"`
	Path                *string `pulumi:"path"`
	PrivateKey          *string `pulumi:"privateKey"`
	ServerCertificateId *string `pulumi:"serverCertificateId"`
}

// The set of arguments for constructing a ServerCertificate resource.
type ServerCertificateArgs struct {
	Body                pulumi.StringPtrInput
	Chain               pulumi.StringPtrInput
	DryRun              pulumi.StringPtrInput
	Name                pulumi.StringPtrInput
	Path                pulumi.StringPtrInput
	PrivateKey          pulumi.StringPtrInput
	ServerCertificateId pulumi.StringPtrInput
}

func (ServerCertificateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCertificateArgs)(nil)).Elem()
}

type ServerCertificateInput interface {
	pulumi.Input

	ToServerCertificateOutput() ServerCertificateOutput
	ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput
}

func (*ServerCertificate) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCertificate)(nil)).Elem()
}

func (i *ServerCertificate) ToServerCertificateOutput() ServerCertificateOutput {
	return i.ToServerCertificateOutputWithContext(context.Background())
}

func (i *ServerCertificate) ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCertificateOutput)
}

type ServerCertificateOutput struct{ *pulumi.OutputState }

func (ServerCertificateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCertificate)(nil)).Elem()
}

func (o ServerCertificateOutput) ToServerCertificateOutput() ServerCertificateOutput {
	return o
}

func (o ServerCertificateOutput) ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput {
	return o
}

func (o ServerCertificateOutput) Body() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.Body }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) Chain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.Chain }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) DryRun() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.DryRun }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Orn() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Orn }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) PrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.PrivateKey }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) ServerCertificateId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.ServerCertificateId }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) UploadDate() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.UploadDate }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCertificateInput)(nil)).Elem(), &ServerCertificate{})
	pulumi.RegisterOutputType(ServerCertificateOutput{})
}
