// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Snapshot struct {
	pulumi.CustomResourceState

	AccountAlias               pulumi.StringOutput                          `pulumi:"accountAlias"`
	AccountId                  pulumi.StringOutput                          `pulumi:"accountId"`
	CreationDate               pulumi.StringOutput                          `pulumi:"creationDate"`
	Description                pulumi.StringOutput                          `pulumi:"description"`
	FileLocation               pulumi.StringOutput                          `pulumi:"fileLocation"`
	OutscaleSnapshotId         pulumi.StringOutput                          `pulumi:"outscaleSnapshotId"`
	PermissionsToCreateVolumes SnapshotPermissionsToCreateVolumeArrayOutput `pulumi:"permissionsToCreateVolumes"`
	Progress                   pulumi.Float64Output                         `pulumi:"progress"`
	RequestId                  pulumi.StringOutput                          `pulumi:"requestId"`
	SnapshotId                 pulumi.StringOutput                          `pulumi:"snapshotId"`
	SnapshotSize               pulumi.Float64Output                         `pulumi:"snapshotSize"`
	SourceRegionName           pulumi.StringOutput                          `pulumi:"sourceRegionName"`
	SourceSnapshotId           pulumi.StringOutput                          `pulumi:"sourceSnapshotId"`
	State                      pulumi.StringOutput                          `pulumi:"state"`
	Tags                       SnapshotTagArrayOutput                       `pulumi:"tags"`
	Timeouts                   SnapshotTimeoutsPtrOutput                    `pulumi:"timeouts"`
	VolumeId                   pulumi.StringOutput                          `pulumi:"volumeId"`
	VolumeSize                 pulumi.Float64Output                         `pulumi:"volumeSize"`
}

// NewSnapshot registers a new resource with the given unique name, arguments, and options.
func NewSnapshot(ctx *pulumi.Context,
	name string, args *SnapshotArgs, opts ...pulumi.ResourceOption) (*Snapshot, error) {
	if args == nil {
		args = &SnapshotArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Snapshot
	err = ctx.RegisterPackageResource("outscale:index/snapshot:Snapshot", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSnapshot gets an existing Snapshot resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSnapshot(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SnapshotState, opts ...pulumi.ResourceOption) (*Snapshot, error) {
	var resource Snapshot
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/snapshot:Snapshot", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Snapshot resources.
type snapshotState struct {
	AccountAlias               *string                             `pulumi:"accountAlias"`
	AccountId                  *string                             `pulumi:"accountId"`
	CreationDate               *string                             `pulumi:"creationDate"`
	Description                *string                             `pulumi:"description"`
	FileLocation               *string                             `pulumi:"fileLocation"`
	OutscaleSnapshotId         *string                             `pulumi:"outscaleSnapshotId"`
	PermissionsToCreateVolumes []SnapshotPermissionsToCreateVolume `pulumi:"permissionsToCreateVolumes"`
	Progress                   *float64                            `pulumi:"progress"`
	RequestId                  *string                             `pulumi:"requestId"`
	SnapshotId                 *string                             `pulumi:"snapshotId"`
	SnapshotSize               *float64                            `pulumi:"snapshotSize"`
	SourceRegionName           *string                             `pulumi:"sourceRegionName"`
	SourceSnapshotId           *string                             `pulumi:"sourceSnapshotId"`
	State                      *string                             `pulumi:"state"`
	Tags                       []SnapshotTag                       `pulumi:"tags"`
	Timeouts                   *SnapshotTimeouts                   `pulumi:"timeouts"`
	VolumeId                   *string                             `pulumi:"volumeId"`
	VolumeSize                 *float64                            `pulumi:"volumeSize"`
}

type SnapshotState struct {
	AccountAlias               pulumi.StringPtrInput
	AccountId                  pulumi.StringPtrInput
	CreationDate               pulumi.StringPtrInput
	Description                pulumi.StringPtrInput
	FileLocation               pulumi.StringPtrInput
	OutscaleSnapshotId         pulumi.StringPtrInput
	PermissionsToCreateVolumes SnapshotPermissionsToCreateVolumeArrayInput
	Progress                   pulumi.Float64PtrInput
	RequestId                  pulumi.StringPtrInput
	SnapshotId                 pulumi.StringPtrInput
	SnapshotSize               pulumi.Float64PtrInput
	SourceRegionName           pulumi.StringPtrInput
	SourceSnapshotId           pulumi.StringPtrInput
	State                      pulumi.StringPtrInput
	Tags                       SnapshotTagArrayInput
	Timeouts                   SnapshotTimeoutsPtrInput
	VolumeId                   pulumi.StringPtrInput
	VolumeSize                 pulumi.Float64PtrInput
}

func (SnapshotState) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotState)(nil)).Elem()
}

type snapshotArgs struct {
	Description        *string           `pulumi:"description"`
	FileLocation       *string           `pulumi:"fileLocation"`
	OutscaleSnapshotId *string           `pulumi:"outscaleSnapshotId"`
	SnapshotSize       *float64          `pulumi:"snapshotSize"`
	SourceRegionName   *string           `pulumi:"sourceRegionName"`
	SourceSnapshotId   *string           `pulumi:"sourceSnapshotId"`
	Tags               []SnapshotTag     `pulumi:"tags"`
	Timeouts           *SnapshotTimeouts `pulumi:"timeouts"`
	VolumeId           *string           `pulumi:"volumeId"`
}

// The set of arguments for constructing a Snapshot resource.
type SnapshotArgs struct {
	Description        pulumi.StringPtrInput
	FileLocation       pulumi.StringPtrInput
	OutscaleSnapshotId pulumi.StringPtrInput
	SnapshotSize       pulumi.Float64PtrInput
	SourceRegionName   pulumi.StringPtrInput
	SourceSnapshotId   pulumi.StringPtrInput
	Tags               SnapshotTagArrayInput
	Timeouts           SnapshotTimeoutsPtrInput
	VolumeId           pulumi.StringPtrInput
}

func (SnapshotArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotArgs)(nil)).Elem()
}

type SnapshotInput interface {
	pulumi.Input

	ToSnapshotOutput() SnapshotOutput
	ToSnapshotOutputWithContext(ctx context.Context) SnapshotOutput
}

func (*Snapshot) ElementType() reflect.Type {
	return reflect.TypeOf((**Snapshot)(nil)).Elem()
}

func (i *Snapshot) ToSnapshotOutput() SnapshotOutput {
	return i.ToSnapshotOutputWithContext(context.Background())
}

func (i *Snapshot) ToSnapshotOutputWithContext(ctx context.Context) SnapshotOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SnapshotOutput)
}

type SnapshotOutput struct{ *pulumi.OutputState }

func (SnapshotOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Snapshot)(nil)).Elem()
}

func (o SnapshotOutput) ToSnapshotOutput() SnapshotOutput {
	return o
}

func (o SnapshotOutput) ToSnapshotOutputWithContext(ctx context.Context) SnapshotOutput {
	return o
}

func (o SnapshotOutput) AccountAlias() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.AccountAlias }).(pulumi.StringOutput)
}

func (o SnapshotOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.AccountId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o SnapshotOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o SnapshotOutput) FileLocation() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.FileLocation }).(pulumi.StringOutput)
}

func (o SnapshotOutput) OutscaleSnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.OutscaleSnapshotId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) PermissionsToCreateVolumes() SnapshotPermissionsToCreateVolumeArrayOutput {
	return o.ApplyT(func(v *Snapshot) SnapshotPermissionsToCreateVolumeArrayOutput { return v.PermissionsToCreateVolumes }).(SnapshotPermissionsToCreateVolumeArrayOutput)
}

func (o SnapshotOutput) Progress() pulumi.Float64Output {
	return o.ApplyT(func(v *Snapshot) pulumi.Float64Output { return v.Progress }).(pulumi.Float64Output)
}

func (o SnapshotOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) SnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.SnapshotId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) SnapshotSize() pulumi.Float64Output {
	return o.ApplyT(func(v *Snapshot) pulumi.Float64Output { return v.SnapshotSize }).(pulumi.Float64Output)
}

func (o SnapshotOutput) SourceRegionName() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.SourceRegionName }).(pulumi.StringOutput)
}

func (o SnapshotOutput) SourceSnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.SourceSnapshotId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o SnapshotOutput) Tags() SnapshotTagArrayOutput {
	return o.ApplyT(func(v *Snapshot) SnapshotTagArrayOutput { return v.Tags }).(SnapshotTagArrayOutput)
}

func (o SnapshotOutput) Timeouts() SnapshotTimeoutsPtrOutput {
	return o.ApplyT(func(v *Snapshot) SnapshotTimeoutsPtrOutput { return v.Timeouts }).(SnapshotTimeoutsPtrOutput)
}

func (o SnapshotOutput) VolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Snapshot) pulumi.StringOutput { return v.VolumeId }).(pulumi.StringOutput)
}

func (o SnapshotOutput) VolumeSize() pulumi.Float64Output {
	return o.ApplyT(func(v *Snapshot) pulumi.Float64Output { return v.VolumeSize }).(pulumi.Float64Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SnapshotInput)(nil)).Elem(), &Snapshot{})
	pulumi.RegisterOutputType(SnapshotOutput{})
}
