// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SnapshotExportTask struct {
	pulumi.CustomResourceState

	Comment              pulumi.StringOutput                    `pulumi:"comment"`
	OsuExports           SnapshotExportTaskOsuExportArrayOutput `pulumi:"osuExports"`
	Progress             pulumi.Float64Output                   `pulumi:"progress"`
	RequestId            pulumi.StringOutput                    `pulumi:"requestId"`
	SnapshotExportTaskId pulumi.StringOutput                    `pulumi:"snapshotExportTaskId"`
	SnapshotId           pulumi.StringOutput                    `pulumi:"snapshotId"`
	State                pulumi.StringOutput                    `pulumi:"state"`
	Tags                 SnapshotExportTaskTagArrayOutput       `pulumi:"tags"`
	TaskId               pulumi.StringOutput                    `pulumi:"taskId"`
	Timeouts             SnapshotExportTaskTimeoutsPtrOutput    `pulumi:"timeouts"`
}

// NewSnapshotExportTask registers a new resource with the given unique name, arguments, and options.
func NewSnapshotExportTask(ctx *pulumi.Context,
	name string, args *SnapshotExportTaskArgs, opts ...pulumi.ResourceOption) (*SnapshotExportTask, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OsuExports == nil {
		return nil, errors.New("invalid value for required argument 'OsuExports'")
	}
	if args.SnapshotId == nil {
		return nil, errors.New("invalid value for required argument 'SnapshotId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource SnapshotExportTask
	err = ctx.RegisterPackageResource("outscale:index/snapshotExportTask:SnapshotExportTask", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSnapshotExportTask gets an existing SnapshotExportTask resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSnapshotExportTask(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SnapshotExportTaskState, opts ...pulumi.ResourceOption) (*SnapshotExportTask, error) {
	var resource SnapshotExportTask
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/snapshotExportTask:SnapshotExportTask", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SnapshotExportTask resources.
type snapshotExportTaskState struct {
	Comment              *string                       `pulumi:"comment"`
	OsuExports           []SnapshotExportTaskOsuExport `pulumi:"osuExports"`
	Progress             *float64                      `pulumi:"progress"`
	RequestId            *string                       `pulumi:"requestId"`
	SnapshotExportTaskId *string                       `pulumi:"snapshotExportTaskId"`
	SnapshotId           *string                       `pulumi:"snapshotId"`
	State                *string                       `pulumi:"state"`
	Tags                 []SnapshotExportTaskTag       `pulumi:"tags"`
	TaskId               *string                       `pulumi:"taskId"`
	Timeouts             *SnapshotExportTaskTimeouts   `pulumi:"timeouts"`
}

type SnapshotExportTaskState struct {
	Comment              pulumi.StringPtrInput
	OsuExports           SnapshotExportTaskOsuExportArrayInput
	Progress             pulumi.Float64PtrInput
	RequestId            pulumi.StringPtrInput
	SnapshotExportTaskId pulumi.StringPtrInput
	SnapshotId           pulumi.StringPtrInput
	State                pulumi.StringPtrInput
	Tags                 SnapshotExportTaskTagArrayInput
	TaskId               pulumi.StringPtrInput
	Timeouts             SnapshotExportTaskTimeoutsPtrInput
}

func (SnapshotExportTaskState) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotExportTaskState)(nil)).Elem()
}

type snapshotExportTaskArgs struct {
	OsuExports           []SnapshotExportTaskOsuExport `pulumi:"osuExports"`
	SnapshotExportTaskId *string                       `pulumi:"snapshotExportTaskId"`
	SnapshotId           string                        `pulumi:"snapshotId"`
	Tags                 []SnapshotExportTaskTag       `pulumi:"tags"`
	Timeouts             *SnapshotExportTaskTimeouts   `pulumi:"timeouts"`
}

// The set of arguments for constructing a SnapshotExportTask resource.
type SnapshotExportTaskArgs struct {
	OsuExports           SnapshotExportTaskOsuExportArrayInput
	SnapshotExportTaskId pulumi.StringPtrInput
	SnapshotId           pulumi.StringInput
	Tags                 SnapshotExportTaskTagArrayInput
	Timeouts             SnapshotExportTaskTimeoutsPtrInput
}

func (SnapshotExportTaskArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*snapshotExportTaskArgs)(nil)).Elem()
}

type SnapshotExportTaskInput interface {
	pulumi.Input

	ToSnapshotExportTaskOutput() SnapshotExportTaskOutput
	ToSnapshotExportTaskOutputWithContext(ctx context.Context) SnapshotExportTaskOutput
}

func (*SnapshotExportTask) ElementType() reflect.Type {
	return reflect.TypeOf((**SnapshotExportTask)(nil)).Elem()
}

func (i *SnapshotExportTask) ToSnapshotExportTaskOutput() SnapshotExportTaskOutput {
	return i.ToSnapshotExportTaskOutputWithContext(context.Background())
}

func (i *SnapshotExportTask) ToSnapshotExportTaskOutputWithContext(ctx context.Context) SnapshotExportTaskOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SnapshotExportTaskOutput)
}

type SnapshotExportTaskOutput struct{ *pulumi.OutputState }

func (SnapshotExportTaskOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SnapshotExportTask)(nil)).Elem()
}

func (o SnapshotExportTaskOutput) ToSnapshotExportTaskOutput() SnapshotExportTaskOutput {
	return o
}

func (o SnapshotExportTaskOutput) ToSnapshotExportTaskOutputWithContext(ctx context.Context) SnapshotExportTaskOutput {
	return o
}

func (o SnapshotExportTaskOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.Comment }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) OsuExports() SnapshotExportTaskOsuExportArrayOutput {
	return o.ApplyT(func(v *SnapshotExportTask) SnapshotExportTaskOsuExportArrayOutput { return v.OsuExports }).(SnapshotExportTaskOsuExportArrayOutput)
}

func (o SnapshotExportTaskOutput) Progress() pulumi.Float64Output {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.Float64Output { return v.Progress }).(pulumi.Float64Output)
}

func (o SnapshotExportTaskOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) SnapshotExportTaskId() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.SnapshotExportTaskId }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) SnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.SnapshotId }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) Tags() SnapshotExportTaskTagArrayOutput {
	return o.ApplyT(func(v *SnapshotExportTask) SnapshotExportTaskTagArrayOutput { return v.Tags }).(SnapshotExportTaskTagArrayOutput)
}

func (o SnapshotExportTaskOutput) TaskId() pulumi.StringOutput {
	return o.ApplyT(func(v *SnapshotExportTask) pulumi.StringOutput { return v.TaskId }).(pulumi.StringOutput)
}

func (o SnapshotExportTaskOutput) Timeouts() SnapshotExportTaskTimeoutsPtrOutput {
	return o.ApplyT(func(v *SnapshotExportTask) SnapshotExportTaskTimeoutsPtrOutput { return v.Timeouts }).(SnapshotExportTaskTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SnapshotExportTaskInput)(nil)).Elem(), &SnapshotExportTask{})
	pulumi.RegisterOutputType(SnapshotExportTaskOutput{})
}
