// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Subnet struct {
	pulumi.CustomResourceState

	AvailableIpsCount   pulumi.Float64Output    `pulumi:"availableIpsCount"`
	IpRange             pulumi.StringOutput     `pulumi:"ipRange"`
	MapPublicIpOnLaunch pulumi.BoolOutput       `pulumi:"mapPublicIpOnLaunch"`
	NetId               pulumi.StringOutput     `pulumi:"netId"`
	RequestId           pulumi.StringOutput     `pulumi:"requestId"`
	State               pulumi.StringOutput     `pulumi:"state"`
	SubnetId            pulumi.StringOutput     `pulumi:"subnetId"`
	SubregionName       pulumi.StringOutput     `pulumi:"subregionName"`
	Tags                SubnetTagArrayOutput    `pulumi:"tags"`
	Timeouts            SubnetTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewSubnet registers a new resource with the given unique name, arguments, and options.
func NewSubnet(ctx *pulumi.Context,
	name string, args *SubnetArgs, opts ...pulumi.ResourceOption) (*Subnet, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IpRange == nil {
		return nil, errors.New("invalid value for required argument 'IpRange'")
	}
	if args.NetId == nil {
		return nil, errors.New("invalid value for required argument 'NetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Subnet
	err = ctx.RegisterPackageResource("outscale:index/subnet:Subnet", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSubnet gets an existing Subnet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSubnet(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SubnetState, opts ...pulumi.ResourceOption) (*Subnet, error) {
	var resource Subnet
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/subnet:Subnet", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Subnet resources.
type subnetState struct {
	AvailableIpsCount   *float64        `pulumi:"availableIpsCount"`
	IpRange             *string         `pulumi:"ipRange"`
	MapPublicIpOnLaunch *bool           `pulumi:"mapPublicIpOnLaunch"`
	NetId               *string         `pulumi:"netId"`
	RequestId           *string         `pulumi:"requestId"`
	State               *string         `pulumi:"state"`
	SubnetId            *string         `pulumi:"subnetId"`
	SubregionName       *string         `pulumi:"subregionName"`
	Tags                []SubnetTag     `pulumi:"tags"`
	Timeouts            *SubnetTimeouts `pulumi:"timeouts"`
}

type SubnetState struct {
	AvailableIpsCount   pulumi.Float64PtrInput
	IpRange             pulumi.StringPtrInput
	MapPublicIpOnLaunch pulumi.BoolPtrInput
	NetId               pulumi.StringPtrInput
	RequestId           pulumi.StringPtrInput
	State               pulumi.StringPtrInput
	SubnetId            pulumi.StringPtrInput
	SubregionName       pulumi.StringPtrInput
	Tags                SubnetTagArrayInput
	Timeouts            SubnetTimeoutsPtrInput
}

func (SubnetState) ElementType() reflect.Type {
	return reflect.TypeOf((*subnetState)(nil)).Elem()
}

type subnetArgs struct {
	IpRange             string          `pulumi:"ipRange"`
	MapPublicIpOnLaunch *bool           `pulumi:"mapPublicIpOnLaunch"`
	NetId               string          `pulumi:"netId"`
	SubregionName       *string         `pulumi:"subregionName"`
	Tags                []SubnetTag     `pulumi:"tags"`
	Timeouts            *SubnetTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a Subnet resource.
type SubnetArgs struct {
	IpRange             pulumi.StringInput
	MapPublicIpOnLaunch pulumi.BoolPtrInput
	NetId               pulumi.StringInput
	SubregionName       pulumi.StringPtrInput
	Tags                SubnetTagArrayInput
	Timeouts            SubnetTimeoutsPtrInput
}

func (SubnetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*subnetArgs)(nil)).Elem()
}

type SubnetInput interface {
	pulumi.Input

	ToSubnetOutput() SubnetOutput
	ToSubnetOutputWithContext(ctx context.Context) SubnetOutput
}

func (*Subnet) ElementType() reflect.Type {
	return reflect.TypeOf((**Subnet)(nil)).Elem()
}

func (i *Subnet) ToSubnetOutput() SubnetOutput {
	return i.ToSubnetOutputWithContext(context.Background())
}

func (i *Subnet) ToSubnetOutputWithContext(ctx context.Context) SubnetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SubnetOutput)
}

type SubnetOutput struct{ *pulumi.OutputState }

func (SubnetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Subnet)(nil)).Elem()
}

func (o SubnetOutput) ToSubnetOutput() SubnetOutput {
	return o
}

func (o SubnetOutput) ToSubnetOutputWithContext(ctx context.Context) SubnetOutput {
	return o
}

func (o SubnetOutput) AvailableIpsCount() pulumi.Float64Output {
	return o.ApplyT(func(v *Subnet) pulumi.Float64Output { return v.AvailableIpsCount }).(pulumi.Float64Output)
}

func (o SubnetOutput) IpRange() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.IpRange }).(pulumi.StringOutput)
}

func (o SubnetOutput) MapPublicIpOnLaunch() pulumi.BoolOutput {
	return o.ApplyT(func(v *Subnet) pulumi.BoolOutput { return v.MapPublicIpOnLaunch }).(pulumi.BoolOutput)
}

func (o SubnetOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.NetId }).(pulumi.StringOutput)
}

func (o SubnetOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o SubnetOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o SubnetOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.SubnetId }).(pulumi.StringOutput)
}

func (o SubnetOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v *Subnet) pulumi.StringOutput { return v.SubregionName }).(pulumi.StringOutput)
}

func (o SubnetOutput) Tags() SubnetTagArrayOutput {
	return o.ApplyT(func(v *Subnet) SubnetTagArrayOutput { return v.Tags }).(SubnetTagArrayOutput)
}

func (o SubnetOutput) Timeouts() SubnetTimeoutsPtrOutput {
	return o.ApplyT(func(v *Subnet) SubnetTimeoutsPtrOutput { return v.Timeouts }).(SubnetTimeoutsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SubnetInput)(nil)).Elem(), &Subnet{})
	pulumi.RegisterOutputType(SubnetOutput{})
}
