// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type User struct {
	pulumi.CustomResourceState

	CreationDate         pulumi.StringOutput    `pulumi:"creationDate"`
	LastModificationDate pulumi.StringOutput    `pulumi:"lastModificationDate"`
	OutscaleUserId       pulumi.StringOutput    `pulumi:"outscaleUserId"`
	Path                 pulumi.StringPtrOutput `pulumi:"path"`
	Policies             UserPolicyArrayOutput  `pulumi:"policies"`
	UserEmail            pulumi.StringOutput    `pulumi:"userEmail"`
	UserId               pulumi.StringOutput    `pulumi:"userId"`
	UserName             pulumi.StringOutput    `pulumi:"userName"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.UserName == nil {
		return nil, errors.New("invalid value for required argument 'UserName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource User
	err = ctx.RegisterPackageResource("outscale:index/user:User", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/user:User", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	CreationDate         *string      `pulumi:"creationDate"`
	LastModificationDate *string      `pulumi:"lastModificationDate"`
	OutscaleUserId       *string      `pulumi:"outscaleUserId"`
	Path                 *string      `pulumi:"path"`
	Policies             []UserPolicy `pulumi:"policies"`
	UserEmail            *string      `pulumi:"userEmail"`
	UserId               *string      `pulumi:"userId"`
	UserName             *string      `pulumi:"userName"`
}

type UserState struct {
	CreationDate         pulumi.StringPtrInput
	LastModificationDate pulumi.StringPtrInput
	OutscaleUserId       pulumi.StringPtrInput
	Path                 pulumi.StringPtrInput
	Policies             UserPolicyArrayInput
	UserEmail            pulumi.StringPtrInput
	UserId               pulumi.StringPtrInput
	UserName             pulumi.StringPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	OutscaleUserId *string      `pulumi:"outscaleUserId"`
	Path           *string      `pulumi:"path"`
	Policies       []UserPolicy `pulumi:"policies"`
	UserEmail      *string      `pulumi:"userEmail"`
	UserName       string       `pulumi:"userName"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	OutscaleUserId pulumi.StringPtrInput
	Path           pulumi.StringPtrInput
	Policies       UserPolicyArrayInput
	UserEmail      pulumi.StringPtrInput
	UserName       pulumi.StringInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

func (o UserOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o UserOutput) LastModificationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.LastModificationDate }).(pulumi.StringOutput)
}

func (o UserOutput) OutscaleUserId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.OutscaleUserId }).(pulumi.StringOutput)
}

func (o UserOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Path }).(pulumi.StringPtrOutput)
}

func (o UserOutput) Policies() UserPolicyArrayOutput {
	return o.ApplyT(func(v *User) UserPolicyArrayOutput { return v.Policies }).(UserPolicyArrayOutput)
}

func (o UserOutput) UserEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.UserEmail }).(pulumi.StringOutput)
}

func (o UserOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.UserId }).(pulumi.StringOutput)
}

func (o UserOutput) UserName() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.UserName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterOutputType(UserOutput{})
}
