// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type UserGroup struct {
	pulumi.CustomResourceState

	CreationDate         pulumi.StringOutput        `pulumi:"creationDate"`
	LastModificationDate pulumi.StringOutput        `pulumi:"lastModificationDate"`
	Orn                  pulumi.StringOutput        `pulumi:"orn"`
	OutscaleUserGroupId  pulumi.StringOutput        `pulumi:"outscaleUserGroupId"`
	Path                 pulumi.StringPtrOutput     `pulumi:"path"`
	Policies             UserGroupPolicyArrayOutput `pulumi:"policies"`
	UserGroupId          pulumi.StringOutput        `pulumi:"userGroupId"`
	UserGroupName        pulumi.StringOutput        `pulumi:"userGroupName"`
	Users                UserGroupUserArrayOutput   `pulumi:"users"`
}

// NewUserGroup registers a new resource with the given unique name, arguments, and options.
func NewUserGroup(ctx *pulumi.Context,
	name string, args *UserGroupArgs, opts ...pulumi.ResourceOption) (*UserGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.UserGroupName == nil {
		return nil, errors.New("invalid value for required argument 'UserGroupName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource UserGroup
	err = ctx.RegisterPackageResource("outscale:index/userGroup:UserGroup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUserGroup gets an existing UserGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserGroupState, opts ...pulumi.ResourceOption) (*UserGroup, error) {
	var resource UserGroup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/userGroup:UserGroup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UserGroup resources.
type userGroupState struct {
	CreationDate         *string           `pulumi:"creationDate"`
	LastModificationDate *string           `pulumi:"lastModificationDate"`
	Orn                  *string           `pulumi:"orn"`
	OutscaleUserGroupId  *string           `pulumi:"outscaleUserGroupId"`
	Path                 *string           `pulumi:"path"`
	Policies             []UserGroupPolicy `pulumi:"policies"`
	UserGroupId          *string           `pulumi:"userGroupId"`
	UserGroupName        *string           `pulumi:"userGroupName"`
	Users                []UserGroupUser   `pulumi:"users"`
}

type UserGroupState struct {
	CreationDate         pulumi.StringPtrInput
	LastModificationDate pulumi.StringPtrInput
	Orn                  pulumi.StringPtrInput
	OutscaleUserGroupId  pulumi.StringPtrInput
	Path                 pulumi.StringPtrInput
	Policies             UserGroupPolicyArrayInput
	UserGroupId          pulumi.StringPtrInput
	UserGroupName        pulumi.StringPtrInput
	Users                UserGroupUserArrayInput
}

func (UserGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*userGroupState)(nil)).Elem()
}

type userGroupArgs struct {
	OutscaleUserGroupId *string           `pulumi:"outscaleUserGroupId"`
	Path                *string           `pulumi:"path"`
	Policies            []UserGroupPolicy `pulumi:"policies"`
	UserGroupName       string            `pulumi:"userGroupName"`
	Users               []UserGroupUser   `pulumi:"users"`
}

// The set of arguments for constructing a UserGroup resource.
type UserGroupArgs struct {
	OutscaleUserGroupId pulumi.StringPtrInput
	Path                pulumi.StringPtrInput
	Policies            UserGroupPolicyArrayInput
	UserGroupName       pulumi.StringInput
	Users               UserGroupUserArrayInput
}

func (UserGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userGroupArgs)(nil)).Elem()
}

type UserGroupInput interface {
	pulumi.Input

	ToUserGroupOutput() UserGroupOutput
	ToUserGroupOutputWithContext(ctx context.Context) UserGroupOutput
}

func (*UserGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**UserGroup)(nil)).Elem()
}

func (i *UserGroup) ToUserGroupOutput() UserGroupOutput {
	return i.ToUserGroupOutputWithContext(context.Background())
}

func (i *UserGroup) ToUserGroupOutputWithContext(ctx context.Context) UserGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserGroupOutput)
}

type UserGroupOutput struct{ *pulumi.OutputState }

func (UserGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UserGroup)(nil)).Elem()
}

func (o UserGroupOutput) ToUserGroupOutput() UserGroupOutput {
	return o
}

func (o UserGroupOutput) ToUserGroupOutputWithContext(ctx context.Context) UserGroupOutput {
	return o
}

func (o UserGroupOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o UserGroupOutput) LastModificationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.LastModificationDate }).(pulumi.StringOutput)
}

func (o UserGroupOutput) Orn() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.Orn }).(pulumi.StringOutput)
}

func (o UserGroupOutput) OutscaleUserGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.OutscaleUserGroupId }).(pulumi.StringOutput)
}

func (o UserGroupOutput) Path() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringPtrOutput { return v.Path }).(pulumi.StringPtrOutput)
}

func (o UserGroupOutput) Policies() UserGroupPolicyArrayOutput {
	return o.ApplyT(func(v *UserGroup) UserGroupPolicyArrayOutput { return v.Policies }).(UserGroupPolicyArrayOutput)
}

func (o UserGroupOutput) UserGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.UserGroupId }).(pulumi.StringOutput)
}

func (o UserGroupOutput) UserGroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroup) pulumi.StringOutput { return v.UserGroupName }).(pulumi.StringOutput)
}

func (o UserGroupOutput) Users() UserGroupUserArrayOutput {
	return o.ApplyT(func(v *UserGroup) UserGroupUserArrayOutput { return v.Users }).(UserGroupUserArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserGroupInput)(nil)).Elem(), &UserGroup{})
	pulumi.RegisterOutputType(UserGroupOutput{})
}
