// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VirtualGateway struct {
	pulumi.CustomResourceState

	ConnectionType           pulumi.StringOutput                              `pulumi:"connectionType"`
	NetToVirtualGatewayLinks VirtualGatewayNetToVirtualGatewayLinkArrayOutput `pulumi:"netToVirtualGatewayLinks"`
	OutscaleVirtualGatewayId pulumi.StringOutput                              `pulumi:"outscaleVirtualGatewayId"`
	RequestId                pulumi.StringOutput                              `pulumi:"requestId"`
	State                    pulumi.StringOutput                              `pulumi:"state"`
	Tags                     VirtualGatewayTagArrayOutput                     `pulumi:"tags"`
	VirtualGatewayId         pulumi.StringOutput                              `pulumi:"virtualGatewayId"`
}

// NewVirtualGateway registers a new resource with the given unique name, arguments, and options.
func NewVirtualGateway(ctx *pulumi.Context,
	name string, args *VirtualGatewayArgs, opts ...pulumi.ResourceOption) (*VirtualGateway, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConnectionType == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionType'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource VirtualGateway
	err = ctx.RegisterPackageResource("outscale:index/virtualGateway:VirtualGateway", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVirtualGateway gets an existing VirtualGateway resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVirtualGateway(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VirtualGatewayState, opts ...pulumi.ResourceOption) (*VirtualGateway, error) {
	var resource VirtualGateway
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/virtualGateway:VirtualGateway", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VirtualGateway resources.
type virtualGatewayState struct {
	ConnectionType           *string                                 `pulumi:"connectionType"`
	NetToVirtualGatewayLinks []VirtualGatewayNetToVirtualGatewayLink `pulumi:"netToVirtualGatewayLinks"`
	OutscaleVirtualGatewayId *string                                 `pulumi:"outscaleVirtualGatewayId"`
	RequestId                *string                                 `pulumi:"requestId"`
	State                    *string                                 `pulumi:"state"`
	Tags                     []VirtualGatewayTag                     `pulumi:"tags"`
	VirtualGatewayId         *string                                 `pulumi:"virtualGatewayId"`
}

type VirtualGatewayState struct {
	ConnectionType           pulumi.StringPtrInput
	NetToVirtualGatewayLinks VirtualGatewayNetToVirtualGatewayLinkArrayInput
	OutscaleVirtualGatewayId pulumi.StringPtrInput
	RequestId                pulumi.StringPtrInput
	State                    pulumi.StringPtrInput
	Tags                     VirtualGatewayTagArrayInput
	VirtualGatewayId         pulumi.StringPtrInput
}

func (VirtualGatewayState) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualGatewayState)(nil)).Elem()
}

type virtualGatewayArgs struct {
	ConnectionType           string                                  `pulumi:"connectionType"`
	NetToVirtualGatewayLinks []VirtualGatewayNetToVirtualGatewayLink `pulumi:"netToVirtualGatewayLinks"`
	OutscaleVirtualGatewayId *string                                 `pulumi:"outscaleVirtualGatewayId"`
	RequestId                *string                                 `pulumi:"requestId"`
	State                    *string                                 `pulumi:"state"`
	Tags                     []VirtualGatewayTag                     `pulumi:"tags"`
	VirtualGatewayId         *string                                 `pulumi:"virtualGatewayId"`
}

// The set of arguments for constructing a VirtualGateway resource.
type VirtualGatewayArgs struct {
	ConnectionType           pulumi.StringInput
	NetToVirtualGatewayLinks VirtualGatewayNetToVirtualGatewayLinkArrayInput
	OutscaleVirtualGatewayId pulumi.StringPtrInput
	RequestId                pulumi.StringPtrInput
	State                    pulumi.StringPtrInput
	Tags                     VirtualGatewayTagArrayInput
	VirtualGatewayId         pulumi.StringPtrInput
}

func (VirtualGatewayArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualGatewayArgs)(nil)).Elem()
}

type VirtualGatewayInput interface {
	pulumi.Input

	ToVirtualGatewayOutput() VirtualGatewayOutput
	ToVirtualGatewayOutputWithContext(ctx context.Context) VirtualGatewayOutput
}

func (*VirtualGateway) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualGateway)(nil)).Elem()
}

func (i *VirtualGateway) ToVirtualGatewayOutput() VirtualGatewayOutput {
	return i.ToVirtualGatewayOutputWithContext(context.Background())
}

func (i *VirtualGateway) ToVirtualGatewayOutputWithContext(ctx context.Context) VirtualGatewayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VirtualGatewayOutput)
}

type VirtualGatewayOutput struct{ *pulumi.OutputState }

func (VirtualGatewayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VirtualGateway)(nil)).Elem()
}

func (o VirtualGatewayOutput) ToVirtualGatewayOutput() VirtualGatewayOutput {
	return o
}

func (o VirtualGatewayOutput) ToVirtualGatewayOutputWithContext(ctx context.Context) VirtualGatewayOutput {
	return o
}

func (o VirtualGatewayOutput) ConnectionType() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualGateway) pulumi.StringOutput { return v.ConnectionType }).(pulumi.StringOutput)
}

func (o VirtualGatewayOutput) NetToVirtualGatewayLinks() VirtualGatewayNetToVirtualGatewayLinkArrayOutput {
	return o.ApplyT(func(v *VirtualGateway) VirtualGatewayNetToVirtualGatewayLinkArrayOutput {
		return v.NetToVirtualGatewayLinks
	}).(VirtualGatewayNetToVirtualGatewayLinkArrayOutput)
}

func (o VirtualGatewayOutput) OutscaleVirtualGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualGateway) pulumi.StringOutput { return v.OutscaleVirtualGatewayId }).(pulumi.StringOutput)
}

func (o VirtualGatewayOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualGateway) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o VirtualGatewayOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualGateway) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o VirtualGatewayOutput) Tags() VirtualGatewayTagArrayOutput {
	return o.ApplyT(func(v *VirtualGateway) VirtualGatewayTagArrayOutput { return v.Tags }).(VirtualGatewayTagArrayOutput)
}

func (o VirtualGatewayOutput) VirtualGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v *VirtualGateway) pulumi.StringOutput { return v.VirtualGatewayId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VirtualGatewayInput)(nil)).Elem(), &VirtualGateway{})
	pulumi.RegisterOutputType(VirtualGatewayOutput{})
}
