// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VolumeLink struct {
	pulumi.CustomResourceState

	DeleteOnVmDeletion pulumi.BoolOutput           `pulumi:"deleteOnVmDeletion"`
	DeviceName         pulumi.StringOutput         `pulumi:"deviceName"`
	ForceUnlink        pulumi.BoolOutput           `pulumi:"forceUnlink"`
	RequestId          pulumi.StringOutput         `pulumi:"requestId"`
	State              pulumi.StringOutput         `pulumi:"state"`
	Timeouts           VolumeLinkTimeoutsPtrOutput `pulumi:"timeouts"`
	VmId               pulumi.StringOutput         `pulumi:"vmId"`
	VolumeId           pulumi.StringOutput         `pulumi:"volumeId"`
}

// NewVolumeLink registers a new resource with the given unique name, arguments, and options.
func NewVolumeLink(ctx *pulumi.Context,
	name string, args *VolumeLinkArgs, opts ...pulumi.ResourceOption) (*VolumeLink, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DeviceName == nil {
		return nil, errors.New("invalid value for required argument 'DeviceName'")
	}
	if args.VmId == nil {
		return nil, errors.New("invalid value for required argument 'VmId'")
	}
	if args.VolumeId == nil {
		return nil, errors.New("invalid value for required argument 'VolumeId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource VolumeLink
	err = ctx.RegisterPackageResource("outscale:index/volumeLink:VolumeLink", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolumeLink gets an existing VolumeLink resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolumeLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeLinkState, opts ...pulumi.ResourceOption) (*VolumeLink, error) {
	var resource VolumeLink
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/volumeLink:VolumeLink", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VolumeLink resources.
type volumeLinkState struct {
	DeleteOnVmDeletion *bool               `pulumi:"deleteOnVmDeletion"`
	DeviceName         *string             `pulumi:"deviceName"`
	ForceUnlink        *bool               `pulumi:"forceUnlink"`
	RequestId          *string             `pulumi:"requestId"`
	State              *string             `pulumi:"state"`
	Timeouts           *VolumeLinkTimeouts `pulumi:"timeouts"`
	VmId               *string             `pulumi:"vmId"`
	VolumeId           *string             `pulumi:"volumeId"`
}

type VolumeLinkState struct {
	DeleteOnVmDeletion pulumi.BoolPtrInput
	DeviceName         pulumi.StringPtrInput
	ForceUnlink        pulumi.BoolPtrInput
	RequestId          pulumi.StringPtrInput
	State              pulumi.StringPtrInput
	Timeouts           VolumeLinkTimeoutsPtrInput
	VmId               pulumi.StringPtrInput
	VolumeId           pulumi.StringPtrInput
}

func (VolumeLinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeLinkState)(nil)).Elem()
}

type volumeLinkArgs struct {
	DeviceName  string              `pulumi:"deviceName"`
	ForceUnlink *bool               `pulumi:"forceUnlink"`
	Timeouts    *VolumeLinkTimeouts `pulumi:"timeouts"`
	VmId        string              `pulumi:"vmId"`
	VolumeId    string              `pulumi:"volumeId"`
}

// The set of arguments for constructing a VolumeLink resource.
type VolumeLinkArgs struct {
	DeviceName  pulumi.StringInput
	ForceUnlink pulumi.BoolPtrInput
	Timeouts    VolumeLinkTimeoutsPtrInput
	VmId        pulumi.StringInput
	VolumeId    pulumi.StringInput
}

func (VolumeLinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeLinkArgs)(nil)).Elem()
}

type VolumeLinkInput interface {
	pulumi.Input

	ToVolumeLinkOutput() VolumeLinkOutput
	ToVolumeLinkOutputWithContext(ctx context.Context) VolumeLinkOutput
}

func (*VolumeLink) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumeLink)(nil)).Elem()
}

func (i *VolumeLink) ToVolumeLinkOutput() VolumeLinkOutput {
	return i.ToVolumeLinkOutputWithContext(context.Background())
}

func (i *VolumeLink) ToVolumeLinkOutputWithContext(ctx context.Context) VolumeLinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeLinkOutput)
}

type VolumeLinkOutput struct{ *pulumi.OutputState }

func (VolumeLinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumeLink)(nil)).Elem()
}

func (o VolumeLinkOutput) ToVolumeLinkOutput() VolumeLinkOutput {
	return o
}

func (o VolumeLinkOutput) ToVolumeLinkOutputWithContext(ctx context.Context) VolumeLinkOutput {
	return o
}

func (o VolumeLinkOutput) DeleteOnVmDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.BoolOutput { return v.DeleteOnVmDeletion }).(pulumi.BoolOutput)
}

func (o VolumeLinkOutput) DeviceName() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.StringOutput { return v.DeviceName }).(pulumi.StringOutput)
}

func (o VolumeLinkOutput) ForceUnlink() pulumi.BoolOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.BoolOutput { return v.ForceUnlink }).(pulumi.BoolOutput)
}

func (o VolumeLinkOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o VolumeLinkOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o VolumeLinkOutput) Timeouts() VolumeLinkTimeoutsPtrOutput {
	return o.ApplyT(func(v *VolumeLink) VolumeLinkTimeoutsPtrOutput { return v.Timeouts }).(VolumeLinkTimeoutsPtrOutput)
}

func (o VolumeLinkOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.StringOutput { return v.VmId }).(pulumi.StringOutput)
}

func (o VolumeLinkOutput) VolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *VolumeLink) pulumi.StringOutput { return v.VolumeId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeLinkInput)(nil)).Elem(), &VolumeLink{})
	pulumi.RegisterOutputType(VolumeLinkOutput{})
}
