// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Volume struct {
	pulumi.CustomResourceState

	CreationDate            pulumi.StringOutput           `pulumi:"creationDate"`
	Iops                    pulumi.Float64Output          `pulumi:"iops"`
	LinkedVolumes           VolumeLinkedVolumeArrayOutput `pulumi:"linkedVolumes"`
	RequestId               pulumi.StringOutput           `pulumi:"requestId"`
	Size                    pulumi.Float64Output          `pulumi:"size"`
	SnapshotId              pulumi.StringOutput           `pulumi:"snapshotId"`
	State                   pulumi.StringOutput           `pulumi:"state"`
	SubregionName           pulumi.StringOutput           `pulumi:"subregionName"`
	Tags                    VolumeTagArrayOutput          `pulumi:"tags"`
	TerminationSnapshotName pulumi.StringPtrOutput        `pulumi:"terminationSnapshotName"`
	Timeouts                VolumeTimeoutsPtrOutput       `pulumi:"timeouts"`
	VolumeId                pulumi.StringOutput           `pulumi:"volumeId"`
	VolumeType              pulumi.StringOutput           `pulumi:"volumeType"`
}

// NewVolume registers a new resource with the given unique name, arguments, and options.
func NewVolume(ctx *pulumi.Context,
	name string, args *VolumeArgs, opts ...pulumi.ResourceOption) (*Volume, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SubregionName == nil {
		return nil, errors.New("invalid value for required argument 'SubregionName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Volume
	err = ctx.RegisterPackageResource("outscale:index/volume:Volume", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolume gets an existing Volume resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolume(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeState, opts ...pulumi.ResourceOption) (*Volume, error) {
	var resource Volume
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/volume:Volume", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Volume resources.
type volumeState struct {
	CreationDate            *string              `pulumi:"creationDate"`
	Iops                    *float64             `pulumi:"iops"`
	LinkedVolumes           []VolumeLinkedVolume `pulumi:"linkedVolumes"`
	RequestId               *string              `pulumi:"requestId"`
	Size                    *float64             `pulumi:"size"`
	SnapshotId              *string              `pulumi:"snapshotId"`
	State                   *string              `pulumi:"state"`
	SubregionName           *string              `pulumi:"subregionName"`
	Tags                    []VolumeTag          `pulumi:"tags"`
	TerminationSnapshotName *string              `pulumi:"terminationSnapshotName"`
	Timeouts                *VolumeTimeouts      `pulumi:"timeouts"`
	VolumeId                *string              `pulumi:"volumeId"`
	VolumeType              *string              `pulumi:"volumeType"`
}

type VolumeState struct {
	CreationDate            pulumi.StringPtrInput
	Iops                    pulumi.Float64PtrInput
	LinkedVolumes           VolumeLinkedVolumeArrayInput
	RequestId               pulumi.StringPtrInput
	Size                    pulumi.Float64PtrInput
	SnapshotId              pulumi.StringPtrInput
	State                   pulumi.StringPtrInput
	SubregionName           pulumi.StringPtrInput
	Tags                    VolumeTagArrayInput
	TerminationSnapshotName pulumi.StringPtrInput
	Timeouts                VolumeTimeoutsPtrInput
	VolumeId                pulumi.StringPtrInput
	VolumeType              pulumi.StringPtrInput
}

func (VolumeState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeState)(nil)).Elem()
}

type volumeArgs struct {
	Iops                    *float64        `pulumi:"iops"`
	Size                    *float64        `pulumi:"size"`
	SnapshotId              *string         `pulumi:"snapshotId"`
	SubregionName           string          `pulumi:"subregionName"`
	Tags                    []VolumeTag     `pulumi:"tags"`
	TerminationSnapshotName *string         `pulumi:"terminationSnapshotName"`
	Timeouts                *VolumeTimeouts `pulumi:"timeouts"`
	VolumeType              *string         `pulumi:"volumeType"`
}

// The set of arguments for constructing a Volume resource.
type VolumeArgs struct {
	Iops                    pulumi.Float64PtrInput
	Size                    pulumi.Float64PtrInput
	SnapshotId              pulumi.StringPtrInput
	SubregionName           pulumi.StringInput
	Tags                    VolumeTagArrayInput
	TerminationSnapshotName pulumi.StringPtrInput
	Timeouts                VolumeTimeoutsPtrInput
	VolumeType              pulumi.StringPtrInput
}

func (VolumeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeArgs)(nil)).Elem()
}

type VolumeInput interface {
	pulumi.Input

	ToVolumeOutput() VolumeOutput
	ToVolumeOutputWithContext(ctx context.Context) VolumeOutput
}

func (*Volume) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (i *Volume) ToVolumeOutput() VolumeOutput {
	return i.ToVolumeOutputWithContext(context.Background())
}

func (i *Volume) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeOutput)
}

type VolumeOutput struct{ *pulumi.OutputState }

func (VolumeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (o VolumeOutput) ToVolumeOutput() VolumeOutput {
	return o
}

func (o VolumeOutput) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return o
}

func (o VolumeOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

func (o VolumeOutput) Iops() pulumi.Float64Output {
	return o.ApplyT(func(v *Volume) pulumi.Float64Output { return v.Iops }).(pulumi.Float64Output)
}

func (o VolumeOutput) LinkedVolumes() VolumeLinkedVolumeArrayOutput {
	return o.ApplyT(func(v *Volume) VolumeLinkedVolumeArrayOutput { return v.LinkedVolumes }).(VolumeLinkedVolumeArrayOutput)
}

func (o VolumeOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o VolumeOutput) Size() pulumi.Float64Output {
	return o.ApplyT(func(v *Volume) pulumi.Float64Output { return v.Size }).(pulumi.Float64Output)
}

func (o VolumeOutput) SnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.SnapshotId }).(pulumi.StringOutput)
}

func (o VolumeOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func (o VolumeOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.SubregionName }).(pulumi.StringOutput)
}

func (o VolumeOutput) Tags() VolumeTagArrayOutput {
	return o.ApplyT(func(v *Volume) VolumeTagArrayOutput { return v.Tags }).(VolumeTagArrayOutput)
}

func (o VolumeOutput) TerminationSnapshotName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringPtrOutput { return v.TerminationSnapshotName }).(pulumi.StringPtrOutput)
}

func (o VolumeOutput) Timeouts() VolumeTimeoutsPtrOutput {
	return o.ApplyT(func(v *Volume) VolumeTimeoutsPtrOutput { return v.Timeouts }).(VolumeTimeoutsPtrOutput)
}

func (o VolumeOutput) VolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.VolumeId }).(pulumi.StringOutput)
}

func (o VolumeOutput) VolumeType() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.VolumeType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeInput)(nil)).Elem(), &Volume{})
	pulumi.RegisterOutputType(VolumeOutput{})
}
