// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/outscale/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VpnConnectionRoute struct {
	pulumi.CustomResourceState

	DestinationIpRange   pulumi.StringOutput `pulumi:"destinationIpRange"`
	RequestId            pulumi.StringOutput `pulumi:"requestId"`
	VpnConnectionId      pulumi.StringOutput `pulumi:"vpnConnectionId"`
	VpnConnectionRouteId pulumi.StringOutput `pulumi:"vpnConnectionRouteId"`
}

// NewVpnConnectionRoute registers a new resource with the given unique name, arguments, and options.
func NewVpnConnectionRoute(ctx *pulumi.Context,
	name string, args *VpnConnectionRouteArgs, opts ...pulumi.ResourceOption) (*VpnConnectionRoute, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DestinationIpRange == nil {
		return nil, errors.New("invalid value for required argument 'DestinationIpRange'")
	}
	if args.VpnConnectionId == nil {
		return nil, errors.New("invalid value for required argument 'VpnConnectionId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource VpnConnectionRoute
	err = ctx.RegisterPackageResource("outscale:index/vpnConnectionRoute:VpnConnectionRoute", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVpnConnectionRoute gets an existing VpnConnectionRoute resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVpnConnectionRoute(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VpnConnectionRouteState, opts ...pulumi.ResourceOption) (*VpnConnectionRoute, error) {
	var resource VpnConnectionRoute
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("outscale:index/vpnConnectionRoute:VpnConnectionRoute", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VpnConnectionRoute resources.
type vpnConnectionRouteState struct {
	DestinationIpRange   *string `pulumi:"destinationIpRange"`
	RequestId            *string `pulumi:"requestId"`
	VpnConnectionId      *string `pulumi:"vpnConnectionId"`
	VpnConnectionRouteId *string `pulumi:"vpnConnectionRouteId"`
}

type VpnConnectionRouteState struct {
	DestinationIpRange   pulumi.StringPtrInput
	RequestId            pulumi.StringPtrInput
	VpnConnectionId      pulumi.StringPtrInput
	VpnConnectionRouteId pulumi.StringPtrInput
}

func (VpnConnectionRouteState) ElementType() reflect.Type {
	return reflect.TypeOf((*vpnConnectionRouteState)(nil)).Elem()
}

type vpnConnectionRouteArgs struct {
	DestinationIpRange   string  `pulumi:"destinationIpRange"`
	VpnConnectionId      string  `pulumi:"vpnConnectionId"`
	VpnConnectionRouteId *string `pulumi:"vpnConnectionRouteId"`
}

// The set of arguments for constructing a VpnConnectionRoute resource.
type VpnConnectionRouteArgs struct {
	DestinationIpRange   pulumi.StringInput
	VpnConnectionId      pulumi.StringInput
	VpnConnectionRouteId pulumi.StringPtrInput
}

func (VpnConnectionRouteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vpnConnectionRouteArgs)(nil)).Elem()
}

type VpnConnectionRouteInput interface {
	pulumi.Input

	ToVpnConnectionRouteOutput() VpnConnectionRouteOutput
	ToVpnConnectionRouteOutputWithContext(ctx context.Context) VpnConnectionRouteOutput
}

func (*VpnConnectionRoute) ElementType() reflect.Type {
	return reflect.TypeOf((**VpnConnectionRoute)(nil)).Elem()
}

func (i *VpnConnectionRoute) ToVpnConnectionRouteOutput() VpnConnectionRouteOutput {
	return i.ToVpnConnectionRouteOutputWithContext(context.Background())
}

func (i *VpnConnectionRoute) ToVpnConnectionRouteOutputWithContext(ctx context.Context) VpnConnectionRouteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VpnConnectionRouteOutput)
}

type VpnConnectionRouteOutput struct{ *pulumi.OutputState }

func (VpnConnectionRouteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VpnConnectionRoute)(nil)).Elem()
}

func (o VpnConnectionRouteOutput) ToVpnConnectionRouteOutput() VpnConnectionRouteOutput {
	return o
}

func (o VpnConnectionRouteOutput) ToVpnConnectionRouteOutputWithContext(ctx context.Context) VpnConnectionRouteOutput {
	return o
}

func (o VpnConnectionRouteOutput) DestinationIpRange() pulumi.StringOutput {
	return o.ApplyT(func(v *VpnConnectionRoute) pulumi.StringOutput { return v.DestinationIpRange }).(pulumi.StringOutput)
}

func (o VpnConnectionRouteOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *VpnConnectionRoute) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o VpnConnectionRouteOutput) VpnConnectionId() pulumi.StringOutput {
	return o.ApplyT(func(v *VpnConnectionRoute) pulumi.StringOutput { return v.VpnConnectionId }).(pulumi.StringOutput)
}

func (o VpnConnectionRouteOutput) VpnConnectionRouteId() pulumi.StringOutput {
	return o.ApplyT(func(v *VpnConnectionRoute) pulumi.StringOutput { return v.VpnConnectionRouteId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VpnConnectionRouteInput)(nil)).Elem(), &VpnConnectionRoute{})
	pulumi.RegisterOutputType(VpnConnectionRouteOutput{})
}
