apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: openbao
  namespace: security
spec:
  parentRefs:
  - name: openaether-gateway
  hostnames:
  - "vault.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: openbao
      port: 8200
