apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
  namespace: security
  labels:
    app: openbao
spec:
  serviceName: openbao
  replicas: 3
  selector:
    matchLabels:
      app: openbao
  template:
    metadata:
      labels:
        app: openbao
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: openbao
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: openbao
      containers:
      - name: openbao
        image: openbao/openbao:2.0.0
        args:
          - server
        env:
          - name: BAO_API_ADDR
            value: "http://0.0.0.0:8200"
        ports:
          - containerPort: 8200
            name: http
          - containerPort: 8201
            name: cluster
        securityContext:
          capabilities:
            add: ["IPC_LOCK"] # Often needed for mlock, verify if can run without
        volumeMounts:
          - name: data
            mountPath: /bao/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
