apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      server: "http://openbao.security.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # Using Kubernetes Auth (preferred for pod-to-vault)
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-operator"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
